/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.controllers;

import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import tech.fortis.sandbox.api.ApiHelper;
import tech.fortis.sandbox.api.Server;
import tech.fortis.sandbox.api.exceptions.ApiException;
import tech.fortis.sandbox.api.exceptions.Response401TokenException;
import tech.fortis.sandbox.api.exceptions.Response412Exception;
import tech.fortis.sandbox.api.http.request.HttpMethod;
import tech.fortis.sandbox.api.http.response.ApiResponse;
import tech.fortis.sandbox.api.models.Expand26;
import tech.fortis.sandbox.api.models.Field43;
import tech.fortis.sandbox.api.models.FilterBy;
import tech.fortis.sandbox.api.models.Format1;
import tech.fortis.sandbox.api.models.Order21;
import tech.fortis.sandbox.api.models.Page1;
import tech.fortis.sandbox.api.models.ResponseRecurring;
import tech.fortis.sandbox.api.models.ResponseRecurringsCollection;
import tech.fortis.sandbox.api.models.V1RecurringsDeferPaymentRequest;
import tech.fortis.sandbox.api.models.V1RecurringsRequest;
import tech.fortis.sandbox.api.models.V1RecurringsRequest1;
import tech.fortis.sandbox.api.models.V1RecurringsSkipPaymentRequest;

/**
 * This class lists all the endpoints of the groups.
 */
public final class RecurringController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public RecurringController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * @param  body  Required parameter:
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<ResponseRecurring> createanewrecurringrecord(
            final V1RecurringsRequest body,
            final List<Expand26> expand) throws ApiException, IOException {
        return prepareCreateanewrecurringrecordRequest(body, expand).execute();
    }

    /**
     * @param  body  Required parameter:
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<ResponseRecurring>> createanewrecurringrecordAsync(
            final V1RecurringsRequest body,
            final List<Expand26> expand) {
        try {
            return prepareCreateanewrecurringrecordRequest(body, expand).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for createanewrecurringrecord.
     */
    private ApiCall<ApiResponse<ResponseRecurring>, ApiException> prepareCreateanewrecurringrecordRequest(
            final V1RecurringsRequest body,
            final List<Expand26> expand) {
        return new ApiCall.Builder<ApiResponse<ResponseRecurring>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v1/recurrings")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .queryParam(param -> param.key("expand")
                                .value(Expand26.toValue(expand)).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .and(andAuth -> andAuth
                                        .add("user-id")
                                        .add("user-api-key")
                                        .add("developer-id")))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, ResponseRecurring.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new Response401TokenException(reason, context)))
                        .localErrorCase("412",
                                 ErrorCase.setReason("Precondition Failed",
                                (reason, context) -> new Response412Exception(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  page  Optional parameter: Use this field to specify paginate your results, by using
     *         page size and number. You can use one of the following methods: &gt;/endpoint?page={
     *         "number": 1, "size": 50 } &gt; &gt;/endpoint?page[number]=1&amp;page[size]=50 &gt;
     * @param  order  Optional parameter: Criteria used in query string parameters to order results.
     *         Most fields from the endpoint results can be used as a `key`. Unsupported fields or
     *         operators will return a `412`. Must be encoded, or use syntax that does not require
     *         encoding. &gt;/endpoint?order[0][key]=created_ts&amp;order[0][operator]=asc &gt;
     *         &gt;/endpoint?order=[{ "key": "created_ts", "operator": "asc"}] &gt;
     *         &gt;/endpoint?order=[{ "key": "balance", "operator": "desc"},{ "key": "created_ts",
     *         "operator": "asc"}] &gt;
     * @param  filterBy  Optional parameter: Filter criteria that can be used in query string
     *         parameters. Most fields from the endpoint results can be used as a `key`. Unsupported
     *         fields or operators will return a `412`. Must be encoded, or use syntax that does not
     *         require encoding.
     *         &gt;?filter_by[0][key]=first_name&amp;filter_by[0][operator]==&amp;filter_by[0][value]=Steve
     *         &gt; &gt;/endpoint?filter_by=[{ "key": "first_name", "operator": "=", "value": "Fred"
     *         }] &gt; &gt;/endpoint?filter_by=[{ "key": "account_type", "operator": "=", "value":
     *         "VISA" }] &gt; &gt;/endpoint?filter_by=[{ "key": "created_ts", "operator": "&gt;=",
     *         "value": "946702799" }, { "key": "created_ts", "operator": "&lt;=", value:
     *         "1695061891" }] &gt; &gt;/endpoint?filter_by=[{ "key": "last_name", "operator": "IN",
     *         "value": "Williams,Brown,Allman" }] &gt;
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @param  format  Optional parameter: Reporting format, valid values: csv, tsv
     * @param  typeahead  Optional parameter: You can use any `field_name` from this endpoint
     *         results to order the list using the value provided as filter for the same
     *         `field_name`. It will be ordered using the following rules: 1) Exact match, 2) Starts
     *         with, 3) Contains. &gt;/endpoint?filter={ "field_name": "Value"
     *         }&amp;_typeahead=field_name &gt;
     * @param  fields  Optional parameter: You can use any `field_name` from this endpoint results
     *         to filter the list of fields returned on the response.
     * @return    Returns the ResponseRecurringsCollection wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<ResponseRecurringsCollection> listallrecurringrecord(
            final Page1 page,
            final List<Order21> order,
            final List<FilterBy> filterBy,
            final List<Expand26> expand,
            final Format1 format,
            final String typeahead,
            final List<Field43> fields) throws ApiException, IOException {
        return prepareListallrecurringrecordRequest(page, order, filterBy, expand, format,
                typeahead, fields).execute();
    }

    /**
     * @param  page  Optional parameter: Use this field to specify paginate your results, by using
     *         page size and number. You can use one of the following methods: &gt;/endpoint?page={
     *         "number": 1, "size": 50 } &gt; &gt;/endpoint?page[number]=1&amp;page[size]=50 &gt;
     * @param  order  Optional parameter: Criteria used in query string parameters to order results.
     *         Most fields from the endpoint results can be used as a `key`. Unsupported fields or
     *         operators will return a `412`. Must be encoded, or use syntax that does not require
     *         encoding. &gt;/endpoint?order[0][key]=created_ts&amp;order[0][operator]=asc &gt;
     *         &gt;/endpoint?order=[{ "key": "created_ts", "operator": "asc"}] &gt;
     *         &gt;/endpoint?order=[{ "key": "balance", "operator": "desc"},{ "key": "created_ts",
     *         "operator": "asc"}] &gt;
     * @param  filterBy  Optional parameter: Filter criteria that can be used in query string
     *         parameters. Most fields from the endpoint results can be used as a `key`. Unsupported
     *         fields or operators will return a `412`. Must be encoded, or use syntax that does not
     *         require encoding.
     *         &gt;?filter_by[0][key]=first_name&amp;filter_by[0][operator]==&amp;filter_by[0][value]=Steve
     *         &gt; &gt;/endpoint?filter_by=[{ "key": "first_name", "operator": "=", "value": "Fred"
     *         }] &gt; &gt;/endpoint?filter_by=[{ "key": "account_type", "operator": "=", "value":
     *         "VISA" }] &gt; &gt;/endpoint?filter_by=[{ "key": "created_ts", "operator": "&gt;=",
     *         "value": "946702799" }, { "key": "created_ts", "operator": "&lt;=", value:
     *         "1695061891" }] &gt; &gt;/endpoint?filter_by=[{ "key": "last_name", "operator": "IN",
     *         "value": "Williams,Brown,Allman" }] &gt;
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @param  format  Optional parameter: Reporting format, valid values: csv, tsv
     * @param  typeahead  Optional parameter: You can use any `field_name` from this endpoint
     *         results to order the list using the value provided as filter for the same
     *         `field_name`. It will be ordered using the following rules: 1) Exact match, 2) Starts
     *         with, 3) Contains. &gt;/endpoint?filter={ "field_name": "Value"
     *         }&amp;_typeahead=field_name &gt;
     * @param  fields  Optional parameter: You can use any `field_name` from this endpoint results
     *         to filter the list of fields returned on the response.
     * @return    Returns the ResponseRecurringsCollection wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<ResponseRecurringsCollection>> listallrecurringrecordAsync(
            final Page1 page,
            final List<Order21> order,
            final List<FilterBy> filterBy,
            final List<Expand26> expand,
            final Format1 format,
            final String typeahead,
            final List<Field43> fields) {
        try {
            return prepareListallrecurringrecordRequest(page, order, filterBy, expand, format, typeahead,
            fields).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for listallrecurringrecord.
     */
    private ApiCall<ApiResponse<ResponseRecurringsCollection>, ApiException> prepareListallrecurringrecordRequest(
            final Page1 page,
            final List<Order21> order,
            final List<FilterBy> filterBy,
            final List<Expand26> expand,
            final Format1 format,
            final String typeahead,
            final List<Field43> fields) {
        return new ApiCall.Builder<ApiResponse<ResponseRecurringsCollection>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v1/recurrings")
                        .queryParam(param -> param.key("page")
                                .value(page).isRequired(false))
                        .queryParam(param -> param.key("order")
                                .value(order).isRequired(false))
                        .queryParam(param -> param.key("filter_by")
                                .value(filterBy).isRequired(false))
                        .queryParam(param -> param.key("expand")
                                .value(Expand26.toValue(expand)).isRequired(false))
                        .queryParam(param -> param.key("_format")
                                .value((format != null) ? format.value() : null).isRequired(false))
                        .queryParam(param -> param.key("_typeahead")
                                .value(typeahead).isRequired(false))
                        .queryParam(param -> param.key("fields")
                                .value(Field43.toValue(fields)).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .and(andAuth -> andAuth
                                        .add("user-id")
                                        .add("user-api-key")
                                        .add("developer-id")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, ResponseRecurringsCollection.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new Response401TokenException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<ResponseRecurring> deleterecurringrecord(
            final String recurringId) throws ApiException, IOException {
        return prepareDeleterecurringrecordRequest(recurringId).execute();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<ResponseRecurring>> deleterecurringrecordAsync(
            final String recurringId) {
        try {
            return prepareDeleterecurringrecordRequest(recurringId).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for deleterecurringrecord.
     */
    private ApiCall<ApiResponse<ResponseRecurring>, ApiException> prepareDeleterecurringrecordRequest(
            final String recurringId) {
        return new ApiCall.Builder<ApiResponse<ResponseRecurring>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v1/recurrings/{recurring_id}")
                        .templateParam(param -> param.key("recurring_id").value(recurringId)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .and(andAuth -> andAuth
                                        .add("user-id")
                                        .add("user-api-key")
                                        .add("developer-id")))
                        .httpMethod(HttpMethod.DELETE))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, ResponseRecurring.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new Response401TokenException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @param  fields  Optional parameter: You can use any `field_name` from this endpoint results
     *         to filter the list of fields returned on the response.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<ResponseRecurring> viewsinglerecurringrecord(
            final String recurringId,
            final List<Expand26> expand,
            final List<Field43> fields) throws ApiException, IOException {
        return prepareViewsinglerecurringrecordRequest(recurringId, expand, fields).execute();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @param  fields  Optional parameter: You can use any `field_name` from this endpoint results
     *         to filter the list of fields returned on the response.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<ResponseRecurring>> viewsinglerecurringrecordAsync(
            final String recurringId,
            final List<Expand26> expand,
            final List<Field43> fields) {
        try {
            return prepareViewsinglerecurringrecordRequest(recurringId, expand, fields).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for viewsinglerecurringrecord.
     */
    private ApiCall<ApiResponse<ResponseRecurring>, ApiException> prepareViewsinglerecurringrecordRequest(
            final String recurringId,
            final List<Expand26> expand,
            final List<Field43> fields) {
        return new ApiCall.Builder<ApiResponse<ResponseRecurring>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v1/recurrings/{recurring_id}")
                        .queryParam(param -> param.key("expand")
                                .value(Expand26.toValue(expand)).isRequired(false))
                        .queryParam(param -> param.key("fields")
                                .value(Field43.toValue(fields)).isRequired(false))
                        .templateParam(param -> param.key("recurring_id").value(recurringId)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .and(andAuth -> andAuth
                                        .add("user-id")
                                        .add("user-api-key")
                                        .add("developer-id")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, ResponseRecurring.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new Response401TokenException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @param  body  Required parameter:
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<ResponseRecurring> updaterecurringpayment(
            final String recurringId,
            final V1RecurringsRequest1 body,
            final List<Expand26> expand) throws ApiException, IOException {
        return prepareUpdaterecurringpaymentRequest(recurringId, body, expand).execute();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @param  body  Required parameter:
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<ResponseRecurring>> updaterecurringpaymentAsync(
            final String recurringId,
            final V1RecurringsRequest1 body,
            final List<Expand26> expand) {
        try {
            return prepareUpdaterecurringpaymentRequest(recurringId, body, expand).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for updaterecurringpayment.
     */
    private ApiCall<ApiResponse<ResponseRecurring>, ApiException> prepareUpdaterecurringpaymentRequest(
            final String recurringId,
            final V1RecurringsRequest1 body,
            final List<Expand26> expand) {
        return new ApiCall.Builder<ApiResponse<ResponseRecurring>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v1/recurrings/{recurring_id}")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .queryParam(param -> param.key("expand")
                                .value(Expand26.toValue(expand)).isRequired(false))
                        .templateParam(param -> param.key("recurring_id").value(recurringId)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .and(andAuth -> andAuth
                                        .add("user-id")
                                        .add("user-api-key")
                                        .add("developer-id")))
                        .httpMethod(HttpMethod.PATCH))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, ResponseRecurring.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new Response401TokenException(reason, context)))
                        .localErrorCase("412",
                                 ErrorCase.setReason("Precondition Failed",
                                (reason, context) -> new Response412Exception(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<ResponseRecurring> activaterecurringpayment(
            final String recurringId,
            final List<Expand26> expand) throws ApiException, IOException {
        return prepareActivaterecurringpaymentRequest(recurringId, expand).execute();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<ResponseRecurring>> activaterecurringpaymentAsync(
            final String recurringId,
            final List<Expand26> expand) {
        try {
            return prepareActivaterecurringpaymentRequest(recurringId, expand).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for activaterecurringpayment.
     */
    private ApiCall<ApiResponse<ResponseRecurring>, ApiException> prepareActivaterecurringpaymentRequest(
            final String recurringId,
            final List<Expand26> expand) {
        return new ApiCall.Builder<ApiResponse<ResponseRecurring>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v1/recurrings/{recurring_id}/activate")
                        .queryParam(param -> param.key("expand")
                                .value(Expand26.toValue(expand)).isRequired(false))
                        .templateParam(param -> param.key("recurring_id").value(recurringId)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .and(andAuth -> andAuth
                                        .add("user-id")
                                        .add("user-api-key")
                                        .add("developer-id")))
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, ResponseRecurring.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new Response401TokenException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @param  body  Required parameter:
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<ResponseRecurring> deferrecurringpayment(
            final String recurringId,
            final V1RecurringsDeferPaymentRequest body,
            final List<Expand26> expand) throws ApiException, IOException {
        return prepareDeferrecurringpaymentRequest(recurringId, body, expand).execute();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @param  body  Required parameter:
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<ResponseRecurring>> deferrecurringpaymentAsync(
            final String recurringId,
            final V1RecurringsDeferPaymentRequest body,
            final List<Expand26> expand) {
        try {
            return prepareDeferrecurringpaymentRequest(recurringId, body, expand).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for deferrecurringpayment.
     */
    private ApiCall<ApiResponse<ResponseRecurring>, ApiException> prepareDeferrecurringpaymentRequest(
            final String recurringId,
            final V1RecurringsDeferPaymentRequest body,
            final List<Expand26> expand) {
        return new ApiCall.Builder<ApiResponse<ResponseRecurring>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v1/recurrings/{recurring_id}/defer-payment")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .queryParam(param -> param.key("expand")
                                .value(Expand26.toValue(expand)).isRequired(false))
                        .templateParam(param -> param.key("recurring_id").value(recurringId)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .and(andAuth -> andAuth
                                        .add("user-id")
                                        .add("user-api-key")
                                        .add("developer-id")))
                        .httpMethod(HttpMethod.PATCH))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, ResponseRecurring.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new Response401TokenException(reason, context)))
                        .localErrorCase("412",
                                 ErrorCase.setReason("Precondition Failed",
                                (reason, context) -> new Response412Exception(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<ResponseRecurring> placeonholdrecurringpayment(
            final String recurringId,
            final List<Expand26> expand) throws ApiException, IOException {
        return preparePlaceonholdrecurringpaymentRequest(recurringId, expand).execute();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<ResponseRecurring>> placeonholdrecurringpaymentAsync(
            final String recurringId,
            final List<Expand26> expand) {
        try {
            return preparePlaceonholdrecurringpaymentRequest(recurringId, expand).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for placeonholdrecurringpayment.
     */
    private ApiCall<ApiResponse<ResponseRecurring>, ApiException> preparePlaceonholdrecurringpaymentRequest(
            final String recurringId,
            final List<Expand26> expand) {
        return new ApiCall.Builder<ApiResponse<ResponseRecurring>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v1/recurrings/{recurring_id}/place-on-hold")
                        .queryParam(param -> param.key("expand")
                                .value(Expand26.toValue(expand)).isRequired(false))
                        .templateParam(param -> param.key("recurring_id").value(recurringId)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .and(andAuth -> andAuth
                                        .add("user-id")
                                        .add("user-api-key")
                                        .add("developer-id")))
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, ResponseRecurring.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new Response401TokenException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @param  body  Required parameter:
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<ResponseRecurring> skiprecurringpayment(
            final String recurringId,
            final V1RecurringsSkipPaymentRequest body,
            final List<Expand26> expand) throws ApiException, IOException {
        return prepareSkiprecurringpaymentRequest(recurringId, body, expand).execute();
    }

    /**
     * @param  recurringId  Required parameter: Recurring ID
     * @param  body  Required parameter:
     * @param  expand  Optional parameter: Most endpoints in the API have a way to retrieve extra
     *         data related to the current record being retrieved. For example, if the API request
     *         is for the accountvaults endpoint, and the end user also needs to know which contact
     *         the token belongs to, this data can be returned in the accountvaults endpoint
     *         request.
     * @return    Returns the ResponseRecurring wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<ResponseRecurring>> skiprecurringpaymentAsync(
            final String recurringId,
            final V1RecurringsSkipPaymentRequest body,
            final List<Expand26> expand) {
        try {
            return prepareSkiprecurringpaymentRequest(recurringId, body, expand).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for skiprecurringpayment.
     */
    private ApiCall<ApiResponse<ResponseRecurring>, ApiException> prepareSkiprecurringpaymentRequest(
            final String recurringId,
            final V1RecurringsSkipPaymentRequest body,
            final List<Expand26> expand) {
        return new ApiCall.Builder<ApiResponse<ResponseRecurring>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/v1/recurrings/{recurring_id}/skip-payment")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .queryParam(param -> param.key("expand")
                                .value(Expand26.toValue(expand)).isRequired(false))
                        .templateParam(param -> param.key("recurring_id").value(recurringId)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json").isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .and(andAuth -> andAuth
                                        .add("user-id")
                                        .add("user-api-key")
                                        .add("developer-id")))
                        .httpMethod(HttpMethod.PATCH))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, ResponseRecurring.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new Response401TokenException(reason, context)))
                        .localErrorCase("412",
                                 ErrorCase.setReason("Precondition Failed",
                                (reason, context) -> new Response412Exception(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}