/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.authentication;

/**
 * Interface for defining the behavior of CustomHeader Authentication.
 */
public interface DeveloperIdCredentials {

    /**
     * String value for developerId.
     * @return developerId
     */
    String getDeveloperId();

    /**
     * Checks if provided credentials matched with existing ones.
     * @param developerId String value for credentials.
     * @return true if credentials matched.
     */
    boolean equals(String developerId);
}
