/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models.containers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;
import tech.fortis.sandbox.api.ApiHelper;

/**
 * This is a container class for any-of types.
 */
@JsonDeserialize(using = V1ElementsTransactionIntentionRequestSecondaryAmount.V1ElementsTransactionIntentionRequestSecondaryAmountDeserializer.class)
public abstract class V1ElementsTransactionIntentionRequestSecondaryAmount {
    
    /**
     * This is V1ElementsTransactionIntentionRequestSecondaryAmountCase0 case.
     * @param v1ElementsTransactionIntentionRequestSecondaryAmountCase0 V1ElementsTransactionIntentionRequestSecondaryAmountCase0 value for v1ElementsTransactionIntentionRequestSecondaryAmountCase0.
     * @return The Case0 object.
     */
    public static V1ElementsTransactionIntentionRequestSecondaryAmount fromV1ElementsTransactionIntentionRequestSecondaryAmountCase0(
            V1ElementsTransactionIntentionRequestSecondaryAmountCase0 v1ElementsTransactionIntentionRequestSecondaryAmountCase0) {
        return v1ElementsTransactionIntentionRequestSecondaryAmountCase0 == null ? null : new Case0(v1ElementsTransactionIntentionRequestSecondaryAmountCase0);
    }

    /**
     * Method to match from the provided any-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The any-of type cases callback.
     * @return The any-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for any-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R v1ElementsTransactionIntentionRequestSecondaryAmountCase0(V1ElementsTransactionIntentionRequestSecondaryAmountCase0 v1ElementsTransactionIntentionRequestSecondaryAmountCase0);
    }

    /**
     * This is a implementation class for Case0Case.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "V1ElementsTransactionIntentionRequestSecondaryAmountCase0")
    private static class Case0 extends V1ElementsTransactionIntentionRequestSecondaryAmount {

        @JsonValue
        private V1ElementsTransactionIntentionRequestSecondaryAmountCase0 case0;

        Case0(V1ElementsTransactionIntentionRequestSecondaryAmountCase0 case0) {
            this.case0 = case0;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.v1ElementsTransactionIntentionRequestSecondaryAmountCase0(this.case0);
        }

        @JsonCreator
        private Case0(JsonNode jsonNode) throws IOException {
            this.case0 = ApiHelper.deserialize(jsonNode,
                V1ElementsTransactionIntentionRequestSecondaryAmountCase0.class);
        }

        @Override
        public String toString() {
            return case0.toString();
        }
    }

    /**
     * This is a custom deserializer class for V1ElementsTransactionIntentionRequestSecondaryAmount.
     */
    protected static class V1ElementsTransactionIntentionRequestSecondaryAmountDeserializer
            extends JsonDeserializer<V1ElementsTransactionIntentionRequestSecondaryAmount> {

        @Override
        public V1ElementsTransactionIntentionRequestSecondaryAmount deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(Case0.class), false);
        }
    }

}
