/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for AccountInfo1 type.
 */
public class AccountInfo1 {
    private ChAccAgeInd chAccAgeInd;
    private String chAccDate;
    private ChAccChangeInd chAccChangeInd;
    private String chAccChange;
    private ChAccPwChangeInd chAccPwChangeInd;
    private String chAccPwChange;
    private ShipAddressUsageInd shipAddressUsageInd;
    private String shipAddressUsage;
    private Integer txnActivityDay;
    private Integer txnActivityYear;
    private Integer provisionAttemptsDay;
    private Integer nbPurchaseAccount;
    private SuspiciousAccActivity suspiciousAccActivity;
    private ShipNameIndicator shipNameIndicator;
    private PaymentAccInd paymentAccInd;
    private String paymentAccAge;
    private OptionalNullable<String> chAccReqId;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public AccountInfo1() {
    }

    /**
     * Initialization constructor.
     * @param  chAccAgeInd  ChAccAgeInd value for chAccAgeInd.
     * @param  chAccDate  String value for chAccDate.
     * @param  chAccChangeInd  ChAccChangeInd value for chAccChangeInd.
     * @param  chAccChange  String value for chAccChange.
     * @param  chAccPwChangeInd  ChAccPwChangeInd value for chAccPwChangeInd.
     * @param  chAccPwChange  String value for chAccPwChange.
     * @param  shipAddressUsageInd  ShipAddressUsageInd value for shipAddressUsageInd.
     * @param  shipAddressUsage  String value for shipAddressUsage.
     * @param  txnActivityDay  Integer value for txnActivityDay.
     * @param  txnActivityYear  Integer value for txnActivityYear.
     * @param  provisionAttemptsDay  Integer value for provisionAttemptsDay.
     * @param  nbPurchaseAccount  Integer value for nbPurchaseAccount.
     * @param  suspiciousAccActivity  SuspiciousAccActivity value for suspiciousAccActivity.
     * @param  shipNameIndicator  ShipNameIndicator value for shipNameIndicator.
     * @param  paymentAccInd  PaymentAccInd value for paymentAccInd.
     * @param  paymentAccAge  String value for paymentAccAge.
     * @param  chAccReqId  String value for chAccReqId.
     */
    public AccountInfo1(
            ChAccAgeInd chAccAgeInd,
            String chAccDate,
            ChAccChangeInd chAccChangeInd,
            String chAccChange,
            ChAccPwChangeInd chAccPwChangeInd,
            String chAccPwChange,
            ShipAddressUsageInd shipAddressUsageInd,
            String shipAddressUsage,
            Integer txnActivityDay,
            Integer txnActivityYear,
            Integer provisionAttemptsDay,
            Integer nbPurchaseAccount,
            SuspiciousAccActivity suspiciousAccActivity,
            ShipNameIndicator shipNameIndicator,
            PaymentAccInd paymentAccInd,
            String paymentAccAge,
            String chAccReqId) {
        this.chAccAgeInd = chAccAgeInd;
        this.chAccDate = chAccDate;
        this.chAccChangeInd = chAccChangeInd;
        this.chAccChange = chAccChange;
        this.chAccPwChangeInd = chAccPwChangeInd;
        this.chAccPwChange = chAccPwChange;
        this.shipAddressUsageInd = shipAddressUsageInd;
        this.shipAddressUsage = shipAddressUsage;
        this.txnActivityDay = txnActivityDay;
        this.txnActivityYear = txnActivityYear;
        this.provisionAttemptsDay = provisionAttemptsDay;
        this.nbPurchaseAccount = nbPurchaseAccount;
        this.suspiciousAccActivity = suspiciousAccActivity;
        this.shipNameIndicator = shipNameIndicator;
        this.paymentAccInd = paymentAccInd;
        this.paymentAccAge = paymentAccAge;
        this.chAccReqId = OptionalNullable.of(chAccReqId);
    }

    /**
     * Initialization constructor.
     * @param  chAccAgeInd  ChAccAgeInd value for chAccAgeInd.
     * @param  chAccDate  String value for chAccDate.
     * @param  chAccChangeInd  ChAccChangeInd value for chAccChangeInd.
     * @param  chAccChange  String value for chAccChange.
     * @param  chAccPwChangeInd  ChAccPwChangeInd value for chAccPwChangeInd.
     * @param  chAccPwChange  String value for chAccPwChange.
     * @param  shipAddressUsageInd  ShipAddressUsageInd value for shipAddressUsageInd.
     * @param  shipAddressUsage  String value for shipAddressUsage.
     * @param  txnActivityDay  Integer value for txnActivityDay.
     * @param  txnActivityYear  Integer value for txnActivityYear.
     * @param  provisionAttemptsDay  Integer value for provisionAttemptsDay.
     * @param  nbPurchaseAccount  Integer value for nbPurchaseAccount.
     * @param  suspiciousAccActivity  SuspiciousAccActivity value for suspiciousAccActivity.
     * @param  shipNameIndicator  ShipNameIndicator value for shipNameIndicator.
     * @param  paymentAccInd  PaymentAccInd value for paymentAccInd.
     * @param  paymentAccAge  String value for paymentAccAge.
     * @param  chAccReqId  String value for chAccReqId.
     */

    protected AccountInfo1(ChAccAgeInd chAccAgeInd, String chAccDate, ChAccChangeInd chAccChangeInd,
            String chAccChange, ChAccPwChangeInd chAccPwChangeInd, String chAccPwChange,
            ShipAddressUsageInd shipAddressUsageInd, String shipAddressUsage,
            Integer txnActivityDay, Integer txnActivityYear, Integer provisionAttemptsDay,
            Integer nbPurchaseAccount, SuspiciousAccActivity suspiciousAccActivity,
            ShipNameIndicator shipNameIndicator, PaymentAccInd paymentAccInd, String paymentAccAge,
            OptionalNullable<String> chAccReqId) {
        this.chAccAgeInd = chAccAgeInd;
        this.chAccDate = chAccDate;
        this.chAccChangeInd = chAccChangeInd;
        this.chAccChange = chAccChange;
        this.chAccPwChangeInd = chAccPwChangeInd;
        this.chAccPwChange = chAccPwChange;
        this.shipAddressUsageInd = shipAddressUsageInd;
        this.shipAddressUsage = shipAddressUsage;
        this.txnActivityDay = txnActivityDay;
        this.txnActivityYear = txnActivityYear;
        this.provisionAttemptsDay = provisionAttemptsDay;
        this.nbPurchaseAccount = nbPurchaseAccount;
        this.suspiciousAccActivity = suspiciousAccActivity;
        this.shipNameIndicator = shipNameIndicator;
        this.paymentAccInd = paymentAccInd;
        this.paymentAccAge = paymentAccAge;
        this.chAccReqId = chAccReqId;
    }

    /**
     * Getter for ChAccAgeInd.
     * @return Returns the ChAccAgeInd
     */
    @JsonGetter("ch_acc_age_ind")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ChAccAgeInd getChAccAgeInd() {
        return chAccAgeInd;
    }

    /**
     * Setter for ChAccAgeInd.
     * @param chAccAgeInd Value for ChAccAgeInd
     */
    @JsonSetter("ch_acc_age_ind")
    public void setChAccAgeInd(ChAccAgeInd chAccAgeInd) {
        this.chAccAgeInd = chAccAgeInd;
    }

    /**
     * Getter for ChAccDate.
     * Date converted into UTC that the cardholder opened the account with the 3DS Requestor. Date
     * format = YYYYMMDD.
     * @return Returns the String
     */
    @JsonGetter("ch_acc_date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getChAccDate() {
        return chAccDate;
    }

    /**
     * Setter for ChAccDate.
     * Date converted into UTC that the cardholder opened the account with the 3DS Requestor. Date
     * format = YYYYMMDD.
     * @param chAccDate Value for String
     */
    @JsonSetter("ch_acc_date")
    public void setChAccDate(String chAccDate) {
        this.chAccDate = chAccDate;
    }

    /**
     * Getter for ChAccChangeInd.
     * @return Returns the ChAccChangeInd
     */
    @JsonGetter("ch_acc_change_ind")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ChAccChangeInd getChAccChangeInd() {
        return chAccChangeInd;
    }

    /**
     * Setter for ChAccChangeInd.
     * @param chAccChangeInd Value for ChAccChangeInd
     */
    @JsonSetter("ch_acc_change_ind")
    public void setChAccChangeInd(ChAccChangeInd chAccChangeInd) {
        this.chAccChangeInd = chAccChangeInd;
    }

    /**
     * Getter for ChAccChange.
     * Date converted into UTC that the cardholder's account with the 3DS Requestor was last
     * changed. Including Billing or Shipping address, new payment account, or new user(s) added.
     * Date format = YYYYMMDD.
     * @return Returns the String
     */
    @JsonGetter("ch_acc_change")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getChAccChange() {
        return chAccChange;
    }

    /**
     * Setter for ChAccChange.
     * Date converted into UTC that the cardholder's account with the 3DS Requestor was last
     * changed. Including Billing or Shipping address, new payment account, or new user(s) added.
     * Date format = YYYYMMDD.
     * @param chAccChange Value for String
     */
    @JsonSetter("ch_acc_change")
    public void setChAccChange(String chAccChange) {
        this.chAccChange = chAccChange;
    }

    /**
     * Getter for ChAccPwChangeInd.
     * @return Returns the ChAccPwChangeInd
     */
    @JsonGetter("ch_acc_pw_change_ind")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ChAccPwChangeInd getChAccPwChangeInd() {
        return chAccPwChangeInd;
    }

    /**
     * Setter for ChAccPwChangeInd.
     * @param chAccPwChangeInd Value for ChAccPwChangeInd
     */
    @JsonSetter("ch_acc_pw_change_ind")
    public void setChAccPwChangeInd(ChAccPwChangeInd chAccPwChangeInd) {
        this.chAccPwChangeInd = chAccPwChangeInd;
    }

    /**
     * Getter for ChAccPwChange.
     * Date converted into UTC that cardholder's account with the 3DS Requestor had a password
     * change or account reset. Date format must be YYYYMMDD.
     * @return Returns the String
     */
    @JsonGetter("ch_acc_pw_change")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getChAccPwChange() {
        return chAccPwChange;
    }

    /**
     * Setter for ChAccPwChange.
     * Date converted into UTC that cardholder's account with the 3DS Requestor had a password
     * change or account reset. Date format must be YYYYMMDD.
     * @param chAccPwChange Value for String
     */
    @JsonSetter("ch_acc_pw_change")
    public void setChAccPwChange(String chAccPwChange) {
        this.chAccPwChange = chAccPwChange;
    }

    /**
     * Getter for ShipAddressUsageInd.
     * @return Returns the ShipAddressUsageInd
     */
    @JsonGetter("ship_address_usage_ind")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShipAddressUsageInd getShipAddressUsageInd() {
        return shipAddressUsageInd;
    }

    /**
     * Setter for ShipAddressUsageInd.
     * @param shipAddressUsageInd Value for ShipAddressUsageInd
     */
    @JsonSetter("ship_address_usage_ind")
    public void setShipAddressUsageInd(ShipAddressUsageInd shipAddressUsageInd) {
        this.shipAddressUsageInd = shipAddressUsageInd;
    }

    /**
     * Getter for ShipAddressUsage.
     * Date converted into UTC when the shipping address used for this transaction was first used
     * with the 3DS Requestor. Date format must be YYYYMMDD.
     * @return Returns the String
     */
    @JsonGetter("ship_address_usage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getShipAddressUsage() {
        return shipAddressUsage;
    }

    /**
     * Setter for ShipAddressUsage.
     * Date converted into UTC when the shipping address used for this transaction was first used
     * with the 3DS Requestor. Date format must be YYYYMMDD.
     * @param shipAddressUsage Value for String
     */
    @JsonSetter("ship_address_usage")
    public void setShipAddressUsage(String shipAddressUsage) {
        this.shipAddressUsage = shipAddressUsage;
    }

    /**
     * Getter for TxnActivityDay.
     * Number of transactions (successful and abandoned) for this cardholder account with the 3DS
     * Requestor across all payment accounts in the previous 24 hours.
     * @return Returns the Integer
     */
    @JsonGetter("txn_activity_day")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTxnActivityDay() {
        return txnActivityDay;
    }

    /**
     * Setter for TxnActivityDay.
     * Number of transactions (successful and abandoned) for this cardholder account with the 3DS
     * Requestor across all payment accounts in the previous 24 hours.
     * @param txnActivityDay Value for Integer
     */
    @JsonSetter("txn_activity_day")
    public void setTxnActivityDay(Integer txnActivityDay) {
        this.txnActivityDay = txnActivityDay;
    }

    /**
     * Getter for TxnActivityYear.
     * Number of transactions (successful and abandoned) for this cardholder account with the 3DS
     * Requestor across all payment accounts in the previous year.
     * @return Returns the Integer
     */
    @JsonGetter("txn_activity_year")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTxnActivityYear() {
        return txnActivityYear;
    }

    /**
     * Setter for TxnActivityYear.
     * Number of transactions (successful and abandoned) for this cardholder account with the 3DS
     * Requestor across all payment accounts in the previous year.
     * @param txnActivityYear Value for Integer
     */
    @JsonSetter("txn_activity_year")
    public void setTxnActivityYear(Integer txnActivityYear) {
        this.txnActivityYear = txnActivityYear;
    }

    /**
     * Getter for ProvisionAttemptsDay.
     * Number of Add Card attempts in the last 24 hours.
     * @return Returns the Integer
     */
    @JsonGetter("provision_attempts_day")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getProvisionAttemptsDay() {
        return provisionAttemptsDay;
    }

    /**
     * Setter for ProvisionAttemptsDay.
     * Number of Add Card attempts in the last 24 hours.
     * @param provisionAttemptsDay Value for Integer
     */
    @JsonSetter("provision_attempts_day")
    public void setProvisionAttemptsDay(Integer provisionAttemptsDay) {
        this.provisionAttemptsDay = provisionAttemptsDay;
    }

    /**
     * Getter for NbPurchaseAccount.
     * Number of purchases with this cardholder account during the previous six months.
     * @return Returns the Integer
     */
    @JsonGetter("nb_purchase_account")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNbPurchaseAccount() {
        return nbPurchaseAccount;
    }

    /**
     * Setter for NbPurchaseAccount.
     * Number of purchases with this cardholder account during the previous six months.
     * @param nbPurchaseAccount Value for Integer
     */
    @JsonSetter("nb_purchase_account")
    public void setNbPurchaseAccount(Integer nbPurchaseAccount) {
        this.nbPurchaseAccount = nbPurchaseAccount;
    }

    /**
     * Getter for SuspiciousAccActivity.
     * @return Returns the SuspiciousAccActivity
     */
    @JsonGetter("suspicious_acc_activity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SuspiciousAccActivity getSuspiciousAccActivity() {
        return suspiciousAccActivity;
    }

    /**
     * Setter for SuspiciousAccActivity.
     * @param suspiciousAccActivity Value for SuspiciousAccActivity
     */
    @JsonSetter("suspicious_acc_activity")
    public void setSuspiciousAccActivity(SuspiciousAccActivity suspiciousAccActivity) {
        this.suspiciousAccActivity = suspiciousAccActivity;
    }

    /**
     * Getter for ShipNameIndicator.
     * @return Returns the ShipNameIndicator
     */
    @JsonGetter("ship_name_indicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShipNameIndicator getShipNameIndicator() {
        return shipNameIndicator;
    }

    /**
     * Setter for ShipNameIndicator.
     * @param shipNameIndicator Value for ShipNameIndicator
     */
    @JsonSetter("ship_name_indicator")
    public void setShipNameIndicator(ShipNameIndicator shipNameIndicator) {
        this.shipNameIndicator = shipNameIndicator;
    }

    /**
     * Getter for PaymentAccInd.
     * @return Returns the PaymentAccInd
     */
    @JsonGetter("payment_acc_ind")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PaymentAccInd getPaymentAccInd() {
        return paymentAccInd;
    }

    /**
     * Setter for PaymentAccInd.
     * @param paymentAccInd Value for PaymentAccInd
     */
    @JsonSetter("payment_acc_ind")
    public void setPaymentAccInd(PaymentAccInd paymentAccInd) {
        this.paymentAccInd = paymentAccInd;
    }

    /**
     * Getter for PaymentAccAge.
     * Date converted into UTC that the payment account was enrolled in the cardholder's account
     * with the 3DS Requestor. Date format must be YYYYMMDD.
     * @return Returns the String
     */
    @JsonGetter("payment_acc_age")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPaymentAccAge() {
        return paymentAccAge;
    }

    /**
     * Setter for PaymentAccAge.
     * Date converted into UTC that the payment account was enrolled in the cardholder's account
     * with the 3DS Requestor. Date format must be YYYYMMDD.
     * @param paymentAccAge Value for String
     */
    @JsonSetter("payment_acc_age")
    public void setPaymentAccAge(String paymentAccAge) {
        this.paymentAccAge = paymentAccAge;
    }

    /**
     * Internal Getter for ChAccReqId.
     * The 3DS Requestor assigned account identifier of the transacting Cardholder. This identifier
     * is a unique representation of the account identifier for the 3DS Requestor and is provided as
     * a String. This field is supported in Starting from EMV 3DS 2.3.1 and later.
     * @return Returns the Internal String
     */
    @JsonGetter("ch_acc_req_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetChAccReqId() {
        return this.chAccReqId;
    }

    /**
     * Getter for ChAccReqId.
     * The 3DS Requestor assigned account identifier of the transacting Cardholder. This identifier
     * is a unique representation of the account identifier for the 3DS Requestor and is provided as
     * a String. This field is supported in Starting from EMV 3DS 2.3.1 and later.
     * @return Returns the String
     */
    public String getChAccReqId() {
        return OptionalNullable.getFrom(chAccReqId);
    }

    /**
     * Setter for ChAccReqId.
     * The 3DS Requestor assigned account identifier of the transacting Cardholder. This identifier
     * is a unique representation of the account identifier for the 3DS Requestor and is provided as
     * a String. This field is supported in Starting from EMV 3DS 2.3.1 and later.
     * @param chAccReqId Value for String
     */
    @JsonSetter("ch_acc_req_id")
    public void setChAccReqId(String chAccReqId) {
        this.chAccReqId = OptionalNullable.of(chAccReqId);
    }

    /**
     * UnSetter for ChAccReqId.
     * The 3DS Requestor assigned account identifier of the transacting Cardholder. This identifier
     * is a unique representation of the account identifier for the 3DS Requestor and is provided as
     * a String. This field is supported in Starting from EMV 3DS 2.3.1 and later.
     */
    public void unsetChAccReqId() {
        chAccReqId = null;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this AccountInfo1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccountInfo1 [" + "chAccAgeInd=" + chAccAgeInd + ", chAccDate=" + chAccDate
                + ", chAccChangeInd=" + chAccChangeInd + ", chAccChange=" + chAccChange
                + ", chAccPwChangeInd=" + chAccPwChangeInd + ", chAccPwChange=" + chAccPwChange
                + ", shipAddressUsageInd=" + shipAddressUsageInd + ", shipAddressUsage="
                + shipAddressUsage + ", txnActivityDay=" + txnActivityDay + ", txnActivityYear="
                + txnActivityYear + ", provisionAttemptsDay=" + provisionAttemptsDay
                + ", nbPurchaseAccount=" + nbPurchaseAccount + ", suspiciousAccActivity="
                + suspiciousAccActivity + ", shipNameIndicator=" + shipNameIndicator
                + ", paymentAccInd=" + paymentAccInd + ", paymentAccAge=" + paymentAccAge
                + ", chAccReqId=" + chAccReqId + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link AccountInfo1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccountInfo1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .chAccAgeInd(getChAccAgeInd())
                .chAccDate(getChAccDate())
                .chAccChangeInd(getChAccChangeInd())
                .chAccChange(getChAccChange())
                .chAccPwChangeInd(getChAccPwChangeInd())
                .chAccPwChange(getChAccPwChange())
                .shipAddressUsageInd(getShipAddressUsageInd())
                .shipAddressUsage(getShipAddressUsage())
                .txnActivityDay(getTxnActivityDay())
                .txnActivityYear(getTxnActivityYear())
                .provisionAttemptsDay(getProvisionAttemptsDay())
                .nbPurchaseAccount(getNbPurchaseAccount())
                .suspiciousAccActivity(getSuspiciousAccActivity())
                .shipNameIndicator(getShipNameIndicator())
                .paymentAccInd(getPaymentAccInd())
                .paymentAccAge(getPaymentAccAge());
        builder.chAccReqId = internalGetChAccReqId();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link AccountInfo1}.
     */
    public static class Builder {
        private ChAccAgeInd chAccAgeInd;
        private String chAccDate;
        private ChAccChangeInd chAccChangeInd;
        private String chAccChange;
        private ChAccPwChangeInd chAccPwChangeInd;
        private String chAccPwChange;
        private ShipAddressUsageInd shipAddressUsageInd;
        private String shipAddressUsage;
        private Integer txnActivityDay;
        private Integer txnActivityYear;
        private Integer provisionAttemptsDay;
        private Integer nbPurchaseAccount;
        private SuspiciousAccActivity suspiciousAccActivity;
        private ShipNameIndicator shipNameIndicator;
        private PaymentAccInd paymentAccInd;
        private String paymentAccAge;
        private OptionalNullable<String> chAccReqId;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for chAccAgeInd.
         * @param  chAccAgeInd  ChAccAgeInd value for chAccAgeInd.
         * @return Builder
         */
        public Builder chAccAgeInd(ChAccAgeInd chAccAgeInd) {
            this.chAccAgeInd = chAccAgeInd;
            return this;
        }

        /**
         * Setter for chAccDate.
         * @param  chAccDate  String value for chAccDate.
         * @return Builder
         */
        public Builder chAccDate(String chAccDate) {
            this.chAccDate = chAccDate;
            return this;
        }

        /**
         * Setter for chAccChangeInd.
         * @param  chAccChangeInd  ChAccChangeInd value for chAccChangeInd.
         * @return Builder
         */
        public Builder chAccChangeInd(ChAccChangeInd chAccChangeInd) {
            this.chAccChangeInd = chAccChangeInd;
            return this;
        }

        /**
         * Setter for chAccChange.
         * @param  chAccChange  String value for chAccChange.
         * @return Builder
         */
        public Builder chAccChange(String chAccChange) {
            this.chAccChange = chAccChange;
            return this;
        }

        /**
         * Setter for chAccPwChangeInd.
         * @param  chAccPwChangeInd  ChAccPwChangeInd value for chAccPwChangeInd.
         * @return Builder
         */
        public Builder chAccPwChangeInd(ChAccPwChangeInd chAccPwChangeInd) {
            this.chAccPwChangeInd = chAccPwChangeInd;
            return this;
        }

        /**
         * Setter for chAccPwChange.
         * @param  chAccPwChange  String value for chAccPwChange.
         * @return Builder
         */
        public Builder chAccPwChange(String chAccPwChange) {
            this.chAccPwChange = chAccPwChange;
            return this;
        }

        /**
         * Setter for shipAddressUsageInd.
         * @param  shipAddressUsageInd  ShipAddressUsageInd value for shipAddressUsageInd.
         * @return Builder
         */
        public Builder shipAddressUsageInd(ShipAddressUsageInd shipAddressUsageInd) {
            this.shipAddressUsageInd = shipAddressUsageInd;
            return this;
        }

        /**
         * Setter for shipAddressUsage.
         * @param  shipAddressUsage  String value for shipAddressUsage.
         * @return Builder
         */
        public Builder shipAddressUsage(String shipAddressUsage) {
            this.shipAddressUsage = shipAddressUsage;
            return this;
        }

        /**
         * Setter for txnActivityDay.
         * @param  txnActivityDay  Integer value for txnActivityDay.
         * @return Builder
         */
        public Builder txnActivityDay(Integer txnActivityDay) {
            this.txnActivityDay = txnActivityDay;
            return this;
        }

        /**
         * Setter for txnActivityYear.
         * @param  txnActivityYear  Integer value for txnActivityYear.
         * @return Builder
         */
        public Builder txnActivityYear(Integer txnActivityYear) {
            this.txnActivityYear = txnActivityYear;
            return this;
        }

        /**
         * Setter for provisionAttemptsDay.
         * @param  provisionAttemptsDay  Integer value for provisionAttemptsDay.
         * @return Builder
         */
        public Builder provisionAttemptsDay(Integer provisionAttemptsDay) {
            this.provisionAttemptsDay = provisionAttemptsDay;
            return this;
        }

        /**
         * Setter for nbPurchaseAccount.
         * @param  nbPurchaseAccount  Integer value for nbPurchaseAccount.
         * @return Builder
         */
        public Builder nbPurchaseAccount(Integer nbPurchaseAccount) {
            this.nbPurchaseAccount = nbPurchaseAccount;
            return this;
        }

        /**
         * Setter for suspiciousAccActivity.
         * @param  suspiciousAccActivity  SuspiciousAccActivity value for suspiciousAccActivity.
         * @return Builder
         */
        public Builder suspiciousAccActivity(SuspiciousAccActivity suspiciousAccActivity) {
            this.suspiciousAccActivity = suspiciousAccActivity;
            return this;
        }

        /**
         * Setter for shipNameIndicator.
         * @param  shipNameIndicator  ShipNameIndicator value for shipNameIndicator.
         * @return Builder
         */
        public Builder shipNameIndicator(ShipNameIndicator shipNameIndicator) {
            this.shipNameIndicator = shipNameIndicator;
            return this;
        }

        /**
         * Setter for paymentAccInd.
         * @param  paymentAccInd  PaymentAccInd value for paymentAccInd.
         * @return Builder
         */
        public Builder paymentAccInd(PaymentAccInd paymentAccInd) {
            this.paymentAccInd = paymentAccInd;
            return this;
        }

        /**
         * Setter for paymentAccAge.
         * @param  paymentAccAge  String value for paymentAccAge.
         * @return Builder
         */
        public Builder paymentAccAge(String paymentAccAge) {
            this.paymentAccAge = paymentAccAge;
            return this;
        }

        /**
         * Setter for chAccReqId.
         * @param  chAccReqId  String value for chAccReqId.
         * @return Builder
         */
        public Builder chAccReqId(String chAccReqId) {
            this.chAccReqId = OptionalNullable.of(chAccReqId);
            return this;
        }

        /**
         * UnSetter for chAccReqId.
         * @return Builder
         */
        public Builder unsetChAccReqId() {
            chAccReqId = null;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link AccountInfo1} object using the set fields.
         * @return {@link AccountInfo1}
         */
        public AccountInfo1 build() {
            AccountInfo1 model =
                    new AccountInfo1(chAccAgeInd, chAccDate, chAccChangeInd, chAccChange,
                            chAccPwChangeInd, chAccPwChange, shipAddressUsageInd, shipAddressUsage,
                            txnActivityDay, txnActivityYear, provisionAttemptsDay,
                            nbPurchaseAccount, suspiciousAccActivity, shipNameIndicator,
                            paymentAccInd, paymentAccAge, chAccReqId);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
