/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for AdditionalAccess type.
 */
public class AdditionalAccess
        extends BaseModel {
    private Boolean merchantIcOptimization;

    /**
     * Default constructor.
     */
    public AdditionalAccess() {
    }

    /**
     * Initialization constructor.
     * @param  merchantIcOptimization  Boolean value for merchantIcOptimization.
     */
    public AdditionalAccess(
            Boolean merchantIcOptimization) {
        this.merchantIcOptimization = merchantIcOptimization;
    }

    /**
     * Getter for MerchantIcOptimization.
     * @return Returns the Boolean
     */
    @JsonGetter("merchant_ic_optimization")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getMerchantIcOptimization() {
        return merchantIcOptimization;
    }

    /**
     * Setter for MerchantIcOptimization.
     * @param merchantIcOptimization Value for Boolean
     */
    @JsonSetter("merchant_ic_optimization")
    public void setMerchantIcOptimization(Boolean merchantIcOptimization) {
        this.merchantIcOptimization = merchantIcOptimization;
    }

    /**
     * Converts this AdditionalAccess into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AdditionalAccess [" + "merchantIcOptimization=" + merchantIcOptimization
                + ", additionalProperties=" + getAdditionalProperties() + "]";
    }

    /**
     * Builds a new {@link AdditionalAccess.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AdditionalAccess.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .merchantIcOptimization(getMerchantIcOptimization());
        return builder;
    }

    /**
     * Class to build instances of {@link AdditionalAccess}.
     */
    public static class Builder {
        private Boolean merchantIcOptimization;



        /**
         * Setter for merchantIcOptimization.
         * @param  merchantIcOptimization  Boolean value for merchantIcOptimization.
         * @return Builder
         */
        public Builder merchantIcOptimization(Boolean merchantIcOptimization) {
            this.merchantIcOptimization = merchantIcOptimization;
            return this;
        }

        /**
         * Builds a new {@link AdditionalAccess} object using the set fields.
         * @return {@link AdditionalAccess}
         */
        public AdditionalAccess build() {
            return new AdditionalAccess(merchantIcOptimization);
        }
    }
}
