/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Conditions type.
 */
public class Conditions
        extends BaseModel {
    private MethodEnum method;
    private ValuesEnum values;

    /**
     * Default constructor.
     */
    public Conditions() {
    }

    /**
     * Initialization constructor.
     * @param  method  MethodEnum value for method.
     * @param  values  ValuesEnum value for values.
     */
    public Conditions(
            MethodEnum method,
            ValuesEnum values) {
        this.method = method;
        this.values = values;
    }

    /**
     * Getter for Method.
     * @return Returns the MethodEnum
     */
    @JsonGetter("method")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MethodEnum getMethod() {
        return method;
    }

    /**
     * Setter for Method.
     * @param method Value for MethodEnum
     */
    @JsonSetter("method")
    public void setMethod(MethodEnum method) {
        this.method = method;
    }

    /**
     * Getter for Values.
     * @return Returns the ValuesEnum
     */
    @JsonGetter("values")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ValuesEnum getValues() {
        return values;
    }

    /**
     * Setter for Values.
     * @param values Value for ValuesEnum
     */
    @JsonSetter("values")
    public void setValues(ValuesEnum values) {
        this.values = values;
    }

    /**
     * Converts this Conditions into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Conditions [" + "method=" + method + ", values=" + values
                + ", additionalProperties=" + getAdditionalProperties() + "]";
    }

    /**
     * Builds a new {@link Conditions.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Conditions.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .method(getMethod())
                .values(getValues());
        return builder;
    }

    /**
     * Class to build instances of {@link Conditions}.
     */
    public static class Builder {
        private MethodEnum method;
        private ValuesEnum values;



        /**
         * Setter for method.
         * @param  method  MethodEnum value for method.
         * @return Builder
         */
        public Builder method(MethodEnum method) {
            this.method = method;
            return this;
        }

        /**
         * Setter for values.
         * @param  values  ValuesEnum value for values.
         * @return Builder
         */
        public Builder values(ValuesEnum values) {
            this.values = values;
            return this;
        }

        /**
         * Builds a new {@link Conditions} object using the set fields.
         * @return {@link Conditions}
         */
        public Conditions build() {
            return new Conditions(method, values);
        }
    }
}
