/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Data12 type.
 */
public class Data12 {
    private String threeDsServerTransId;
    private String acsUrl;
    private TransactionStatus transactionStatus;
    private String authenticationValue;
    private String eci;
    private String dsTransId;
    private String acsTransId;
    private String messageVersion;
    private AcsChallengeMandated acsChallengeMandated;
    private String purchaseDate;
    private String base64EncodedChallengeRequest;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Data12() {
    }

    /**
     * Initialization constructor.
     * @param  threeDsServerTransId  String value for threeDsServerTransId.
     * @param  acsUrl  String value for acsUrl.
     * @param  transactionStatus  TransactionStatus value for transactionStatus.
     * @param  authenticationValue  String value for authenticationValue.
     * @param  eci  String value for eci.
     * @param  dsTransId  String value for dsTransId.
     * @param  acsTransId  String value for acsTransId.
     * @param  messageVersion  String value for messageVersion.
     * @param  acsChallengeMandated  AcsChallengeMandated value for acsChallengeMandated.
     * @param  purchaseDate  String value for purchaseDate.
     * @param  base64EncodedChallengeRequest  String value for base64EncodedChallengeRequest.
     */
    public Data12(
            String threeDsServerTransId,
            String acsUrl,
            TransactionStatus transactionStatus,
            String authenticationValue,
            String eci,
            String dsTransId,
            String acsTransId,
            String messageVersion,
            AcsChallengeMandated acsChallengeMandated,
            String purchaseDate,
            String base64EncodedChallengeRequest) {
        this.threeDsServerTransId = threeDsServerTransId;
        this.acsUrl = acsUrl;
        this.transactionStatus = transactionStatus;
        this.authenticationValue = authenticationValue;
        this.eci = eci;
        this.dsTransId = dsTransId;
        this.acsTransId = acsTransId;
        this.messageVersion = messageVersion;
        this.acsChallengeMandated = acsChallengeMandated;
        this.purchaseDate = purchaseDate;
        this.base64EncodedChallengeRequest = base64EncodedChallengeRequest;
    }

    /**
     * Getter for ThreeDsServerTransId.
     * Universally unique transaction identifier assigned by the 3DS Server to identify a single
     * transaction. It has the same value as the corresponding received authentication request. This
     * value has 36 characters in a format defined in IETF RFC 4122.
     * @return Returns the String
     */
    @JsonGetter("three_ds_server_trans_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getThreeDsServerTransId() {
        return threeDsServerTransId;
    }

    /**
     * Setter for ThreeDsServerTransId.
     * Universally unique transaction identifier assigned by the 3DS Server to identify a single
     * transaction. It has the same value as the corresponding received authentication request. This
     * value has 36 characters in a format defined in IETF RFC 4122.
     * @param threeDsServerTransId Value for String
     */
    @JsonSetter("three_ds_server_trans_id")
    public void setThreeDsServerTransId(String threeDsServerTransId) {
        this.threeDsServerTransId = threeDsServerTransId;
    }

    /**
     * Getter for AcsUrl.
     * Fully qualified URL of the ACS in case the authentication response message indicates that
     * further Cardholder interaction is required to complete the authentication. This field is only
     * present in Browser flow.
     * @return Returns the String
     */
    @JsonGetter("acs_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAcsUrl() {
        return acsUrl;
    }

    /**
     * Setter for AcsUrl.
     * Fully qualified URL of the ACS in case the authentication response message indicates that
     * further Cardholder interaction is required to complete the authentication. This field is only
     * present in Browser flow.
     * @param acsUrl Value for String
     */
    @JsonSetter("acs_url")
    public void setAcsUrl(String acsUrl) {
        this.acsUrl = acsUrl;
    }

    /**
     * Getter for TransactionStatus.
     * @return Returns the TransactionStatus
     */
    @JsonGetter("transaction_status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransactionStatus getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * Setter for TransactionStatus.
     * @param transactionStatus Value for TransactionStatus
     */
    @JsonSetter("transaction_status")
    public void setTransactionStatus(TransactionStatus transactionStatus) {
        this.transactionStatus = transactionStatus;
    }

    /**
     * Getter for AuthenticationValue.
     * Payment System-specific value provided as part of the ACS registration for each supported DS.
     * Authentication Value may be used to provide proof of authentication.
     * @return Returns the String
     */
    @JsonGetter("authentication_value")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAuthenticationValue() {
        return authenticationValue;
    }

    /**
     * Setter for AuthenticationValue.
     * Payment System-specific value provided as part of the ACS registration for each supported DS.
     * Authentication Value may be used to provide proof of authentication.
     * @param authenticationValue Value for String
     */
    @JsonSetter("authentication_value")
    public void setAuthenticationValue(String authenticationValue) {
        this.authenticationValue = authenticationValue;
    }

    /**
     * Getter for Eci.
     * Payment System-specific value provided by the ACS to indicate the results of the attempt to
     * authenticate the Cardholder.
     * @return Returns the String
     */
    @JsonGetter("eci")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEci() {
        return eci;
    }

    /**
     * Setter for Eci.
     * Payment System-specific value provided by the ACS to indicate the results of the attempt to
     * authenticate the Cardholder.
     * @param eci Value for String
     */
    @JsonSetter("eci")
    public void setEci(String eci) {
        this.eci = eci;
    }

    /**
     * Getter for DsTransId.
     * Universally unique transaction identifier assigned by the DS to identify a single
     * transaction.
     * @return Returns the String
     */
    @JsonGetter("ds_trans_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDsTransId() {
        return dsTransId;
    }

    /**
     * Setter for DsTransId.
     * Universally unique transaction identifier assigned by the DS to identify a single
     * transaction.
     * @param dsTransId Value for String
     */
    @JsonSetter("ds_trans_id")
    public void setDsTransId(String dsTransId) {
        this.dsTransId = dsTransId;
    }

    /**
     * Getter for AcsTransId.
     * Universally unique transaction identifier assigned by the ACS to identify a single
     * transaction.
     * @return Returns the String
     */
    @JsonGetter("acs_trans_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAcsTransId() {
        return acsTransId;
    }

    /**
     * Setter for AcsTransId.
     * Universally unique transaction identifier assigned by the ACS to identify a single
     * transaction.
     * @param acsTransId Value for String
     */
    @JsonSetter("acs_trans_id")
    public void setAcsTransId(String acsTransId) {
        this.acsTransId = acsTransId;
    }

    /**
     * Getter for MessageVersion.
     * Protocol version identifier This shall be the Protocol Version Number of the specification
     * utilised by the system creating this message. The Message Version Number is set by the 3DS
     * Server which originates the protocol with the AReq message. The Message Version Number does
     * not change during a 3DS transaction.
     * @return Returns the String
     */
    @JsonGetter("message_version")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMessageVersion() {
        return messageVersion;
    }

    /**
     * Setter for MessageVersion.
     * Protocol version identifier This shall be the Protocol Version Number of the specification
     * utilised by the system creating this message. The Message Version Number is set by the 3DS
     * Server which originates the protocol with the AReq message. The Message Version Number does
     * not change during a 3DS transaction.
     * @param messageVersion Value for String
     */
    @JsonSetter("message_version")
    public void setMessageVersion(String messageVersion) {
        this.messageVersion = messageVersion;
    }

    /**
     * Getter for AcsChallengeMandated.
     * @return Returns the AcsChallengeMandated
     */
    @JsonGetter("acs_challenge_mandated")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AcsChallengeMandated getAcsChallengeMandated() {
        return acsChallengeMandated;
    }

    /**
     * Setter for AcsChallengeMandated.
     * @param acsChallengeMandated Value for AcsChallengeMandated
     */
    @JsonSetter("acs_challenge_mandated")
    public void setAcsChallengeMandated(AcsChallengeMandated acsChallengeMandated) {
        this.acsChallengeMandated = acsChallengeMandated;
    }

    /**
     * Getter for PurchaseDate.
     * Date and time of the purchase, converted into UTC. The field is limited to 14 characters,
     * formatted as YYYYMMDDHHMMSS.
     * @return Returns the String
     */
    @JsonGetter("purchase_date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * Setter for PurchaseDate.
     * Date and time of the purchase, converted into UTC. The field is limited to 14 characters,
     * formatted as YYYYMMDDHHMMSS.
     * @param purchaseDate Value for String
     */
    @JsonSetter("purchase_date")
    public void setPurchaseDate(String purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * Getter for Base64EncodedChallengeRequest.
     * Base64-encoded Challenge Request object in case the authentication response message indicates
     * that further Cardholder interaction is required to complete the authentication.
     * @return Returns the String
     */
    @JsonGetter("base64_encoded_challenge_request")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBase64EncodedChallengeRequest() {
        return base64EncodedChallengeRequest;
    }

    /**
     * Setter for Base64EncodedChallengeRequest.
     * Base64-encoded Challenge Request object in case the authentication response message indicates
     * that further Cardholder interaction is required to complete the authentication.
     * @param base64EncodedChallengeRequest Value for String
     */
    @JsonSetter("base64_encoded_challenge_request")
    public void setBase64EncodedChallengeRequest(String base64EncodedChallengeRequest) {
        this.base64EncodedChallengeRequest = base64EncodedChallengeRequest;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Data12 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data12 [" + "threeDsServerTransId=" + threeDsServerTransId + ", acsUrl=" + acsUrl
                + ", transactionStatus=" + transactionStatus + ", authenticationValue="
                + authenticationValue + ", eci=" + eci + ", dsTransId=" + dsTransId
                + ", acsTransId=" + acsTransId + ", messageVersion=" + messageVersion
                + ", acsChallengeMandated=" + acsChallengeMandated + ", purchaseDate="
                + purchaseDate + ", base64EncodedChallengeRequest=" + base64EncodedChallengeRequest
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Data12.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data12.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .threeDsServerTransId(getThreeDsServerTransId())
                .acsUrl(getAcsUrl())
                .transactionStatus(getTransactionStatus())
                .authenticationValue(getAuthenticationValue())
                .eci(getEci())
                .dsTransId(getDsTransId())
                .acsTransId(getAcsTransId())
                .messageVersion(getMessageVersion())
                .acsChallengeMandated(getAcsChallengeMandated())
                .purchaseDate(getPurchaseDate())
                .base64EncodedChallengeRequest(getBase64EncodedChallengeRequest());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Data12}.
     */
    public static class Builder {
        private String threeDsServerTransId;
        private String acsUrl;
        private TransactionStatus transactionStatus;
        private String authenticationValue;
        private String eci;
        private String dsTransId;
        private String acsTransId;
        private String messageVersion;
        private AcsChallengeMandated acsChallengeMandated;
        private String purchaseDate;
        private String base64EncodedChallengeRequest;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for threeDsServerTransId.
         * @param  threeDsServerTransId  String value for threeDsServerTransId.
         * @return Builder
         */
        public Builder threeDsServerTransId(String threeDsServerTransId) {
            this.threeDsServerTransId = threeDsServerTransId;
            return this;
        }

        /**
         * Setter for acsUrl.
         * @param  acsUrl  String value for acsUrl.
         * @return Builder
         */
        public Builder acsUrl(String acsUrl) {
            this.acsUrl = acsUrl;
            return this;
        }

        /**
         * Setter for transactionStatus.
         * @param  transactionStatus  TransactionStatus value for transactionStatus.
         * @return Builder
         */
        public Builder transactionStatus(TransactionStatus transactionStatus) {
            this.transactionStatus = transactionStatus;
            return this;
        }

        /**
         * Setter for authenticationValue.
         * @param  authenticationValue  String value for authenticationValue.
         * @return Builder
         */
        public Builder authenticationValue(String authenticationValue) {
            this.authenticationValue = authenticationValue;
            return this;
        }

        /**
         * Setter for eci.
         * @param  eci  String value for eci.
         * @return Builder
         */
        public Builder eci(String eci) {
            this.eci = eci;
            return this;
        }

        /**
         * Setter for dsTransId.
         * @param  dsTransId  String value for dsTransId.
         * @return Builder
         */
        public Builder dsTransId(String dsTransId) {
            this.dsTransId = dsTransId;
            return this;
        }

        /**
         * Setter for acsTransId.
         * @param  acsTransId  String value for acsTransId.
         * @return Builder
         */
        public Builder acsTransId(String acsTransId) {
            this.acsTransId = acsTransId;
            return this;
        }

        /**
         * Setter for messageVersion.
         * @param  messageVersion  String value for messageVersion.
         * @return Builder
         */
        public Builder messageVersion(String messageVersion) {
            this.messageVersion = messageVersion;
            return this;
        }

        /**
         * Setter for acsChallengeMandated.
         * @param  acsChallengeMandated  AcsChallengeMandated value for acsChallengeMandated.
         * @return Builder
         */
        public Builder acsChallengeMandated(AcsChallengeMandated acsChallengeMandated) {
            this.acsChallengeMandated = acsChallengeMandated;
            return this;
        }

        /**
         * Setter for purchaseDate.
         * @param  purchaseDate  String value for purchaseDate.
         * @return Builder
         */
        public Builder purchaseDate(String purchaseDate) {
            this.purchaseDate = purchaseDate;
            return this;
        }

        /**
         * Setter for base64EncodedChallengeRequest.
         * @param  base64EncodedChallengeRequest  String value for base64EncodedChallengeRequest.
         * @return Builder
         */
        public Builder base64EncodedChallengeRequest(String base64EncodedChallengeRequest) {
            this.base64EncodedChallengeRequest = base64EncodedChallengeRequest;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Data12} object using the set fields.
         * @return {@link Data12}
         */
        public Data12 build() {
            Data12 model =
                    new Data12(threeDsServerTransId, acsUrl, transactionStatus, authenticationValue,
                            eci, dsTransId, acsTransId, messageVersion, acsChallengeMandated,
                            purchaseDate, base64EncodedChallengeRequest);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
