/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for EmvReceiptData type.
 */
public class EmvReceiptData {
    private OptionalNullable<String> aid;
    private OptionalNullable<String> applab;
    private OptionalNullable<String> appn;
    private OptionalNullable<String> cvm;
    private OptionalNullable<String> tsi;
    private OptionalNullable<String> tvr;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public EmvReceiptData() {
    }

    /**
     * Initialization constructor.
     * @param  aid  String value for aid.
     * @param  applab  String value for applab.
     * @param  appn  String value for appn.
     * @param  cvm  String value for cvm.
     * @param  tsi  String value for tsi.
     * @param  tvr  String value for tvr.
     */
    public EmvReceiptData(
            String aid,
            String applab,
            String appn,
            String cvm,
            String tsi,
            String tvr) {
        this.aid = OptionalNullable.of(aid);
        this.applab = OptionalNullable.of(applab);
        this.appn = OptionalNullable.of(appn);
        this.cvm = OptionalNullable.of(cvm);
        this.tsi = OptionalNullable.of(tsi);
        this.tvr = OptionalNullable.of(tvr);
    }

    /**
     * Initialization constructor.
     * @param  aid  String value for aid.
     * @param  applab  String value for applab.
     * @param  appn  String value for appn.
     * @param  cvm  String value for cvm.
     * @param  tsi  String value for tsi.
     * @param  tvr  String value for tvr.
     */

    protected EmvReceiptData(OptionalNullable<String> aid, OptionalNullable<String> applab,
            OptionalNullable<String> appn, OptionalNullable<String> cvm,
            OptionalNullable<String> tsi, OptionalNullable<String> tvr) {
        this.aid = aid;
        this.applab = applab;
        this.appn = appn;
        this.cvm = cvm;
        this.tsi = tsi;
        this.tvr = tvr;
    }

    /**
     * Internal Getter for Aid.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @return Returns the Internal String
     */
    @JsonGetter("AID")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetAid() {
        return this.aid;
    }

    /**
     * Getter for Aid.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @return Returns the String
     */
    public String getAid() {
        return OptionalNullable.getFrom(aid);
    }

    /**
     * Setter for Aid.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @param aid Value for String
     */
    @JsonSetter("AID")
    public void setAid(String aid) {
        this.aid = OptionalNullable.of(aid);
    }

    /**
     * UnSetter for Aid.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     */
    public void unsetAid() {
        aid = null;
    }

    /**
     * Internal Getter for Applab.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @return Returns the Internal String
     */
    @JsonGetter("APPLAB")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetApplab() {
        return this.applab;
    }

    /**
     * Getter for Applab.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @return Returns the String
     */
    public String getApplab() {
        return OptionalNullable.getFrom(applab);
    }

    /**
     * Setter for Applab.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @param applab Value for String
     */
    @JsonSetter("APPLAB")
    public void setApplab(String applab) {
        this.applab = OptionalNullable.of(applab);
    }

    /**
     * UnSetter for Applab.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     */
    public void unsetApplab() {
        applab = null;
    }

    /**
     * Internal Getter for Appn.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @return Returns the Internal String
     */
    @JsonGetter("APPN")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetAppn() {
        return this.appn;
    }

    /**
     * Getter for Appn.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @return Returns the String
     */
    public String getAppn() {
        return OptionalNullable.getFrom(appn);
    }

    /**
     * Setter for Appn.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @param appn Value for String
     */
    @JsonSetter("APPN")
    public void setAppn(String appn) {
        this.appn = OptionalNullable.of(appn);
    }

    /**
     * UnSetter for Appn.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     */
    public void unsetAppn() {
        appn = null;
    }

    /**
     * Internal Getter for Cvm.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @return Returns the Internal String
     */
    @JsonGetter("CVM")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetCvm() {
        return this.cvm;
    }

    /**
     * Getter for Cvm.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @return Returns the String
     */
    public String getCvm() {
        return OptionalNullable.getFrom(cvm);
    }

    /**
     * Setter for Cvm.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @param cvm Value for String
     */
    @JsonSetter("CVM")
    public void setCvm(String cvm) {
        this.cvm = OptionalNullable.of(cvm);
    }

    /**
     * UnSetter for Cvm.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     */
    public void unsetCvm() {
        cvm = null;
    }

    /**
     * Internal Getter for Tsi.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @return Returns the Internal String
     */
    @JsonGetter("TSI")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetTsi() {
        return this.tsi;
    }

    /**
     * Getter for Tsi.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @return Returns the String
     */
    public String getTsi() {
        return OptionalNullable.getFrom(tsi);
    }

    /**
     * Setter for Tsi.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @param tsi Value for String
     */
    @JsonSetter("TSI")
    public void setTsi(String tsi) {
        this.tsi = OptionalNullable.of(tsi);
    }

    /**
     * UnSetter for Tsi.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     */
    public void unsetTsi() {
        tsi = null;
    }

    /**
     * Internal Getter for Tvr.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @return Returns the Internal String
     */
    @JsonGetter("TVR")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetTvr() {
        return this.tvr;
    }

    /**
     * Getter for Tvr.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @return Returns the String
     */
    public String getTvr() {
        return OptionalNullable.getFrom(tvr);
    }

    /**
     * Setter for Tvr.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     * @param tvr Value for String
     */
    @JsonSetter("TVR")
    public void setTvr(String tvr) {
        this.tvr = OptionalNullable.of(tvr);
    }

    /**
     * UnSetter for Tvr.
     * This field is a read only field. This field will only be populated for EMV transactions and
     * will contain proper JSON formatted data with some or all of the following fields:
     * TC,TVR,AID,TSI,ATC,APPLAB,APPN,CVM
     */
    public void unsetTvr() {
        tvr = null;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this EmvReceiptData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EmvReceiptData [" + "aid=" + aid + ", applab=" + applab + ", appn=" + appn
                + ", cvm=" + cvm + ", tsi=" + tsi + ", tvr=" + tvr + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link EmvReceiptData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EmvReceiptData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.aid = internalGetAid();
        builder.applab = internalGetApplab();
        builder.appn = internalGetAppn();
        builder.cvm = internalGetCvm();
        builder.tsi = internalGetTsi();
        builder.tvr = internalGetTvr();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link EmvReceiptData}.
     */
    public static class Builder {
        private OptionalNullable<String> aid;
        private OptionalNullable<String> applab;
        private OptionalNullable<String> appn;
        private OptionalNullable<String> cvm;
        private OptionalNullable<String> tsi;
        private OptionalNullable<String> tvr;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for aid.
         * @param  aid  String value for aid.
         * @return Builder
         */
        public Builder aid(String aid) {
            this.aid = OptionalNullable.of(aid);
            return this;
        }

        /**
         * UnSetter for aid.
         * @return Builder
         */
        public Builder unsetAid() {
            aid = null;
            return this;
        }

        /**
         * Setter for applab.
         * @param  applab  String value for applab.
         * @return Builder
         */
        public Builder applab(String applab) {
            this.applab = OptionalNullable.of(applab);
            return this;
        }

        /**
         * UnSetter for applab.
         * @return Builder
         */
        public Builder unsetApplab() {
            applab = null;
            return this;
        }

        /**
         * Setter for appn.
         * @param  appn  String value for appn.
         * @return Builder
         */
        public Builder appn(String appn) {
            this.appn = OptionalNullable.of(appn);
            return this;
        }

        /**
         * UnSetter for appn.
         * @return Builder
         */
        public Builder unsetAppn() {
            appn = null;
            return this;
        }

        /**
         * Setter for cvm.
         * @param  cvm  String value for cvm.
         * @return Builder
         */
        public Builder cvm(String cvm) {
            this.cvm = OptionalNullable.of(cvm);
            return this;
        }

        /**
         * UnSetter for cvm.
         * @return Builder
         */
        public Builder unsetCvm() {
            cvm = null;
            return this;
        }

        /**
         * Setter for tsi.
         * @param  tsi  String value for tsi.
         * @return Builder
         */
        public Builder tsi(String tsi) {
            this.tsi = OptionalNullable.of(tsi);
            return this;
        }

        /**
         * UnSetter for tsi.
         * @return Builder
         */
        public Builder unsetTsi() {
            tsi = null;
            return this;
        }

        /**
         * Setter for tvr.
         * @param  tvr  String value for tvr.
         * @return Builder
         */
        public Builder tvr(String tvr) {
            this.tvr = OptionalNullable.of(tvr);
            return this;
        }

        /**
         * UnSetter for tvr.
         * @return Builder
         */
        public Builder unsetTvr() {
            tvr = null;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link EmvReceiptData} object using the set fields.
         * @return {@link EmvReceiptData}
         */
        public EmvReceiptData build() {
            EmvReceiptData model =
                    new EmvReceiptData(aid, applab, appn, cvm, tsi, tvr);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
