/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Expand57Enum to be used.
 */
public enum Expand57Enum {
    REJECTED_TRANSACTION,

    RETRY_TRANSACTION,

    RETURN_FEE_TRANSACTION,

    CREATED_USER,

    CHANGELOGS;


    private static TreeMap<String, Expand57Enum> valueMap = new TreeMap<>();
    private String value;

    static {
        REJECTED_TRANSACTION.value = "rejected_transaction";
        RETRY_TRANSACTION.value = "retry_transaction";
        RETURN_FEE_TRANSACTION.value = "return_fee_transaction";
        CREATED_USER.value = "created_user";
        CHANGELOGS.value = "changelogs";

        valueMap.put("rejected_transaction", REJECTED_TRANSACTION);
        valueMap.put("retry_transaction", RETRY_TRANSACTION);
        valueMap.put("return_fee_transaction", RETURN_FEE_TRANSACTION);
        valueMap.put("created_user", CREATED_USER);
        valueMap.put("changelogs", CHANGELOGS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Expand57Enum constructFromString(String toConvert) throws IOException {
        Expand57Enum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Expand57Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Expand57Enum values to list of string values.
     * @param toConvert The list of Expand57Enum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Expand57Enum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Expand57Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 