/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Expand123 to be used.
 */
public enum Expand123 {
    POSTBACKLOGS,

    BASIC_AUTH_USERNAME,

    BASIC_AUTH_PASSWORD,

    /**
     * Unknown values will be mapped by this enum member
     */
    _UNKNOWN;


    private static TreeMap<String, Expand123> valueMap = new TreeMap<>();
    private String value;

    static {
        POSTBACKLOGS.value = "postbacklogs";
        BASIC_AUTH_USERNAME.value = "basic_auth_username";
        BASIC_AUTH_PASSWORD.value = "basic_auth_password";
        _UNKNOWN.value = null;

        valueMap.put("postbacklogs", POSTBACKLOGS);
        valueMap.put("basic_auth_username", BASIC_AUTH_USERNAME);
        valueMap.put("basic_auth_password", BASIC_AUTH_PASSWORD);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Expand123 constructFromString(String toConvert) throws IOException {
        Expand123 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Expand123 fromString(String toConvert) {
        if (!valueMap.containsKey(toConvert)) {
            return _UNKNOWN;
        }
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        if (value == null) {
            return null;
        }
        return value.toString();
    }

    /**
     * Convert list of Expand123 values to list of string values.
     * @param toConvert The list of Expand123 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Expand123> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Expand123 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 