/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Expand1Enum to be used.
 */
public enum Expand1Enum {
    RECEIVED_EMAILS,

    IS_DELETABLE,

    LOCATION,

    USER,

    RECURRINGS,

    EMAIL_BLACKLIST,

    SMS_BLACKLIST,

    CHANGELOGS,

    POSTBACK_LOGS,

    CREATED_USER,

    PARENT,

    CHILDREN;


    private static TreeMap<String, Expand1Enum> valueMap = new TreeMap<>();
    private String value;

    static {
        RECEIVED_EMAILS.value = "received_emails";
        IS_DELETABLE.value = "is_deletable";
        LOCATION.value = "location";
        USER.value = "user";
        RECURRINGS.value = "recurrings";
        EMAIL_BLACKLIST.value = "email_blacklist";
        SMS_BLACKLIST.value = "sms_blacklist";
        CHANGELOGS.value = "changelogs";
        POSTBACK_LOGS.value = "postback_logs";
        CREATED_USER.value = "created_user";
        PARENT.value = "parent";
        CHILDREN.value = "children";

        valueMap.put("received_emails", RECEIVED_EMAILS);
        valueMap.put("is_deletable", IS_DELETABLE);
        valueMap.put("location", LOCATION);
        valueMap.put("user", USER);
        valueMap.put("recurrings", RECURRINGS);
        valueMap.put("email_blacklist", EMAIL_BLACKLIST);
        valueMap.put("sms_blacklist", SMS_BLACKLIST);
        valueMap.put("changelogs", CHANGELOGS);
        valueMap.put("postback_logs", POSTBACK_LOGS);
        valueMap.put("created_user", CREATED_USER);
        valueMap.put("parent", PARENT);
        valueMap.put("children", CHILDREN);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Expand1Enum constructFromString(String toConvert) throws IOException {
        Expand1Enum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Expand1Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Expand1Enum values to list of string values.
     * @param toConvert The list of Expand1Enum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Expand1Enum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Expand1Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 