/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Field60Enum to be used.
 */
public enum Field60Enum {
    ACCOUNT_NUMBER,

    BRANDING_DOMAIN_URL,

    CELL_PHONE,

    COMPANY_NAME,

    CONTACT_ID,

    DATE_OF_BIRTH,

    DOMAIN_ID,

    EMAIL,

    EMAIL_TRX_RECEIPT,

    HOME_PHONE,

    FIRST_NAME,

    LAST_NAME,

    LOCALE,

    OFFICE_PHONE,

    OFFICE_EXT_PHONE,

    PRIMARY_LOCATION_ID,

    REQUIRES_NEW_PASSWORD,

    TERMS_CONDITION_CODE,

    TZ,

    UI_PREFS,

    USERNAME,

    USER_API_KEY,

    USER_HASH_KEY,

    USER_TYPE_CODE,

    PASSWORD,

    ZIP,

    LOCATION_ID,

    CONTACT_API_ID,

    PRIMARY_LOCATION_API_ID,

    STATUS_CODE,

    API_ONLY,

    IS_INVITATION,

    ADDRESS,

    ID,

    STATUS,

    LOGIN_ATTEMPTS,

    LAST_LOGIN_TS,

    CREATED_TS,

    MODIFIED_TS,

    CREATED_USER_ID,

    TERMS_ACCEPTED_TS,

    TERMS_AGREE_IP,

    CURRENT_DATE_TIME,

    CURRENT_LOGIN_IP,

    CURRENT_LOGIN,

    SFTP_ACCESS,

    LOG_API_RESPONSE_BODY_TS,

    LOCATIONS,

    PRIMARY_LOCATION,

    RECEIVED_EMAILS,

    CONTACT,

    ISDELETABLE,

    ACTIVE_NOTIFICATION_ALERTS,

    LOCATION_USERS,

    AUTH_ROLES,

    CHANGELOGS,

    RESOURCES,

    DOMAIN,

    CREATED_USER,

    LOCATION_MARKETPLACES,

    EMAIL_BLACKLIST,

    HELPPAGE,

    FEATURE_FLAGS;


    private static TreeMap<String, Field60Enum> valueMap = new TreeMap<>();
    private String value;

    static {
        ACCOUNT_NUMBER.value = "account_number";
        BRANDING_DOMAIN_URL.value = "branding_domain_url";
        CELL_PHONE.value = "cell_phone";
        COMPANY_NAME.value = "company_name";
        CONTACT_ID.value = "contact_id";
        DATE_OF_BIRTH.value = "date_of_birth";
        DOMAIN_ID.value = "domain_id";
        EMAIL.value = "email";
        EMAIL_TRX_RECEIPT.value = "email_trx_receipt";
        HOME_PHONE.value = "home_phone";
        FIRST_NAME.value = "first_name";
        LAST_NAME.value = "last_name";
        LOCALE.value = "locale";
        OFFICE_PHONE.value = "office_phone";
        OFFICE_EXT_PHONE.value = "office_ext_phone";
        PRIMARY_LOCATION_ID.value = "primary_location_id";
        REQUIRES_NEW_PASSWORD.value = "requires_new_password";
        TERMS_CONDITION_CODE.value = "terms_condition_code";
        TZ.value = "tz";
        UI_PREFS.value = "ui_prefs";
        USERNAME.value = "username";
        USER_API_KEY.value = "user_api_key";
        USER_HASH_KEY.value = "user_hash_key";
        USER_TYPE_CODE.value = "user_type_code";
        PASSWORD.value = "password";
        ZIP.value = "zip";
        LOCATION_ID.value = "location_id";
        CONTACT_API_ID.value = "contact_api_id";
        PRIMARY_LOCATION_API_ID.value = "primary_location_api_id";
        STATUS_CODE.value = "status_code";
        API_ONLY.value = "api_only";
        IS_INVITATION.value = "is_invitation";
        ADDRESS.value = "address";
        ID.value = "id";
        STATUS.value = "status";
        LOGIN_ATTEMPTS.value = "login_attempts";
        LAST_LOGIN_TS.value = "last_login_ts";
        CREATED_TS.value = "created_ts";
        MODIFIED_TS.value = "modified_ts";
        CREATED_USER_ID.value = "created_user_id";
        TERMS_ACCEPTED_TS.value = "terms_accepted_ts";
        TERMS_AGREE_IP.value = "terms_agree_ip";
        CURRENT_DATE_TIME.value = "current_date_time";
        CURRENT_LOGIN_IP.value = "current_login_ip";
        CURRENT_LOGIN.value = "current_login";
        SFTP_ACCESS.value = "sftp_access";
        LOG_API_RESPONSE_BODY_TS.value = "log_api_response_body_ts";
        LOCATIONS.value = "locations";
        PRIMARY_LOCATION.value = "primary_location";
        RECEIVED_EMAILS.value = "received_emails";
        CONTACT.value = "contact";
        ISDELETABLE.value = "isDeletable";
        ACTIVE_NOTIFICATION_ALERTS.value = "active_notification_alerts";
        LOCATION_USERS.value = "location_users";
        AUTH_ROLES.value = "auth_roles";
        CHANGELOGS.value = "changelogs";
        RESOURCES.value = "resources";
        DOMAIN.value = "domain";
        CREATED_USER.value = "created_user";
        LOCATION_MARKETPLACES.value = "location_marketplaces";
        EMAIL_BLACKLIST.value = "email_blacklist";
        HELPPAGE.value = "helppage";
        FEATURE_FLAGS.value = "feature_flags";

        valueMap.put("account_number", ACCOUNT_NUMBER);
        valueMap.put("branding_domain_url", BRANDING_DOMAIN_URL);
        valueMap.put("cell_phone", CELL_PHONE);
        valueMap.put("company_name", COMPANY_NAME);
        valueMap.put("contact_id", CONTACT_ID);
        valueMap.put("date_of_birth", DATE_OF_BIRTH);
        valueMap.put("domain_id", DOMAIN_ID);
        valueMap.put("email", EMAIL);
        valueMap.put("email_trx_receipt", EMAIL_TRX_RECEIPT);
        valueMap.put("home_phone", HOME_PHONE);
        valueMap.put("first_name", FIRST_NAME);
        valueMap.put("last_name", LAST_NAME);
        valueMap.put("locale", LOCALE);
        valueMap.put("office_phone", OFFICE_PHONE);
        valueMap.put("office_ext_phone", OFFICE_EXT_PHONE);
        valueMap.put("primary_location_id", PRIMARY_LOCATION_ID);
        valueMap.put("requires_new_password", REQUIRES_NEW_PASSWORD);
        valueMap.put("terms_condition_code", TERMS_CONDITION_CODE);
        valueMap.put("tz", TZ);
        valueMap.put("ui_prefs", UI_PREFS);
        valueMap.put("username", USERNAME);
        valueMap.put("user_api_key", USER_API_KEY);
        valueMap.put("user_hash_key", USER_HASH_KEY);
        valueMap.put("user_type_code", USER_TYPE_CODE);
        valueMap.put("password", PASSWORD);
        valueMap.put("zip", ZIP);
        valueMap.put("location_id", LOCATION_ID);
        valueMap.put("contact_api_id", CONTACT_API_ID);
        valueMap.put("primary_location_api_id", PRIMARY_LOCATION_API_ID);
        valueMap.put("status_code", STATUS_CODE);
        valueMap.put("api_only", API_ONLY);
        valueMap.put("is_invitation", IS_INVITATION);
        valueMap.put("address", ADDRESS);
        valueMap.put("id", ID);
        valueMap.put("status", STATUS);
        valueMap.put("login_attempts", LOGIN_ATTEMPTS);
        valueMap.put("last_login_ts", LAST_LOGIN_TS);
        valueMap.put("created_ts", CREATED_TS);
        valueMap.put("modified_ts", MODIFIED_TS);
        valueMap.put("created_user_id", CREATED_USER_ID);
        valueMap.put("terms_accepted_ts", TERMS_ACCEPTED_TS);
        valueMap.put("terms_agree_ip", TERMS_AGREE_IP);
        valueMap.put("current_date_time", CURRENT_DATE_TIME);
        valueMap.put("current_login_ip", CURRENT_LOGIN_IP);
        valueMap.put("current_login", CURRENT_LOGIN);
        valueMap.put("sftp_access", SFTP_ACCESS);
        valueMap.put("log_api_response_body_ts", LOG_API_RESPONSE_BODY_TS);
        valueMap.put("locations", LOCATIONS);
        valueMap.put("primary_location", PRIMARY_LOCATION);
        valueMap.put("received_emails", RECEIVED_EMAILS);
        valueMap.put("contact", CONTACT);
        valueMap.put("isDeletable", ISDELETABLE);
        valueMap.put("active_notification_alerts", ACTIVE_NOTIFICATION_ALERTS);
        valueMap.put("location_users", LOCATION_USERS);
        valueMap.put("auth_roles", AUTH_ROLES);
        valueMap.put("changelogs", CHANGELOGS);
        valueMap.put("resources", RESOURCES);
        valueMap.put("domain", DOMAIN);
        valueMap.put("created_user", CREATED_USER);
        valueMap.put("location_marketplaces", LOCATION_MARKETPLACES);
        valueMap.put("email_blacklist", EMAIL_BLACKLIST);
        valueMap.put("helppage", HELPPAGE);
        valueMap.put("feature_flags", FEATURE_FLAGS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Field60Enum constructFromString(String toConvert) throws IOException {
        Field60Enum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Field60Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Field60Enum values to list of string values.
     * @param toConvert The list of Field60Enum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Field60Enum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Field60Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 