/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Field57 to be used.
 */
public enum Field57 {
    ADDITIONAL_AMOUNTS,

    BILLING_ADDRESS,

    CHECKIN_DATE,

    CHECKOUT_DATE,

    CLERK_NUMBER,

    CONTACT_API_ID,

    CONTACT_ID,

    CUSTOM_DATA,

    CUSTOMER_ID,

    DESCRIPTION,

    IIAS_IND,

    IMAGE_FRONT,

    IMAGE_BACK,

    INSTALLMENT,

    INSTALLMENT_NUMBER,

    INSTALLMENT_COUNT,

    RECURRING_FLAG,

    INSTALLMENT_COUNTER,

    INSTALLMENT_TOTAL,

    SUBSCRIPTION,

    STANDING_ORDER,

    LOCATION_API_ID,

    LOCATION_ID,

    PRODUCT_TRANSACTION_ID,

    ADVANCE_DEPOSIT,

    NO_SHOW,

    NOTIFICATION_EMAIL_ADDRESS,

    ORDER_NUMBER,

    PO_NUMBER,

    QUICK_INVOICE_ID,

    RECURRING,

    RECURRING_NUMBER,

    ROOM_NUM,

    ROOM_RATE,

    SAVE_ACCOUNT,

    SAVE_ACCOUNT_TITLE,

    SUBTOTAL_AMOUNT,

    SURCHARGE_AMOUNT,

    TAGS,

    TAX,

    TIP_AMOUNT,

    TRANSACTION_AMOUNT,

    SECONDARY_AMOUNT,

    TRANSACTION_API_ID,

    TRANSACTION_C1,

    TRANSACTION_C2,

    TRANSACTION_C3,

    BANK_FUNDED_ONLY_OVERRIDE,

    ALLOW_PARTIAL_AUTHORIZATION_OVERRIDE,

    AUTO_DECLINE_CVV_OVERRIDE,

    AUTO_DECLINE_STREET_OVERRIDE,

    AUTO_DECLINE_ZIP_OVERRIDE,

    EBT_TYPE,

    ID,

    CREATED_TS,

    MODIFIED_TS,

    TERMINAL_ID,

    ACCOUNT_HOLDER_NAME,

    ACCOUNT_TYPE,

    TOKEN_API_ID,

    TOKEN_ID,

    ACH_IDENTIFIER,

    ACH_SEC_CODE,

    AUTH_AMOUNT,

    AUTH_CODE,

    AVS,

    AVS_ENHANCED,

    CARDHOLDER_PRESENT,

    CARD_PRESENT,

    CHECK_NUMBER,

    CUSTOMER_IP,

    CVV_RESPONSE,

    ENTRY_MODE_ID,

    EMV_RECEIPT_DATA,

    FIRST_SIX,

    LAST_FOUR,

    PAYMENT_METHOD,

    TERMINAL_SERIAL_NUMBER,

    TRANSACTION_SETTLEMENT_STATUS,

    CHARGE_BACK_DATE,

    IS_RECURRING,

    NOTIFICATION_EMAIL_SENT,

    PAR,

    REASON_CODE_ID,

    RECURRING_ID,

    SETTLE_DATE,

    STATUS_CODE,

    TRANSACTION_BATCH_ID,

    TYPE_ID,

    VERBIAGE,

    VOUCHER_NUMBER,

    VOID_DATE,

    BATCH,

    TERMS_AGREE,

    RESPONSE_MESSAGE,

    RETURN_DATE,

    TRX_SOURCE_ID,

    ROUTING_NUMBER,

    TRX_SOURCE_CODE,

    PAYLINK_ID,

    CURRENCY_CODE,

    IS_ACCOUNTVAULT,

    CREATED_USER_ID,

    MODIFIED_USER_ID,

    TRANSACTION_CODE,

    EFFECTIVE_DATE,

    NOTIFICATION_PHONE,

    CAVV_RESULT,

    IS_TOKEN,

    ACCOUNT_VAULT_ID,

    HOSTED_PAYMENT_PAGE_ID,

    STAN,

    CURRENCY,

    CARD_BIN,

    WALLET_TYPE,

    ACCOUNT_VAULT,

    QUICK_INVOICE,

    LOG_EMAILS,

    IS_VOIDABLE,

    IS_REVERSIBLE,

    IS_REFUNDABLE,

    IS_COMPLETABLE,

    IS_SETTLED,

    CREATED_USER,

    LOCATION,

    CONTACT,

    CHANGELOGS,

    PRODUCT_TRANSACTION,

    ALL_TAGS,

    TAGTRANSACTIONS,

    DECLINED_RECURRING_NOTIFICATION,

    PAYMENT_RECURRING_NOTIFICATION,

    DEVELOPER_COMPANY,

    TERMINAL,

    HOSTED_PAYMENT_PAGE,

    TRANSACTION_LEVEL3,

    DEVELOPER_COMPANY_ID,

    TRANSACTION_HISTORIES,

    SURCHARGE_TRANSACTION,

    SURCHARGE,

    SIGNATURE,

    REASON_CODE,

    TYPE,

    STATUS,

    TRANSACTION_BATCH,

    TRANSACTION_SPLITS,

    POSTBACK_LOGS,

    CURRENCY_TYPE,

    TRANSACTION_REFERENCES,

    REJECTED_TRANSACTION_ACH_RETRIES,

    RETURN_FEE_TRANSACTION_ACH_RETRY,

    RETRY_TRANSACTION_ACH_RETRY,

    IS_RETRIABLE,

    SAVED_ACCOUNT,

    BALANCES,

    TRANSACTION_THREE_DS,

    /**
     * Unknown values will be mapped by this enum member
     */
    _UNKNOWN;


    private static TreeMap<String, Field57> valueMap = new TreeMap<>();
    private String value;

    static {
        ADDITIONAL_AMOUNTS.value = "additional_amounts";
        BILLING_ADDRESS.value = "billing_address";
        CHECKIN_DATE.value = "checkin_date";
        CHECKOUT_DATE.value = "checkout_date";
        CLERK_NUMBER.value = "clerk_number";
        CONTACT_API_ID.value = "contact_api_id";
        CONTACT_ID.value = "contact_id";
        CUSTOM_DATA.value = "custom_data";
        CUSTOMER_ID.value = "customer_id";
        DESCRIPTION.value = "description";
        IIAS_IND.value = "iias_ind";
        IMAGE_FRONT.value = "image_front";
        IMAGE_BACK.value = "image_back";
        INSTALLMENT.value = "installment";
        INSTALLMENT_NUMBER.value = "installment_number";
        INSTALLMENT_COUNT.value = "installment_count";
        RECURRING_FLAG.value = "recurring_flag";
        INSTALLMENT_COUNTER.value = "installment_counter";
        INSTALLMENT_TOTAL.value = "installment_total";
        SUBSCRIPTION.value = "subscription";
        STANDING_ORDER.value = "standing_order";
        LOCATION_API_ID.value = "location_api_id";
        LOCATION_ID.value = "location_id";
        PRODUCT_TRANSACTION_ID.value = "product_transaction_id";
        ADVANCE_DEPOSIT.value = "advance_deposit";
        NO_SHOW.value = "no_show";
        NOTIFICATION_EMAIL_ADDRESS.value = "notification_email_address";
        ORDER_NUMBER.value = "order_number";
        PO_NUMBER.value = "po_number";
        QUICK_INVOICE_ID.value = "quick_invoice_id";
        RECURRING.value = "recurring";
        RECURRING_NUMBER.value = "recurring_number";
        ROOM_NUM.value = "room_num";
        ROOM_RATE.value = "room_rate";
        SAVE_ACCOUNT.value = "save_account";
        SAVE_ACCOUNT_TITLE.value = "save_account_title";
        SUBTOTAL_AMOUNT.value = "subtotal_amount";
        SURCHARGE_AMOUNT.value = "surcharge_amount";
        TAGS.value = "tags";
        TAX.value = "tax";
        TIP_AMOUNT.value = "tip_amount";
        TRANSACTION_AMOUNT.value = "transaction_amount";
        SECONDARY_AMOUNT.value = "secondary_amount";
        TRANSACTION_API_ID.value = "transaction_api_id";
        TRANSACTION_C1.value = "transaction_c1";
        TRANSACTION_C2.value = "transaction_c2";
        TRANSACTION_C3.value = "transaction_c3";
        BANK_FUNDED_ONLY_OVERRIDE.value = "bank_funded_only_override";
        ALLOW_PARTIAL_AUTHORIZATION_OVERRIDE.value = "allow_partial_authorization_override";
        AUTO_DECLINE_CVV_OVERRIDE.value = "auto_decline_cvv_override";
        AUTO_DECLINE_STREET_OVERRIDE.value = "auto_decline_street_override";
        AUTO_DECLINE_ZIP_OVERRIDE.value = "auto_decline_zip_override";
        EBT_TYPE.value = "ebt_type";
        ID.value = "id";
        CREATED_TS.value = "created_ts";
        MODIFIED_TS.value = "modified_ts";
        TERMINAL_ID.value = "terminal_id";
        ACCOUNT_HOLDER_NAME.value = "account_holder_name";
        ACCOUNT_TYPE.value = "account_type";
        TOKEN_API_ID.value = "token_api_id";
        TOKEN_ID.value = "token_id";
        ACH_IDENTIFIER.value = "ach_identifier";
        ACH_SEC_CODE.value = "ach_sec_code";
        AUTH_AMOUNT.value = "auth_amount";
        AUTH_CODE.value = "auth_code";
        AVS.value = "avs";
        AVS_ENHANCED.value = "avs_enhanced";
        CARDHOLDER_PRESENT.value = "cardholder_present";
        CARD_PRESENT.value = "card_present";
        CHECK_NUMBER.value = "check_number";
        CUSTOMER_IP.value = "customer_ip";
        CVV_RESPONSE.value = "cvv_response";
        ENTRY_MODE_ID.value = "entry_mode_id";
        EMV_RECEIPT_DATA.value = "emv_receipt_data";
        FIRST_SIX.value = "first_six";
        LAST_FOUR.value = "last_four";
        PAYMENT_METHOD.value = "payment_method";
        TERMINAL_SERIAL_NUMBER.value = "terminal_serial_number";
        TRANSACTION_SETTLEMENT_STATUS.value = "transaction_settlement_status";
        CHARGE_BACK_DATE.value = "charge_back_date";
        IS_RECURRING.value = "is_recurring";
        NOTIFICATION_EMAIL_SENT.value = "notification_email_sent";
        PAR.value = "par";
        REASON_CODE_ID.value = "reason_code_id";
        RECURRING_ID.value = "recurring_id";
        SETTLE_DATE.value = "settle_date";
        STATUS_CODE.value = "status_code";
        TRANSACTION_BATCH_ID.value = "transaction_batch_id";
        TYPE_ID.value = "type_id";
        VERBIAGE.value = "verbiage";
        VOUCHER_NUMBER.value = "voucher_number";
        VOID_DATE.value = "void_date";
        BATCH.value = "batch";
        TERMS_AGREE.value = "terms_agree";
        RESPONSE_MESSAGE.value = "response_message";
        RETURN_DATE.value = "return_date";
        TRX_SOURCE_ID.value = "trx_source_id";
        ROUTING_NUMBER.value = "routing_number";
        TRX_SOURCE_CODE.value = "trx_source_code";
        PAYLINK_ID.value = "paylink_id";
        CURRENCY_CODE.value = "currency_code";
        IS_ACCOUNTVAULT.value = "is_accountvault";
        CREATED_USER_ID.value = "created_user_id";
        MODIFIED_USER_ID.value = "modified_user_id";
        TRANSACTION_CODE.value = "transaction_code";
        EFFECTIVE_DATE.value = "effective_date";
        NOTIFICATION_PHONE.value = "notification_phone";
        CAVV_RESULT.value = "cavv_result";
        IS_TOKEN.value = "is_token";
        ACCOUNT_VAULT_ID.value = "account_vault_id";
        HOSTED_PAYMENT_PAGE_ID.value = "hosted_payment_page_id";
        STAN.value = "stan";
        CURRENCY.value = "currency";
        CARD_BIN.value = "card_bin";
        WALLET_TYPE.value = "wallet_type";
        ACCOUNT_VAULT.value = "account_vault";
        QUICK_INVOICE.value = "quick_invoice";
        LOG_EMAILS.value = "log_emails";
        IS_VOIDABLE.value = "is_voidable";
        IS_REVERSIBLE.value = "is_reversible";
        IS_REFUNDABLE.value = "is_refundable";
        IS_COMPLETABLE.value = "is_completable";
        IS_SETTLED.value = "is_settled";
        CREATED_USER.value = "created_user";
        LOCATION.value = "location";
        CONTACT.value = "contact";
        CHANGELOGS.value = "changelogs";
        PRODUCT_TRANSACTION.value = "product_transaction";
        ALL_TAGS.value = "all_tags";
        TAGTRANSACTIONS.value = "tagTransactions";
        DECLINED_RECURRING_NOTIFICATION.value = "declined_recurring_notification";
        PAYMENT_RECURRING_NOTIFICATION.value = "payment_recurring_notification";
        DEVELOPER_COMPANY.value = "developer_company";
        TERMINAL.value = "terminal";
        HOSTED_PAYMENT_PAGE.value = "hosted_payment_page";
        TRANSACTION_LEVEL3.value = "transaction_level3";
        DEVELOPER_COMPANY_ID.value = "developer_company_id";
        TRANSACTION_HISTORIES.value = "transaction_histories";
        SURCHARGE_TRANSACTION.value = "surcharge_transaction";
        SURCHARGE.value = "surcharge";
        SIGNATURE.value = "signature";
        REASON_CODE.value = "reason_code";
        TYPE.value = "type";
        STATUS.value = "status";
        TRANSACTION_BATCH.value = "transaction_batch";
        TRANSACTION_SPLITS.value = "transaction_splits";
        POSTBACK_LOGS.value = "postback_logs";
        CURRENCY_TYPE.value = "currency_type";
        TRANSACTION_REFERENCES.value = "transaction_references";
        REJECTED_TRANSACTION_ACH_RETRIES.value = "rejected_transaction_ach_retries";
        RETURN_FEE_TRANSACTION_ACH_RETRY.value = "return_fee_transaction_ach_retry";
        RETRY_TRANSACTION_ACH_RETRY.value = "retry_transaction_ach_retry";
        IS_RETRIABLE.value = "is_retriable";
        SAVED_ACCOUNT.value = "saved_account";
        BALANCES.value = "balances";
        TRANSACTION_THREE_DS.value = "transaction_three_ds";
        _UNKNOWN.value = null;

        valueMap.put("additional_amounts", ADDITIONAL_AMOUNTS);
        valueMap.put("billing_address", BILLING_ADDRESS);
        valueMap.put("checkin_date", CHECKIN_DATE);
        valueMap.put("checkout_date", CHECKOUT_DATE);
        valueMap.put("clerk_number", CLERK_NUMBER);
        valueMap.put("contact_api_id", CONTACT_API_ID);
        valueMap.put("contact_id", CONTACT_ID);
        valueMap.put("custom_data", CUSTOM_DATA);
        valueMap.put("customer_id", CUSTOMER_ID);
        valueMap.put("description", DESCRIPTION);
        valueMap.put("iias_ind", IIAS_IND);
        valueMap.put("image_front", IMAGE_FRONT);
        valueMap.put("image_back", IMAGE_BACK);
        valueMap.put("installment", INSTALLMENT);
        valueMap.put("installment_number", INSTALLMENT_NUMBER);
        valueMap.put("installment_count", INSTALLMENT_COUNT);
        valueMap.put("recurring_flag", RECURRING_FLAG);
        valueMap.put("installment_counter", INSTALLMENT_COUNTER);
        valueMap.put("installment_total", INSTALLMENT_TOTAL);
        valueMap.put("subscription", SUBSCRIPTION);
        valueMap.put("standing_order", STANDING_ORDER);
        valueMap.put("location_api_id", LOCATION_API_ID);
        valueMap.put("location_id", LOCATION_ID);
        valueMap.put("product_transaction_id", PRODUCT_TRANSACTION_ID);
        valueMap.put("advance_deposit", ADVANCE_DEPOSIT);
        valueMap.put("no_show", NO_SHOW);
        valueMap.put("notification_email_address", NOTIFICATION_EMAIL_ADDRESS);
        valueMap.put("order_number", ORDER_NUMBER);
        valueMap.put("po_number", PO_NUMBER);
        valueMap.put("quick_invoice_id", QUICK_INVOICE_ID);
        valueMap.put("recurring", RECURRING);
        valueMap.put("recurring_number", RECURRING_NUMBER);
        valueMap.put("room_num", ROOM_NUM);
        valueMap.put("room_rate", ROOM_RATE);
        valueMap.put("save_account", SAVE_ACCOUNT);
        valueMap.put("save_account_title", SAVE_ACCOUNT_TITLE);
        valueMap.put("subtotal_amount", SUBTOTAL_AMOUNT);
        valueMap.put("surcharge_amount", SURCHARGE_AMOUNT);
        valueMap.put("tags", TAGS);
        valueMap.put("tax", TAX);
        valueMap.put("tip_amount", TIP_AMOUNT);
        valueMap.put("transaction_amount", TRANSACTION_AMOUNT);
        valueMap.put("secondary_amount", SECONDARY_AMOUNT);
        valueMap.put("transaction_api_id", TRANSACTION_API_ID);
        valueMap.put("transaction_c1", TRANSACTION_C1);
        valueMap.put("transaction_c2", TRANSACTION_C2);
        valueMap.put("transaction_c3", TRANSACTION_C3);
        valueMap.put("bank_funded_only_override", BANK_FUNDED_ONLY_OVERRIDE);
        valueMap.put("allow_partial_authorization_override", ALLOW_PARTIAL_AUTHORIZATION_OVERRIDE);
        valueMap.put("auto_decline_cvv_override", AUTO_DECLINE_CVV_OVERRIDE);
        valueMap.put("auto_decline_street_override", AUTO_DECLINE_STREET_OVERRIDE);
        valueMap.put("auto_decline_zip_override", AUTO_DECLINE_ZIP_OVERRIDE);
        valueMap.put("ebt_type", EBT_TYPE);
        valueMap.put("id", ID);
        valueMap.put("created_ts", CREATED_TS);
        valueMap.put("modified_ts", MODIFIED_TS);
        valueMap.put("terminal_id", TERMINAL_ID);
        valueMap.put("account_holder_name", ACCOUNT_HOLDER_NAME);
        valueMap.put("account_type", ACCOUNT_TYPE);
        valueMap.put("token_api_id", TOKEN_API_ID);
        valueMap.put("token_id", TOKEN_ID);
        valueMap.put("ach_identifier", ACH_IDENTIFIER);
        valueMap.put("ach_sec_code", ACH_SEC_CODE);
        valueMap.put("auth_amount", AUTH_AMOUNT);
        valueMap.put("auth_code", AUTH_CODE);
        valueMap.put("avs", AVS);
        valueMap.put("avs_enhanced", AVS_ENHANCED);
        valueMap.put("cardholder_present", CARDHOLDER_PRESENT);
        valueMap.put("card_present", CARD_PRESENT);
        valueMap.put("check_number", CHECK_NUMBER);
        valueMap.put("customer_ip", CUSTOMER_IP);
        valueMap.put("cvv_response", CVV_RESPONSE);
        valueMap.put("entry_mode_id", ENTRY_MODE_ID);
        valueMap.put("emv_receipt_data", EMV_RECEIPT_DATA);
        valueMap.put("first_six", FIRST_SIX);
        valueMap.put("last_four", LAST_FOUR);
        valueMap.put("payment_method", PAYMENT_METHOD);
        valueMap.put("terminal_serial_number", TERMINAL_SERIAL_NUMBER);
        valueMap.put("transaction_settlement_status", TRANSACTION_SETTLEMENT_STATUS);
        valueMap.put("charge_back_date", CHARGE_BACK_DATE);
        valueMap.put("is_recurring", IS_RECURRING);
        valueMap.put("notification_email_sent", NOTIFICATION_EMAIL_SENT);
        valueMap.put("par", PAR);
        valueMap.put("reason_code_id", REASON_CODE_ID);
        valueMap.put("recurring_id", RECURRING_ID);
        valueMap.put("settle_date", SETTLE_DATE);
        valueMap.put("status_code", STATUS_CODE);
        valueMap.put("transaction_batch_id", TRANSACTION_BATCH_ID);
        valueMap.put("type_id", TYPE_ID);
        valueMap.put("verbiage", VERBIAGE);
        valueMap.put("voucher_number", VOUCHER_NUMBER);
        valueMap.put("void_date", VOID_DATE);
        valueMap.put("batch", BATCH);
        valueMap.put("terms_agree", TERMS_AGREE);
        valueMap.put("response_message", RESPONSE_MESSAGE);
        valueMap.put("return_date", RETURN_DATE);
        valueMap.put("trx_source_id", TRX_SOURCE_ID);
        valueMap.put("routing_number", ROUTING_NUMBER);
        valueMap.put("trx_source_code", TRX_SOURCE_CODE);
        valueMap.put("paylink_id", PAYLINK_ID);
        valueMap.put("currency_code", CURRENCY_CODE);
        valueMap.put("is_accountvault", IS_ACCOUNTVAULT);
        valueMap.put("created_user_id", CREATED_USER_ID);
        valueMap.put("modified_user_id", MODIFIED_USER_ID);
        valueMap.put("transaction_code", TRANSACTION_CODE);
        valueMap.put("effective_date", EFFECTIVE_DATE);
        valueMap.put("notification_phone", NOTIFICATION_PHONE);
        valueMap.put("cavv_result", CAVV_RESULT);
        valueMap.put("is_token", IS_TOKEN);
        valueMap.put("account_vault_id", ACCOUNT_VAULT_ID);
        valueMap.put("hosted_payment_page_id", HOSTED_PAYMENT_PAGE_ID);
        valueMap.put("stan", STAN);
        valueMap.put("currency", CURRENCY);
        valueMap.put("card_bin", CARD_BIN);
        valueMap.put("wallet_type", WALLET_TYPE);
        valueMap.put("account_vault", ACCOUNT_VAULT);
        valueMap.put("quick_invoice", QUICK_INVOICE);
        valueMap.put("log_emails", LOG_EMAILS);
        valueMap.put("is_voidable", IS_VOIDABLE);
        valueMap.put("is_reversible", IS_REVERSIBLE);
        valueMap.put("is_refundable", IS_REFUNDABLE);
        valueMap.put("is_completable", IS_COMPLETABLE);
        valueMap.put("is_settled", IS_SETTLED);
        valueMap.put("created_user", CREATED_USER);
        valueMap.put("location", LOCATION);
        valueMap.put("contact", CONTACT);
        valueMap.put("changelogs", CHANGELOGS);
        valueMap.put("product_transaction", PRODUCT_TRANSACTION);
        valueMap.put("all_tags", ALL_TAGS);
        valueMap.put("tagTransactions", TAGTRANSACTIONS);
        valueMap.put("declined_recurring_notification", DECLINED_RECURRING_NOTIFICATION);
        valueMap.put("payment_recurring_notification", PAYMENT_RECURRING_NOTIFICATION);
        valueMap.put("developer_company", DEVELOPER_COMPANY);
        valueMap.put("terminal", TERMINAL);
        valueMap.put("hosted_payment_page", HOSTED_PAYMENT_PAGE);
        valueMap.put("transaction_level3", TRANSACTION_LEVEL3);
        valueMap.put("developer_company_id", DEVELOPER_COMPANY_ID);
        valueMap.put("transaction_histories", TRANSACTION_HISTORIES);
        valueMap.put("surcharge_transaction", SURCHARGE_TRANSACTION);
        valueMap.put("surcharge", SURCHARGE);
        valueMap.put("signature", SIGNATURE);
        valueMap.put("reason_code", REASON_CODE);
        valueMap.put("type", TYPE);
        valueMap.put("status", STATUS);
        valueMap.put("transaction_batch", TRANSACTION_BATCH);
        valueMap.put("transaction_splits", TRANSACTION_SPLITS);
        valueMap.put("postback_logs", POSTBACK_LOGS);
        valueMap.put("currency_type", CURRENCY_TYPE);
        valueMap.put("transaction_references", TRANSACTION_REFERENCES);
        valueMap.put("rejected_transaction_ach_retries", REJECTED_TRANSACTION_ACH_RETRIES);
        valueMap.put("return_fee_transaction_ach_retry", RETURN_FEE_TRANSACTION_ACH_RETRY);
        valueMap.put("retry_transaction_ach_retry", RETRY_TRANSACTION_ACH_RETRY);
        valueMap.put("is_retriable", IS_RETRIABLE);
        valueMap.put("saved_account", SAVED_ACCOUNT);
        valueMap.put("balances", BALANCES);
        valueMap.put("transaction_three_ds", TRANSACTION_THREE_DS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Field57 constructFromString(String toConvert) throws IOException {
        Field57 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Field57 fromString(String toConvert) {
        if (!valueMap.containsKey(toConvert)) {
            return _UNKNOWN;
        }
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        if (value == null) {
            return null;
        }
        return value.toString();
    }

    /**
     * Convert list of Field57 values to list of string values.
     * @param toConvert The list of Field57 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Field57> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Field57 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 