/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Joi type.
 */
public class Joi
        extends BaseModel {
    private Conditions conditions;

    /**
     * Default constructor.
     */
    public Joi() {
    }

    /**
     * Initialization constructor.
     * @param  conditions  Conditions value for conditions.
     */
    public Joi(
            Conditions conditions) {
        this.conditions = conditions;
    }

    /**
     * Getter for Conditions.
     * @return Returns the Conditions
     */
    @JsonGetter("conditions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Conditions getConditions() {
        return conditions;
    }

    /**
     * Setter for Conditions.
     * @param conditions Value for Conditions
     */
    @JsonSetter("conditions")
    public void setConditions(Conditions conditions) {
        this.conditions = conditions;
    }

    /**
     * Converts this Joi into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Joi [" + "conditions=" + conditions + ", additionalProperties="
                + getAdditionalProperties() + "]";
    }

    /**
     * Builds a new {@link Joi.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Joi.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .conditions(getConditions());
        return builder;
    }

    /**
     * Class to build instances of {@link Joi}.
     */
    public static class Builder {
        private Conditions conditions;



        /**
         * Setter for conditions.
         * @param  conditions  Conditions value for conditions.
         * @return Builder
         */
        public Builder conditions(Conditions conditions) {
            this.conditions = conditions;
            return this;
        }

        /**
         * Builds a new {@link Joi} object using the set fields.
         * @return {@link Joi}
         */
        public Joi build() {
            return new Joi(conditions);
        }
    }
}
