/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.BaseModel;
import io.apimatic.core.types.OptionalNullable;
import java.util.List;

/**
 * This is a model class for List5 type.
 */
public class List5
        extends BaseModel {
    private String id;
    private Integer createdTs;
    private Integer modifiedTs;
    private OptionalNullable<String> accountNumber;
    private Address1 address;
    private OptionalNullable<String> brandingDomainId;
    private Boolean contactEmailTrxReceiptDefault;
    private OptionalNullable<String> defaultAch;
    private OptionalNullable<String> defaultCc;
    private OptionalNullable<String> emailReplyTo;
    private OptionalNullable<String> fax;
    private OptionalNullable<String> locationApiId;
    private OptionalNullable<String> locationApiKey;
    private OptionalNullable<String> locationC1;
    private OptionalNullable<String> locationC2;
    private OptionalNullable<String> locationC3;
    private String name;
    private OptionalNullable<String> officePhone;
    private OptionalNullable<String> officeExtPhone;
    private OptionalNullable<String> tz;
    private OptionalNullable<String> parentId;
    private Boolean showContactNotes;
    private Boolean showContactFiles;
    private OptionalNullable<String> createdUserId;
    private OptionalNullable<LocationTypeEnum> locationType;
    private OptionalNullable<String> brandingDomainUrl;
    private BrandingDomain brandingDomain;
    private List<ProductTransaction1> productTransactions;
    private ProductFile productFile;
    private ProductAccountvault productAccountvault;
    private ProductToken productToken;
    private ProductRecurring productRecurring;
    private List<Tag> tags;
    private List<Terminal2> terminals;
    private AdditionalAccess additionalAccess;

    /**
     * Default constructor.
     */
    public List5() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  createdTs  Integer value for createdTs.
     * @param  modifiedTs  Integer value for modifiedTs.
     * @param  accountNumber  String value for accountNumber.
     * @param  address  Address1 value for address.
     * @param  brandingDomainId  String value for brandingDomainId.
     * @param  contactEmailTrxReceiptDefault  Boolean value for contactEmailTrxReceiptDefault.
     * @param  defaultAch  String value for defaultAch.
     * @param  defaultCc  String value for defaultCc.
     * @param  emailReplyTo  String value for emailReplyTo.
     * @param  fax  String value for fax.
     * @param  locationApiId  String value for locationApiId.
     * @param  locationApiKey  String value for locationApiKey.
     * @param  locationC1  String value for locationC1.
     * @param  locationC2  String value for locationC2.
     * @param  locationC3  String value for locationC3.
     * @param  name  String value for name.
     * @param  officePhone  String value for officePhone.
     * @param  officeExtPhone  String value for officeExtPhone.
     * @param  tz  String value for tz.
     * @param  parentId  String value for parentId.
     * @param  showContactNotes  Boolean value for showContactNotes.
     * @param  showContactFiles  Boolean value for showContactFiles.
     * @param  createdUserId  String value for createdUserId.
     * @param  locationType  LocationTypeEnum value for locationType.
     * @param  brandingDomainUrl  String value for brandingDomainUrl.
     * @param  brandingDomain  BrandingDomain value for brandingDomain.
     * @param  productTransactions  List of ProductTransaction1 value for productTransactions.
     * @param  productFile  ProductFile value for productFile.
     * @param  productAccountvault  ProductAccountvault value for productAccountvault.
     * @param  productToken  ProductToken value for productToken.
     * @param  productRecurring  ProductRecurring value for productRecurring.
     * @param  tags  List of Tag value for tags.
     * @param  terminals  List of Terminal2 value for terminals.
     * @param  additionalAccess  AdditionalAccess value for additionalAccess.
     */
    public List5(
            String id,
            Integer createdTs,
            Integer modifiedTs,
            String accountNumber,
            Address1 address,
            String brandingDomainId,
            Boolean contactEmailTrxReceiptDefault,
            String defaultAch,
            String defaultCc,
            String emailReplyTo,
            String fax,
            String locationApiId,
            String locationApiKey,
            String locationC1,
            String locationC2,
            String locationC3,
            String name,
            String officePhone,
            String officeExtPhone,
            String tz,
            String parentId,
            Boolean showContactNotes,
            Boolean showContactFiles,
            String createdUserId,
            LocationTypeEnum locationType,
            String brandingDomainUrl,
            BrandingDomain brandingDomain,
            List<ProductTransaction1> productTransactions,
            ProductFile productFile,
            ProductAccountvault productAccountvault,
            ProductToken productToken,
            ProductRecurring productRecurring,
            List<Tag> tags,
            List<Terminal2> terminals,
            AdditionalAccess additionalAccess) {
        this.id = id;
        this.createdTs = createdTs;
        this.modifiedTs = modifiedTs;
        this.accountNumber = OptionalNullable.of(accountNumber);
        this.address = address;
        this.brandingDomainId = OptionalNullable.of(brandingDomainId);
        this.contactEmailTrxReceiptDefault = contactEmailTrxReceiptDefault;
        this.defaultAch = OptionalNullable.of(defaultAch);
        this.defaultCc = OptionalNullable.of(defaultCc);
        this.emailReplyTo = OptionalNullable.of(emailReplyTo);
        this.fax = OptionalNullable.of(fax);
        this.locationApiId = OptionalNullable.of(locationApiId);
        this.locationApiKey = OptionalNullable.of(locationApiKey);
        this.locationC1 = OptionalNullable.of(locationC1);
        this.locationC2 = OptionalNullable.of(locationC2);
        this.locationC3 = OptionalNullable.of(locationC3);
        this.name = name;
        this.officePhone = OptionalNullable.of(officePhone);
        this.officeExtPhone = OptionalNullable.of(officeExtPhone);
        this.tz = OptionalNullable.of(tz);
        this.parentId = OptionalNullable.of(parentId);
        this.showContactNotes = showContactNotes;
        this.showContactFiles = showContactFiles;
        this.createdUserId = OptionalNullable.of(createdUserId);
        this.locationType = OptionalNullable.of(locationType);
        this.brandingDomainUrl = OptionalNullable.of(brandingDomainUrl);
        this.brandingDomain = brandingDomain;
        this.productTransactions = productTransactions;
        this.productFile = productFile;
        this.productAccountvault = productAccountvault;
        this.productToken = productToken;
        this.productRecurring = productRecurring;
        this.tags = tags;
        this.terminals = terminals;
        this.additionalAccess = additionalAccess;
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  createdTs  Integer value for createdTs.
     * @param  modifiedTs  Integer value for modifiedTs.
     * @param  accountNumber  String value for accountNumber.
     * @param  address  Address1 value for address.
     * @param  brandingDomainId  String value for brandingDomainId.
     * @param  contactEmailTrxReceiptDefault  Boolean value for contactEmailTrxReceiptDefault.
     * @param  defaultAch  String value for defaultAch.
     * @param  defaultCc  String value for defaultCc.
     * @param  emailReplyTo  String value for emailReplyTo.
     * @param  fax  String value for fax.
     * @param  locationApiId  String value for locationApiId.
     * @param  locationApiKey  String value for locationApiKey.
     * @param  locationC1  String value for locationC1.
     * @param  locationC2  String value for locationC2.
     * @param  locationC3  String value for locationC3.
     * @param  name  String value for name.
     * @param  officePhone  String value for officePhone.
     * @param  officeExtPhone  String value for officeExtPhone.
     * @param  tz  String value for tz.
     * @param  parentId  String value for parentId.
     * @param  showContactNotes  Boolean value for showContactNotes.
     * @param  showContactFiles  Boolean value for showContactFiles.
     * @param  createdUserId  String value for createdUserId.
     * @param  locationType  LocationTypeEnum value for locationType.
     * @param  brandingDomainUrl  String value for brandingDomainUrl.
     * @param  brandingDomain  BrandingDomain value for brandingDomain.
     * @param  productTransactions  List of ProductTransaction1 value for productTransactions.
     * @param  productFile  ProductFile value for productFile.
     * @param  productAccountvault  ProductAccountvault value for productAccountvault.
     * @param  productToken  ProductToken value for productToken.
     * @param  productRecurring  ProductRecurring value for productRecurring.
     * @param  tags  List of Tag value for tags.
     * @param  terminals  List of Terminal2 value for terminals.
     * @param  additionalAccess  AdditionalAccess value for additionalAccess.
     */

    protected List5(String id, Integer createdTs, Integer modifiedTs,
            OptionalNullable<String> accountNumber, Address1 address,
            OptionalNullable<String> brandingDomainId, Boolean contactEmailTrxReceiptDefault,
            OptionalNullable<String> defaultAch, OptionalNullable<String> defaultCc,
            OptionalNullable<String> emailReplyTo, OptionalNullable<String> fax,
            OptionalNullable<String> locationApiId, OptionalNullable<String> locationApiKey,
            OptionalNullable<String> locationC1, OptionalNullable<String> locationC2,
            OptionalNullable<String> locationC3, String name, OptionalNullable<String> officePhone,
            OptionalNullable<String> officeExtPhone, OptionalNullable<String> tz,
            OptionalNullable<String> parentId, Boolean showContactNotes, Boolean showContactFiles,
            OptionalNullable<String> createdUserId, OptionalNullable<LocationTypeEnum> locationType,
            OptionalNullable<String> brandingDomainUrl, BrandingDomain brandingDomain,
            List<ProductTransaction1> productTransactions, ProductFile productFile,
            ProductAccountvault productAccountvault, ProductToken productToken,
            ProductRecurring productRecurring, List<Tag> tags, List<Terminal2> terminals,
            AdditionalAccess additionalAccess) {
        this.id = id;
        this.createdTs = createdTs;
        this.modifiedTs = modifiedTs;
        this.accountNumber = accountNumber;
        this.address = address;
        this.brandingDomainId = brandingDomainId;
        this.contactEmailTrxReceiptDefault = contactEmailTrxReceiptDefault;
        this.defaultAch = defaultAch;
        this.defaultCc = defaultCc;
        this.emailReplyTo = emailReplyTo;
        this.fax = fax;
        this.locationApiId = locationApiId;
        this.locationApiKey = locationApiKey;
        this.locationC1 = locationC1;
        this.locationC2 = locationC2;
        this.locationC3 = locationC3;
        this.name = name;
        this.officePhone = officePhone;
        this.officeExtPhone = officeExtPhone;
        this.tz = tz;
        this.parentId = parentId;
        this.showContactNotes = showContactNotes;
        this.showContactFiles = showContactFiles;
        this.createdUserId = createdUserId;
        this.locationType = locationType;
        this.brandingDomainUrl = brandingDomainUrl;
        this.brandingDomain = brandingDomain;
        this.productTransactions = productTransactions;
        this.productFile = productFile;
        this.productAccountvault = productAccountvault;
        this.productToken = productToken;
        this.productRecurring = productRecurring;
        this.tags = tags;
        this.terminals = terminals;
        this.additionalAccess = additionalAccess;
    }

    /**
     * Getter for Id.
     * Location ID
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Location ID
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for CreatedTs.
     * Created Time Stamp
     * @return Returns the Integer
     */
    @JsonGetter("created_ts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCreatedTs() {
        return createdTs;
    }

    /**
     * Setter for CreatedTs.
     * Created Time Stamp
     * @param createdTs Value for Integer
     */
    @JsonSetter("created_ts")
    public void setCreatedTs(Integer createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * Getter for ModifiedTs.
     * Modified Time Stamp
     * @return Returns the Integer
     */
    @JsonGetter("modified_ts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getModifiedTs() {
        return modifiedTs;
    }

    /**
     * Setter for ModifiedTs.
     * Modified Time Stamp
     * @param modifiedTs Value for Integer
     */
    @JsonSetter("modified_ts")
    public void setModifiedTs(Integer modifiedTs) {
        this.modifiedTs = modifiedTs;
    }

    /**
     * Internal Getter for AccountNumber.
     * Account number
     * @return Returns the Internal String
     */
    @JsonGetter("account_number")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetAccountNumber() {
        return this.accountNumber;
    }

    /**
     * Getter for AccountNumber.
     * Account number
     * @return Returns the String
     */
    public String getAccountNumber() {
        return OptionalNullable.getFrom(accountNumber);
    }

    /**
     * Setter for AccountNumber.
     * Account number
     * @param accountNumber Value for String
     */
    @JsonSetter("account_number")
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = OptionalNullable.of(accountNumber);
    }

    /**
     * UnSetter for AccountNumber.
     * Account number
     */
    public void unsetAccountNumber() {
        accountNumber = null;
    }

    /**
     * Getter for Address.
     * Address
     * @return Returns the Address1
     */
    @JsonGetter("address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Address1 getAddress() {
        return address;
    }

    /**
     * Setter for Address.
     * Address
     * @param address Value for Address1
     */
    @JsonSetter("address")
    public void setAddress(Address1 address) {
        this.address = address;
    }

    /**
     * Internal Getter for BrandingDomainId.
     * GUID for Branding Domain
     * @return Returns the Internal String
     */
    @JsonGetter("branding_domain_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetBrandingDomainId() {
        return this.brandingDomainId;
    }

    /**
     * Getter for BrandingDomainId.
     * GUID for Branding Domain
     * @return Returns the String
     */
    public String getBrandingDomainId() {
        return OptionalNullable.getFrom(brandingDomainId);
    }

    /**
     * Setter for BrandingDomainId.
     * GUID for Branding Domain
     * @param brandingDomainId Value for String
     */
    @JsonSetter("branding_domain_id")
    public void setBrandingDomainId(String brandingDomainId) {
        this.brandingDomainId = OptionalNullable.of(brandingDomainId);
    }

    /**
     * UnSetter for BrandingDomainId.
     * GUID for Branding Domain
     */
    public void unsetBrandingDomainId() {
        brandingDomainId = null;
    }

    /**
     * Getter for ContactEmailTrxReceiptDefault.
     * If true, will email contact receipt for any transaction
     * @return Returns the Boolean
     */
    @JsonGetter("contact_email_trx_receipt_default")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getContactEmailTrxReceiptDefault() {
        return contactEmailTrxReceiptDefault;
    }

    /**
     * Setter for ContactEmailTrxReceiptDefault.
     * If true, will email contact receipt for any transaction
     * @param contactEmailTrxReceiptDefault Value for Boolean
     */
    @JsonSetter("contact_email_trx_receipt_default")
    public void setContactEmailTrxReceiptDefault(Boolean contactEmailTrxReceiptDefault) {
        this.contactEmailTrxReceiptDefault = contactEmailTrxReceiptDefault;
    }

    /**
     * Internal Getter for DefaultAch.
     * GUID for Location's default ACH Product Transaction
     * @return Returns the Internal String
     */
    @JsonGetter("default_ach")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDefaultAch() {
        return this.defaultAch;
    }

    /**
     * Getter for DefaultAch.
     * GUID for Location's default ACH Product Transaction
     * @return Returns the String
     */
    public String getDefaultAch() {
        return OptionalNullable.getFrom(defaultAch);
    }

    /**
     * Setter for DefaultAch.
     * GUID for Location's default ACH Product Transaction
     * @param defaultAch Value for String
     */
    @JsonSetter("default_ach")
    public void setDefaultAch(String defaultAch) {
        this.defaultAch = OptionalNullable.of(defaultAch);
    }

    /**
     * UnSetter for DefaultAch.
     * GUID for Location's default ACH Product Transaction
     */
    public void unsetDefaultAch() {
        defaultAch = null;
    }

    /**
     * Internal Getter for DefaultCc.
     * GUID for Location's default CC Product Transaction
     * @return Returns the Internal String
     */
    @JsonGetter("default_cc")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDefaultCc() {
        return this.defaultCc;
    }

    /**
     * Getter for DefaultCc.
     * GUID for Location's default CC Product Transaction
     * @return Returns the String
     */
    public String getDefaultCc() {
        return OptionalNullable.getFrom(defaultCc);
    }

    /**
     * Setter for DefaultCc.
     * GUID for Location's default CC Product Transaction
     * @param defaultCc Value for String
     */
    @JsonSetter("default_cc")
    public void setDefaultCc(String defaultCc) {
        this.defaultCc = OptionalNullable.of(defaultCc);
    }

    /**
     * UnSetter for DefaultCc.
     * GUID for Location's default CC Product Transaction
     */
    public void unsetDefaultCc() {
        defaultCc = null;
    }

    /**
     * Internal Getter for EmailReplyTo.
     * Used as from email address when sending various notifications
     * @return Returns the Internal String
     */
    @JsonGetter("email_reply_to")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetEmailReplyTo() {
        return this.emailReplyTo;
    }

    /**
     * Getter for EmailReplyTo.
     * Used as from email address when sending various notifications
     * @return Returns the String
     */
    public String getEmailReplyTo() {
        return OptionalNullable.getFrom(emailReplyTo);
    }

    /**
     * Setter for EmailReplyTo.
     * Used as from email address when sending various notifications
     * @param emailReplyTo Value for String
     */
    @JsonSetter("email_reply_to")
    public void setEmailReplyTo(String emailReplyTo) {
        this.emailReplyTo = OptionalNullable.of(emailReplyTo);
    }

    /**
     * UnSetter for EmailReplyTo.
     * Used as from email address when sending various notifications
     */
    public void unsetEmailReplyTo() {
        emailReplyTo = null;
    }

    /**
     * Internal Getter for Fax.
     * Fax number
     * @return Returns the Internal String
     */
    @JsonGetter("fax")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetFax() {
        return this.fax;
    }

    /**
     * Getter for Fax.
     * Fax number
     * @return Returns the String
     */
    public String getFax() {
        return OptionalNullable.getFrom(fax);
    }

    /**
     * Setter for Fax.
     * Fax number
     * @param fax Value for String
     */
    @JsonSetter("fax")
    public void setFax(String fax) {
        this.fax = OptionalNullable.of(fax);
    }

    /**
     * UnSetter for Fax.
     * Fax number
     */
    public void unsetFax() {
        fax = null;
    }

    /**
     * Internal Getter for LocationApiId.
     * Location api ID
     * @return Returns the Internal String
     */
    @JsonGetter("location_api_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetLocationApiId() {
        return this.locationApiId;
    }

    /**
     * Getter for LocationApiId.
     * Location api ID
     * @return Returns the String
     */
    public String getLocationApiId() {
        return OptionalNullable.getFrom(locationApiId);
    }

    /**
     * Setter for LocationApiId.
     * Location api ID
     * @param locationApiId Value for String
     */
    @JsonSetter("location_api_id")
    public void setLocationApiId(String locationApiId) {
        this.locationApiId = OptionalNullable.of(locationApiId);
    }

    /**
     * UnSetter for LocationApiId.
     * Location api ID
     */
    public void unsetLocationApiId() {
        locationApiId = null;
    }

    /**
     * Internal Getter for LocationApiKey.
     * Location api key
     * @return Returns the Internal String
     */
    @JsonGetter("location_api_key")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetLocationApiKey() {
        return this.locationApiKey;
    }

    /**
     * Getter for LocationApiKey.
     * Location api key
     * @return Returns the String
     */
    public String getLocationApiKey() {
        return OptionalNullable.getFrom(locationApiKey);
    }

    /**
     * Setter for LocationApiKey.
     * Location api key
     * @param locationApiKey Value for String
     */
    @JsonSetter("location_api_key")
    public void setLocationApiKey(String locationApiKey) {
        this.locationApiKey = OptionalNullable.of(locationApiKey);
    }

    /**
     * UnSetter for LocationApiKey.
     * Location api key
     */
    public void unsetLocationApiKey() {
        locationApiKey = null;
    }

    /**
     * Internal Getter for LocationC1.
     * Can be used to store custom information for location.
     * @return Returns the Internal String
     */
    @JsonGetter("location_c1")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetLocationC1() {
        return this.locationC1;
    }

    /**
     * Getter for LocationC1.
     * Can be used to store custom information for location.
     * @return Returns the String
     */
    public String getLocationC1() {
        return OptionalNullable.getFrom(locationC1);
    }

    /**
     * Setter for LocationC1.
     * Can be used to store custom information for location.
     * @param locationC1 Value for String
     */
    @JsonSetter("location_c1")
    public void setLocationC1(String locationC1) {
        this.locationC1 = OptionalNullable.of(locationC1);
    }

    /**
     * UnSetter for LocationC1.
     * Can be used to store custom information for location.
     */
    public void unsetLocationC1() {
        locationC1 = null;
    }

    /**
     * Internal Getter for LocationC2.
     * Can be used to store custom information for location.
     * @return Returns the Internal String
     */
    @JsonGetter("location_c2")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetLocationC2() {
        return this.locationC2;
    }

    /**
     * Getter for LocationC2.
     * Can be used to store custom information for location.
     * @return Returns the String
     */
    public String getLocationC2() {
        return OptionalNullable.getFrom(locationC2);
    }

    /**
     * Setter for LocationC2.
     * Can be used to store custom information for location.
     * @param locationC2 Value for String
     */
    @JsonSetter("location_c2")
    public void setLocationC2(String locationC2) {
        this.locationC2 = OptionalNullable.of(locationC2);
    }

    /**
     * UnSetter for LocationC2.
     * Can be used to store custom information for location.
     */
    public void unsetLocationC2() {
        locationC2 = null;
    }

    /**
     * Internal Getter for LocationC3.
     * Can be used to store custom information for location.
     * @return Returns the Internal String
     */
    @JsonGetter("location_c3")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetLocationC3() {
        return this.locationC3;
    }

    /**
     * Getter for LocationC3.
     * Can be used to store custom information for location.
     * @return Returns the String
     */
    public String getLocationC3() {
        return OptionalNullable.getFrom(locationC3);
    }

    /**
     * Setter for LocationC3.
     * Can be used to store custom information for location.
     * @param locationC3 Value for String
     */
    @JsonSetter("location_c3")
    public void setLocationC3(String locationC3) {
        this.locationC3 = OptionalNullable.of(locationC3);
    }

    /**
     * UnSetter for LocationC3.
     * Can be used to store custom information for location.
     */
    public void unsetLocationC3() {
        locationC3 = null;
    }

    /**
     * Getter for Name.
     * Name of the company
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Name of the company
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Internal Getter for OfficePhone.
     * Office phone number
     * @return Returns the Internal String
     */
    @JsonGetter("office_phone")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetOfficePhone() {
        return this.officePhone;
    }

    /**
     * Getter for OfficePhone.
     * Office phone number
     * @return Returns the String
     */
    public String getOfficePhone() {
        return OptionalNullable.getFrom(officePhone);
    }

    /**
     * Setter for OfficePhone.
     * Office phone number
     * @param officePhone Value for String
     */
    @JsonSetter("office_phone")
    public void setOfficePhone(String officePhone) {
        this.officePhone = OptionalNullable.of(officePhone);
    }

    /**
     * UnSetter for OfficePhone.
     * Office phone number
     */
    public void unsetOfficePhone() {
        officePhone = null;
    }

    /**
     * Internal Getter for OfficeExtPhone.
     * Office phone extension number
     * @return Returns the Internal String
     */
    @JsonGetter("office_ext_phone")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetOfficeExtPhone() {
        return this.officeExtPhone;
    }

    /**
     * Getter for OfficeExtPhone.
     * Office phone extension number
     * @return Returns the String
     */
    public String getOfficeExtPhone() {
        return OptionalNullable.getFrom(officeExtPhone);
    }

    /**
     * Setter for OfficeExtPhone.
     * Office phone extension number
     * @param officeExtPhone Value for String
     */
    @JsonSetter("office_ext_phone")
    public void setOfficeExtPhone(String officeExtPhone) {
        this.officeExtPhone = OptionalNullable.of(officeExtPhone);
    }

    /**
     * UnSetter for OfficeExtPhone.
     * Office phone extension number
     */
    public void unsetOfficeExtPhone() {
        officeExtPhone = null;
    }

    /**
     * Internal Getter for Tz.
     * Time zone
     * @return Returns the Internal String
     */
    @JsonGetter("tz")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetTz() {
        return this.tz;
    }

    /**
     * Getter for Tz.
     * Time zone
     * @return Returns the String
     */
    public String getTz() {
        return OptionalNullable.getFrom(tz);
    }

    /**
     * Setter for Tz.
     * Time zone
     * @param tz Value for String
     */
    @JsonSetter("tz")
    public void setTz(String tz) {
        this.tz = OptionalNullable.of(tz);
    }

    /**
     * UnSetter for Tz.
     * Time zone
     */
    public void unsetTz() {
        tz = null;
    }

    /**
     * Internal Getter for ParentId.
     * Location GUID of the parent location
     * @return Returns the Internal String
     */
    @JsonGetter("parent_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetParentId() {
        return this.parentId;
    }

    /**
     * Getter for ParentId.
     * Location GUID of the parent location
     * @return Returns the String
     */
    public String getParentId() {
        return OptionalNullable.getFrom(parentId);
    }

    /**
     * Setter for ParentId.
     * Location GUID of the parent location
     * @param parentId Value for String
     */
    @JsonSetter("parent_id")
    public void setParentId(String parentId) {
        this.parentId = OptionalNullable.of(parentId);
    }

    /**
     * UnSetter for ParentId.
     * Location GUID of the parent location
     */
    public void unsetParentId() {
        parentId = null;
    }

    /**
     * Getter for ShowContactNotes.
     * If set to true will show 'Notes' tab on Contact
     * @return Returns the Boolean
     */
    @JsonGetter("show_contact_notes")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getShowContactNotes() {
        return showContactNotes;
    }

    /**
     * Setter for ShowContactNotes.
     * If set to true will show 'Notes' tab on Contact
     * @param showContactNotes Value for Boolean
     */
    @JsonSetter("show_contact_notes")
    public void setShowContactNotes(Boolean showContactNotes) {
        this.showContactNotes = showContactNotes;
    }

    /**
     * Getter for ShowContactFiles.
     * If set to true will show 'Files' tab on Contact
     * @return Returns the Boolean
     */
    @JsonGetter("show_contact_files")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getShowContactFiles() {
        return showContactFiles;
    }

    /**
     * Setter for ShowContactFiles.
     * If set to true will show 'Files' tab on Contact
     * @param showContactFiles Value for Boolean
     */
    @JsonSetter("show_contact_files")
    public void setShowContactFiles(Boolean showContactFiles) {
        this.showContactFiles = showContactFiles;
    }

    /**
     * Internal Getter for CreatedUserId.
     * User ID Created the register
     * @return Returns the Internal String
     */
    @JsonGetter("created_user_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetCreatedUserId() {
        return this.createdUserId;
    }

    /**
     * Getter for CreatedUserId.
     * User ID Created the register
     * @return Returns the String
     */
    public String getCreatedUserId() {
        return OptionalNullable.getFrom(createdUserId);
    }

    /**
     * Setter for CreatedUserId.
     * User ID Created the register
     * @param createdUserId Value for String
     */
    @JsonSetter("created_user_id")
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = OptionalNullable.of(createdUserId);
    }

    /**
     * UnSetter for CreatedUserId.
     * User ID Created the register
     */
    public void unsetCreatedUserId() {
        createdUserId = null;
    }

    /**
     * Internal Getter for LocationType.
     * Location Type
     * @return Returns the Internal LocationTypeEnum
     */
    @JsonGetter("location_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<LocationTypeEnum> internalGetLocationType() {
        return this.locationType;
    }

    /**
     * Getter for LocationType.
     * Location Type
     * @return Returns the LocationTypeEnum
     */
    public LocationTypeEnum getLocationType() {
        return OptionalNullable.getFrom(locationType);
    }

    /**
     * Setter for LocationType.
     * Location Type
     * @param locationType Value for LocationTypeEnum
     */
    @JsonSetter("location_type")
    public void setLocationType(LocationTypeEnum locationType) {
        this.locationType = OptionalNullable.of(locationType);
    }

    /**
     * UnSetter for LocationType.
     * Location Type
     */
    public void unsetLocationType() {
        locationType = null;
    }

    /**
     * Internal Getter for BrandingDomainUrl.
     * Branding domain URL
     * @return Returns the Internal String
     */
    @JsonGetter("branding_domain_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetBrandingDomainUrl() {
        return this.brandingDomainUrl;
    }

    /**
     * Getter for BrandingDomainUrl.
     * Branding domain URL
     * @return Returns the String
     */
    public String getBrandingDomainUrl() {
        return OptionalNullable.getFrom(brandingDomainUrl);
    }

    /**
     * Setter for BrandingDomainUrl.
     * Branding domain URL
     * @param brandingDomainUrl Value for String
     */
    @JsonSetter("branding_domain_url")
    public void setBrandingDomainUrl(String brandingDomainUrl) {
        this.brandingDomainUrl = OptionalNullable.of(brandingDomainUrl);
    }

    /**
     * UnSetter for BrandingDomainUrl.
     * Branding domain URL
     */
    public void unsetBrandingDomainUrl() {
        brandingDomainUrl = null;
    }

    /**
     * Getter for BrandingDomain.
     * Branding domain array
     * @return Returns the BrandingDomain
     */
    @JsonGetter("branding_domain")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BrandingDomain getBrandingDomain() {
        return brandingDomain;
    }

    /**
     * Setter for BrandingDomain.
     * Branding domain array
     * @param brandingDomain Value for BrandingDomain
     */
    @JsonSetter("branding_domain")
    public void setBrandingDomain(BrandingDomain brandingDomain) {
        this.brandingDomain = brandingDomain;
    }

    /**
     * Getter for ProductTransactions.
     * Product Transactions array
     * @return Returns the List of ProductTransaction1
     */
    @JsonGetter("product_transactions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ProductTransaction1> getProductTransactions() {
        return productTransactions;
    }

    /**
     * Setter for ProductTransactions.
     * Product Transactions array
     * @param productTransactions Value for List of ProductTransaction1
     */
    @JsonSetter("product_transactions")
    public void setProductTransactions(List<ProductTransaction1> productTransactions) {
        this.productTransactions = productTransactions;
    }

    /**
     * Getter for ProductFile.
     * Product file array
     * @return Returns the ProductFile
     */
    @JsonGetter("product_file")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProductFile getProductFile() {
        return productFile;
    }

    /**
     * Setter for ProductFile.
     * Product file array
     * @param productFile Value for ProductFile
     */
    @JsonSetter("product_file")
    public void setProductFile(ProductFile productFile) {
        this.productFile = productFile;
    }

    /**
     * Getter for ProductAccountvault.
     * Product Token array (legacy)
     * @return Returns the ProductAccountvault
     */
    @JsonGetter("product_accountvault")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProductAccountvault getProductAccountvault() {
        return productAccountvault;
    }

    /**
     * Setter for ProductAccountvault.
     * Product Token array (legacy)
     * @param productAccountvault Value for ProductAccountvault
     */
    @JsonSetter("product_accountvault")
    public void setProductAccountvault(ProductAccountvault productAccountvault) {
        this.productAccountvault = productAccountvault;
    }

    /**
     * Getter for ProductToken.
     * Product Token array
     * @return Returns the ProductToken
     */
    @JsonGetter("product_token")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProductToken getProductToken() {
        return productToken;
    }

    /**
     * Setter for ProductToken.
     * Product Token array
     * @param productToken Value for ProductToken
     */
    @JsonSetter("product_token")
    public void setProductToken(ProductToken productToken) {
        this.productToken = productToken;
    }

    /**
     * Getter for ProductRecurring.
     * Product recurring array
     * @return Returns the ProductRecurring
     */
    @JsonGetter("product_recurring")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProductRecurring getProductRecurring() {
        return productRecurring;
    }

    /**
     * Setter for ProductRecurring.
     * Product recurring array
     * @param productRecurring Value for ProductRecurring
     */
    @JsonSetter("product_recurring")
    public void setProductRecurring(ProductRecurring productRecurring) {
        this.productRecurring = productRecurring;
    }

    /**
     * Getter for Tags.
     * Tags array
     * @return Returns the List of Tag
     */
    @JsonGetter("tags")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Tag> getTags() {
        return tags;
    }

    /**
     * Setter for Tags.
     * Tags array
     * @param tags Value for List of Tag
     */
    @JsonSetter("tags")
    public void setTags(List<Tag> tags) {
        this.tags = tags;
    }

    /**
     * Getter for Terminals.
     * Terminals array
     * @return Returns the List of Terminal2
     */
    @JsonGetter("terminals")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Terminal2> getTerminals() {
        return terminals;
    }

    /**
     * Setter for Terminals.
     * Terminals array
     * @param terminals Value for List of Terminal2
     */
    @JsonSetter("terminals")
    public void setTerminals(List<Terminal2> terminals) {
        this.terminals = terminals;
    }

    /**
     * Getter for AdditionalAccess.
     * @return Returns the AdditionalAccess
     */
    @JsonGetter("additional_access")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AdditionalAccess getAdditionalAccess() {
        return additionalAccess;
    }

    /**
     * Setter for AdditionalAccess.
     * @param additionalAccess Value for AdditionalAccess
     */
    @JsonSetter("additional_access")
    public void setAdditionalAccess(AdditionalAccess additionalAccess) {
        this.additionalAccess = additionalAccess;
    }

    /**
     * Converts this List5 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "List5 [" + "id=" + id + ", createdTs=" + createdTs + ", modifiedTs=" + modifiedTs
                + ", accountNumber=" + accountNumber + ", address=" + address
                + ", brandingDomainId=" + brandingDomainId + ", contactEmailTrxReceiptDefault="
                + contactEmailTrxReceiptDefault + ", defaultAch=" + defaultAch + ", defaultCc="
                + defaultCc + ", emailReplyTo=" + emailReplyTo + ", fax=" + fax + ", locationApiId="
                + locationApiId + ", locationApiKey=" + locationApiKey + ", locationC1="
                + locationC1 + ", locationC2=" + locationC2 + ", locationC3=" + locationC3
                + ", name=" + name + ", officePhone=" + officePhone + ", officeExtPhone="
                + officeExtPhone + ", tz=" + tz + ", parentId=" + parentId + ", showContactNotes="
                + showContactNotes + ", showContactFiles=" + showContactFiles + ", createdUserId="
                + createdUserId + ", locationType=" + locationType + ", brandingDomainUrl="
                + brandingDomainUrl + ", brandingDomain=" + brandingDomain
                + ", productTransactions=" + productTransactions + ", productFile=" + productFile
                + ", productAccountvault=" + productAccountvault + ", productToken=" + productToken
                + ", productRecurring=" + productRecurring + ", tags=" + tags + ", terminals="
                + terminals + ", additionalAccess=" + additionalAccess + ", additionalProperties="
                + getAdditionalProperties() + "]";
    }

    /**
     * Builds a new {@link List5.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link List5.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .createdTs(getCreatedTs())
                .modifiedTs(getModifiedTs())
                .address(getAddress())
                .contactEmailTrxReceiptDefault(getContactEmailTrxReceiptDefault())
                .name(getName())
                .showContactNotes(getShowContactNotes())
                .showContactFiles(getShowContactFiles())
                .brandingDomain(getBrandingDomain())
                .productTransactions(getProductTransactions())
                .productFile(getProductFile())
                .productAccountvault(getProductAccountvault())
                .productToken(getProductToken())
                .productRecurring(getProductRecurring())
                .tags(getTags())
                .terminals(getTerminals())
                .additionalAccess(getAdditionalAccess());
        builder.accountNumber = internalGetAccountNumber();
        builder.brandingDomainId = internalGetBrandingDomainId();
        builder.defaultAch = internalGetDefaultAch();
        builder.defaultCc = internalGetDefaultCc();
        builder.emailReplyTo = internalGetEmailReplyTo();
        builder.fax = internalGetFax();
        builder.locationApiId = internalGetLocationApiId();
        builder.locationApiKey = internalGetLocationApiKey();
        builder.locationC1 = internalGetLocationC1();
        builder.locationC2 = internalGetLocationC2();
        builder.locationC3 = internalGetLocationC3();
        builder.officePhone = internalGetOfficePhone();
        builder.officeExtPhone = internalGetOfficeExtPhone();
        builder.tz = internalGetTz();
        builder.parentId = internalGetParentId();
        builder.createdUserId = internalGetCreatedUserId();
        builder.locationType = internalGetLocationType();
        builder.brandingDomainUrl = internalGetBrandingDomainUrl();
        return builder;
    }

    /**
     * Class to build instances of {@link List5}.
     */
    public static class Builder {
        private String id;
        private Integer createdTs;
        private Integer modifiedTs;
        private OptionalNullable<String> accountNumber;
        private Address1 address;
        private OptionalNullable<String> brandingDomainId;
        private Boolean contactEmailTrxReceiptDefault;
        private OptionalNullable<String> defaultAch;
        private OptionalNullable<String> defaultCc;
        private OptionalNullable<String> emailReplyTo;
        private OptionalNullable<String> fax;
        private OptionalNullable<String> locationApiId;
        private OptionalNullable<String> locationApiKey;
        private OptionalNullable<String> locationC1;
        private OptionalNullable<String> locationC2;
        private OptionalNullable<String> locationC3;
        private String name;
        private OptionalNullable<String> officePhone;
        private OptionalNullable<String> officeExtPhone;
        private OptionalNullable<String> tz;
        private OptionalNullable<String> parentId;
        private Boolean showContactNotes;
        private Boolean showContactFiles;
        private OptionalNullable<String> createdUserId;
        private OptionalNullable<LocationTypeEnum> locationType;
        private OptionalNullable<String> brandingDomainUrl;
        private BrandingDomain brandingDomain;
        private List<ProductTransaction1> productTransactions;
        private ProductFile productFile;
        private ProductAccountvault productAccountvault;
        private ProductToken productToken;
        private ProductRecurring productRecurring;
        private List<Tag> tags;
        private List<Terminal2> terminals;
        private AdditionalAccess additionalAccess;



        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for createdTs.
         * @param  createdTs  Integer value for createdTs.
         * @return Builder
         */
        public Builder createdTs(Integer createdTs) {
            this.createdTs = createdTs;
            return this;
        }

        /**
         * Setter for modifiedTs.
         * @param  modifiedTs  Integer value for modifiedTs.
         * @return Builder
         */
        public Builder modifiedTs(Integer modifiedTs) {
            this.modifiedTs = modifiedTs;
            return this;
        }

        /**
         * Setter for accountNumber.
         * @param  accountNumber  String value for accountNumber.
         * @return Builder
         */
        public Builder accountNumber(String accountNumber) {
            this.accountNumber = OptionalNullable.of(accountNumber);
            return this;
        }

        /**
         * UnSetter for accountNumber.
         * @return Builder
         */
        public Builder unsetAccountNumber() {
            accountNumber = null;
            return this;
        }

        /**
         * Setter for address.
         * @param  address  Address1 value for address.
         * @return Builder
         */
        public Builder address(Address1 address) {
            this.address = address;
            return this;
        }

        /**
         * Setter for brandingDomainId.
         * @param  brandingDomainId  String value for brandingDomainId.
         * @return Builder
         */
        public Builder brandingDomainId(String brandingDomainId) {
            this.brandingDomainId = OptionalNullable.of(brandingDomainId);
            return this;
        }

        /**
         * UnSetter for brandingDomainId.
         * @return Builder
         */
        public Builder unsetBrandingDomainId() {
            brandingDomainId = null;
            return this;
        }

        /**
         * Setter for contactEmailTrxReceiptDefault.
         * @param  contactEmailTrxReceiptDefault  Boolean value for contactEmailTrxReceiptDefault.
         * @return Builder
         */
        public Builder contactEmailTrxReceiptDefault(Boolean contactEmailTrxReceiptDefault) {
            this.contactEmailTrxReceiptDefault = contactEmailTrxReceiptDefault;
            return this;
        }

        /**
         * Setter for defaultAch.
         * @param  defaultAch  String value for defaultAch.
         * @return Builder
         */
        public Builder defaultAch(String defaultAch) {
            this.defaultAch = OptionalNullable.of(defaultAch);
            return this;
        }

        /**
         * UnSetter for defaultAch.
         * @return Builder
         */
        public Builder unsetDefaultAch() {
            defaultAch = null;
            return this;
        }

        /**
         * Setter for defaultCc.
         * @param  defaultCc  String value for defaultCc.
         * @return Builder
         */
        public Builder defaultCc(String defaultCc) {
            this.defaultCc = OptionalNullable.of(defaultCc);
            return this;
        }

        /**
         * UnSetter for defaultCc.
         * @return Builder
         */
        public Builder unsetDefaultCc() {
            defaultCc = null;
            return this;
        }

        /**
         * Setter for emailReplyTo.
         * @param  emailReplyTo  String value for emailReplyTo.
         * @return Builder
         */
        public Builder emailReplyTo(String emailReplyTo) {
            this.emailReplyTo = OptionalNullable.of(emailReplyTo);
            return this;
        }

        /**
         * UnSetter for emailReplyTo.
         * @return Builder
         */
        public Builder unsetEmailReplyTo() {
            emailReplyTo = null;
            return this;
        }

        /**
         * Setter for fax.
         * @param  fax  String value for fax.
         * @return Builder
         */
        public Builder fax(String fax) {
            this.fax = OptionalNullable.of(fax);
            return this;
        }

        /**
         * UnSetter for fax.
         * @return Builder
         */
        public Builder unsetFax() {
            fax = null;
            return this;
        }

        /**
         * Setter for locationApiId.
         * @param  locationApiId  String value for locationApiId.
         * @return Builder
         */
        public Builder locationApiId(String locationApiId) {
            this.locationApiId = OptionalNullable.of(locationApiId);
            return this;
        }

        /**
         * UnSetter for locationApiId.
         * @return Builder
         */
        public Builder unsetLocationApiId() {
            locationApiId = null;
            return this;
        }

        /**
         * Setter for locationApiKey.
         * @param  locationApiKey  String value for locationApiKey.
         * @return Builder
         */
        public Builder locationApiKey(String locationApiKey) {
            this.locationApiKey = OptionalNullable.of(locationApiKey);
            return this;
        }

        /**
         * UnSetter for locationApiKey.
         * @return Builder
         */
        public Builder unsetLocationApiKey() {
            locationApiKey = null;
            return this;
        }

        /**
         * Setter for locationC1.
         * @param  locationC1  String value for locationC1.
         * @return Builder
         */
        public Builder locationC1(String locationC1) {
            this.locationC1 = OptionalNullable.of(locationC1);
            return this;
        }

        /**
         * UnSetter for locationC1.
         * @return Builder
         */
        public Builder unsetLocationC1() {
            locationC1 = null;
            return this;
        }

        /**
         * Setter for locationC2.
         * @param  locationC2  String value for locationC2.
         * @return Builder
         */
        public Builder locationC2(String locationC2) {
            this.locationC2 = OptionalNullable.of(locationC2);
            return this;
        }

        /**
         * UnSetter for locationC2.
         * @return Builder
         */
        public Builder unsetLocationC2() {
            locationC2 = null;
            return this;
        }

        /**
         * Setter for locationC3.
         * @param  locationC3  String value for locationC3.
         * @return Builder
         */
        public Builder locationC3(String locationC3) {
            this.locationC3 = OptionalNullable.of(locationC3);
            return this;
        }

        /**
         * UnSetter for locationC3.
         * @return Builder
         */
        public Builder unsetLocationC3() {
            locationC3 = null;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for officePhone.
         * @param  officePhone  String value for officePhone.
         * @return Builder
         */
        public Builder officePhone(String officePhone) {
            this.officePhone = OptionalNullable.of(officePhone);
            return this;
        }

        /**
         * UnSetter for officePhone.
         * @return Builder
         */
        public Builder unsetOfficePhone() {
            officePhone = null;
            return this;
        }

        /**
         * Setter for officeExtPhone.
         * @param  officeExtPhone  String value for officeExtPhone.
         * @return Builder
         */
        public Builder officeExtPhone(String officeExtPhone) {
            this.officeExtPhone = OptionalNullable.of(officeExtPhone);
            return this;
        }

        /**
         * UnSetter for officeExtPhone.
         * @return Builder
         */
        public Builder unsetOfficeExtPhone() {
            officeExtPhone = null;
            return this;
        }

        /**
         * Setter for tz.
         * @param  tz  String value for tz.
         * @return Builder
         */
        public Builder tz(String tz) {
            this.tz = OptionalNullable.of(tz);
            return this;
        }

        /**
         * UnSetter for tz.
         * @return Builder
         */
        public Builder unsetTz() {
            tz = null;
            return this;
        }

        /**
         * Setter for parentId.
         * @param  parentId  String value for parentId.
         * @return Builder
         */
        public Builder parentId(String parentId) {
            this.parentId = OptionalNullable.of(parentId);
            return this;
        }

        /**
         * UnSetter for parentId.
         * @return Builder
         */
        public Builder unsetParentId() {
            parentId = null;
            return this;
        }

        /**
         * Setter for showContactNotes.
         * @param  showContactNotes  Boolean value for showContactNotes.
         * @return Builder
         */
        public Builder showContactNotes(Boolean showContactNotes) {
            this.showContactNotes = showContactNotes;
            return this;
        }

        /**
         * Setter for showContactFiles.
         * @param  showContactFiles  Boolean value for showContactFiles.
         * @return Builder
         */
        public Builder showContactFiles(Boolean showContactFiles) {
            this.showContactFiles = showContactFiles;
            return this;
        }

        /**
         * Setter for createdUserId.
         * @param  createdUserId  String value for createdUserId.
         * @return Builder
         */
        public Builder createdUserId(String createdUserId) {
            this.createdUserId = OptionalNullable.of(createdUserId);
            return this;
        }

        /**
         * UnSetter for createdUserId.
         * @return Builder
         */
        public Builder unsetCreatedUserId() {
            createdUserId = null;
            return this;
        }

        /**
         * Setter for locationType.
         * @param  locationType  LocationTypeEnum value for locationType.
         * @return Builder
         */
        public Builder locationType(LocationTypeEnum locationType) {
            this.locationType = OptionalNullable.of(locationType);
            return this;
        }

        /**
         * UnSetter for locationType.
         * @return Builder
         */
        public Builder unsetLocationType() {
            locationType = null;
            return this;
        }

        /**
         * Setter for brandingDomainUrl.
         * @param  brandingDomainUrl  String value for brandingDomainUrl.
         * @return Builder
         */
        public Builder brandingDomainUrl(String brandingDomainUrl) {
            this.brandingDomainUrl = OptionalNullable.of(brandingDomainUrl);
            return this;
        }

        /**
         * UnSetter for brandingDomainUrl.
         * @return Builder
         */
        public Builder unsetBrandingDomainUrl() {
            brandingDomainUrl = null;
            return this;
        }

        /**
         * Setter for brandingDomain.
         * @param  brandingDomain  BrandingDomain value for brandingDomain.
         * @return Builder
         */
        public Builder brandingDomain(BrandingDomain brandingDomain) {
            this.brandingDomain = brandingDomain;
            return this;
        }

        /**
         * Setter for productTransactions.
         * @param  productTransactions  List of ProductTransaction1 value for productTransactions.
         * @return Builder
         */
        public Builder productTransactions(List<ProductTransaction1> productTransactions) {
            this.productTransactions = productTransactions;
            return this;
        }

        /**
         * Setter for productFile.
         * @param  productFile  ProductFile value for productFile.
         * @return Builder
         */
        public Builder productFile(ProductFile productFile) {
            this.productFile = productFile;
            return this;
        }

        /**
         * Setter for productAccountvault.
         * @param  productAccountvault  ProductAccountvault value for productAccountvault.
         * @return Builder
         */
        public Builder productAccountvault(ProductAccountvault productAccountvault) {
            this.productAccountvault = productAccountvault;
            return this;
        }

        /**
         * Setter for productToken.
         * @param  productToken  ProductToken value for productToken.
         * @return Builder
         */
        public Builder productToken(ProductToken productToken) {
            this.productToken = productToken;
            return this;
        }

        /**
         * Setter for productRecurring.
         * @param  productRecurring  ProductRecurring value for productRecurring.
         * @return Builder
         */
        public Builder productRecurring(ProductRecurring productRecurring) {
            this.productRecurring = productRecurring;
            return this;
        }

        /**
         * Setter for tags.
         * @param  tags  List of Tag value for tags.
         * @return Builder
         */
        public Builder tags(List<Tag> tags) {
            this.tags = tags;
            return this;
        }

        /**
         * Setter for terminals.
         * @param  terminals  List of Terminal2 value for terminals.
         * @return Builder
         */
        public Builder terminals(List<Terminal2> terminals) {
            this.terminals = terminals;
            return this;
        }

        /**
         * Setter for additionalAccess.
         * @param  additionalAccess  AdditionalAccess value for additionalAccess.
         * @return Builder
         */
        public Builder additionalAccess(AdditionalAccess additionalAccess) {
            this.additionalAccess = additionalAccess;
            return this;
        }

        /**
         * Builds a new {@link List5} object using the set fields.
         * @return {@link List5}
         */
        public List5 build() {
            return new List5(id, createdTs, modifiedTs, accountNumber, address, brandingDomainId,
                    contactEmailTrxReceiptDefault, defaultAch, defaultCc, emailReplyTo, fax,
                    locationApiId, locationApiKey, locationC1, locationC2, locationC3, name,
                    officePhone, officeExtPhone, tz, parentId, showContactNotes, showContactFiles,
                    createdUserId, locationType, brandingDomainUrl, brandingDomain,
                    productTransactions, productFile, productAccountvault, productToken,
                    productRecurring, tags, terminals, additionalAccess);
        }
    }
}
