/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for LocationBillingAccount type.
 */
public class LocationBillingAccount {
    private String title;
    private OptionalNullable<String> locationId;
    private OptionalNullable<String> locationApiId;
    private OptionalNullable<String> achSecCode;
    private OptionalNullable<String> accountNumber;
    private OptionalNullable<String> routing;
    private OptionalNullable<String> expDate;
    private OptionalNullable<String> billingZip;
    private OptionalNullable<String> accountType;
    private OptionalNullable<String> accountHolderName;
    private String id;
    private Integer createdTs;
    private Integer modifiedTs;
    private OptionalNullable<String> createdUserId;
    private OptionalNullable<String> modifiedUserId;
    private OptionalNullable<String> billingDescriptor;
    private OptionalNullable<String> paymentMethod;
    private String portfolioId;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public LocationBillingAccount() {
    }

    /**
     * Initialization constructor.
     * @param  title  String value for title.
     * @param  locationId  String value for locationId.
     * @param  locationApiId  String value for locationApiId.
     * @param  achSecCode  String value for achSecCode.
     * @param  accountNumber  String value for accountNumber.
     * @param  routing  String value for routing.
     * @param  expDate  String value for expDate.
     * @param  billingZip  String value for billingZip.
     * @param  accountType  String value for accountType.
     * @param  accountHolderName  String value for accountHolderName.
     * @param  id  String value for id.
     * @param  createdTs  Integer value for createdTs.
     * @param  modifiedTs  Integer value for modifiedTs.
     * @param  createdUserId  String value for createdUserId.
     * @param  modifiedUserId  String value for modifiedUserId.
     * @param  billingDescriptor  String value for billingDescriptor.
     * @param  paymentMethod  String value for paymentMethod.
     * @param  portfolioId  String value for portfolioId.
     */
    public LocationBillingAccount(
            String title,
            String locationId,
            String locationApiId,
            String achSecCode,
            String accountNumber,
            String routing,
            String expDate,
            String billingZip,
            String accountType,
            String accountHolderName,
            String id,
            Integer createdTs,
            Integer modifiedTs,
            String createdUserId,
            String modifiedUserId,
            String billingDescriptor,
            String paymentMethod,
            String portfolioId) {
        this.title = title;
        this.locationId = OptionalNullable.of(locationId);
        this.locationApiId = OptionalNullable.of(locationApiId);
        this.achSecCode = OptionalNullable.of(achSecCode);
        this.accountNumber = OptionalNullable.of(accountNumber);
        this.routing = OptionalNullable.of(routing);
        this.expDate = OptionalNullable.of(expDate);
        this.billingZip = OptionalNullable.of(billingZip);
        this.accountType = OptionalNullable.of(accountType);
        this.accountHolderName = OptionalNullable.of(accountHolderName);
        this.id = id;
        this.createdTs = createdTs;
        this.modifiedTs = modifiedTs;
        this.createdUserId = OptionalNullable.of(createdUserId);
        this.modifiedUserId = OptionalNullable.of(modifiedUserId);
        this.billingDescriptor = OptionalNullable.of(billingDescriptor);
        this.paymentMethod = OptionalNullable.of(paymentMethod);
        this.portfolioId = portfolioId;
    }

    /**
     * Initialization constructor.
     * @param  title  String value for title.
     * @param  locationId  String value for locationId.
     * @param  locationApiId  String value for locationApiId.
     * @param  achSecCode  String value for achSecCode.
     * @param  accountNumber  String value for accountNumber.
     * @param  routing  String value for routing.
     * @param  expDate  String value for expDate.
     * @param  billingZip  String value for billingZip.
     * @param  accountType  String value for accountType.
     * @param  accountHolderName  String value for accountHolderName.
     * @param  id  String value for id.
     * @param  createdTs  Integer value for createdTs.
     * @param  modifiedTs  Integer value for modifiedTs.
     * @param  createdUserId  String value for createdUserId.
     * @param  modifiedUserId  String value for modifiedUserId.
     * @param  billingDescriptor  String value for billingDescriptor.
     * @param  paymentMethod  String value for paymentMethod.
     * @param  portfolioId  String value for portfolioId.
     */

    protected LocationBillingAccount(String title, OptionalNullable<String> locationId,
            OptionalNullable<String> locationApiId, OptionalNullable<String> achSecCode,
            OptionalNullable<String> accountNumber, OptionalNullable<String> routing,
            OptionalNullable<String> expDate, OptionalNullable<String> billingZip,
            OptionalNullable<String> accountType, OptionalNullable<String> accountHolderName,
            String id, Integer createdTs, Integer modifiedTs,
            OptionalNullable<String> createdUserId, OptionalNullable<String> modifiedUserId,
            OptionalNullable<String> billingDescriptor, OptionalNullable<String> paymentMethod,
            String portfolioId) {
        this.title = title;
        this.locationId = locationId;
        this.locationApiId = locationApiId;
        this.achSecCode = achSecCode;
        this.accountNumber = accountNumber;
        this.routing = routing;
        this.expDate = expDate;
        this.billingZip = billingZip;
        this.accountType = accountType;
        this.accountHolderName = accountHolderName;
        this.id = id;
        this.createdTs = createdTs;
        this.modifiedTs = modifiedTs;
        this.createdUserId = createdUserId;
        this.modifiedUserId = modifiedUserId;
        this.billingDescriptor = billingDescriptor;
        this.paymentMethod = paymentMethod;
        this.portfolioId = portfolioId;
    }

    /**
     * Getter for Title.
     * Title
     * @return Returns the String
     */
    @JsonGetter("title")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * Title
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Internal Getter for LocationId.
     * Location ID
     * @return Returns the Internal String
     */
    @JsonGetter("location_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetLocationId() {
        return this.locationId;
    }

    /**
     * Getter for LocationId.
     * Location ID
     * @return Returns the String
     */
    public String getLocationId() {
        return OptionalNullable.getFrom(locationId);
    }

    /**
     * Setter for LocationId.
     * Location ID
     * @param locationId Value for String
     */
    @JsonSetter("location_id")
    public void setLocationId(String locationId) {
        this.locationId = OptionalNullable.of(locationId);
    }

    /**
     * UnSetter for LocationId.
     * Location ID
     */
    public void unsetLocationId() {
        locationId = null;
    }

    /**
     * Internal Getter for LocationApiId.
     * Location Api Id
     * @return Returns the Internal String
     */
    @JsonGetter("location_api_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetLocationApiId() {
        return this.locationApiId;
    }

    /**
     * Getter for LocationApiId.
     * Location Api Id
     * @return Returns the String
     */
    public String getLocationApiId() {
        return OptionalNullable.getFrom(locationApiId);
    }

    /**
     * Setter for LocationApiId.
     * Location Api Id
     * @param locationApiId Value for String
     */
    @JsonSetter("location_api_id")
    public void setLocationApiId(String locationApiId) {
        this.locationApiId = OptionalNullable.of(locationApiId);
    }

    /**
     * UnSetter for LocationApiId.
     * Location Api Id
     */
    public void unsetLocationApiId() {
        locationApiId = null;
    }

    /**
     * Internal Getter for AchSecCode.
     * Ach Sec Code
     * @return Returns the Internal String
     */
    @JsonGetter("ach_sec_code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetAchSecCode() {
        return this.achSecCode;
    }

    /**
     * Getter for AchSecCode.
     * Ach Sec Code
     * @return Returns the String
     */
    public String getAchSecCode() {
        return OptionalNullable.getFrom(achSecCode);
    }

    /**
     * Setter for AchSecCode.
     * Ach Sec Code
     * @param achSecCode Value for String
     */
    @JsonSetter("ach_sec_code")
    public void setAchSecCode(String achSecCode) {
        this.achSecCode = OptionalNullable.of(achSecCode);
    }

    /**
     * UnSetter for AchSecCode.
     * Ach Sec Code
     */
    public void unsetAchSecCode() {
        achSecCode = null;
    }

    /**
     * Internal Getter for AccountNumber.
     * Account number
     * @return Returns the Internal String
     */
    @JsonGetter("account_number")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetAccountNumber() {
        return this.accountNumber;
    }

    /**
     * Getter for AccountNumber.
     * Account number
     * @return Returns the String
     */
    public String getAccountNumber() {
        return OptionalNullable.getFrom(accountNumber);
    }

    /**
     * Setter for AccountNumber.
     * Account number
     * @param accountNumber Value for String
     */
    @JsonSetter("account_number")
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = OptionalNullable.of(accountNumber);
    }

    /**
     * UnSetter for AccountNumber.
     * Account number
     */
    public void unsetAccountNumber() {
        accountNumber = null;
    }

    /**
     * Internal Getter for Routing.
     * Routing
     * @return Returns the Internal String
     */
    @JsonGetter("routing")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetRouting() {
        return this.routing;
    }

    /**
     * Getter for Routing.
     * Routing
     * @return Returns the String
     */
    public String getRouting() {
        return OptionalNullable.getFrom(routing);
    }

    /**
     * Setter for Routing.
     * Routing
     * @param routing Value for String
     */
    @JsonSetter("routing")
    public void setRouting(String routing) {
        this.routing = OptionalNullable.of(routing);
    }

    /**
     * UnSetter for Routing.
     * Routing
     */
    public void unsetRouting() {
        routing = null;
    }

    /**
     * Internal Getter for ExpDate.
     * Exp Date
     * @return Returns the Internal String
     */
    @JsonGetter("exp_date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetExpDate() {
        return this.expDate;
    }

    /**
     * Getter for ExpDate.
     * Exp Date
     * @return Returns the String
     */
    public String getExpDate() {
        return OptionalNullable.getFrom(expDate);
    }

    /**
     * Setter for ExpDate.
     * Exp Date
     * @param expDate Value for String
     */
    @JsonSetter("exp_date")
    public void setExpDate(String expDate) {
        this.expDate = OptionalNullable.of(expDate);
    }

    /**
     * UnSetter for ExpDate.
     * Exp Date
     */
    public void unsetExpDate() {
        expDate = null;
    }

    /**
     * Internal Getter for BillingZip.
     * Billing Zip
     * @return Returns the Internal String
     */
    @JsonGetter("billing_zip")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetBillingZip() {
        return this.billingZip;
    }

    /**
     * Getter for BillingZip.
     * Billing Zip
     * @return Returns the String
     */
    public String getBillingZip() {
        return OptionalNullable.getFrom(billingZip);
    }

    /**
     * Setter for BillingZip.
     * Billing Zip
     * @param billingZip Value for String
     */
    @JsonSetter("billing_zip")
    public void setBillingZip(String billingZip) {
        this.billingZip = OptionalNullable.of(billingZip);
    }

    /**
     * UnSetter for BillingZip.
     * Billing Zip
     */
    public void unsetBillingZip() {
        billingZip = null;
    }

    /**
     * Internal Getter for AccountType.
     * Account Type
     * @return Returns the Internal String
     */
    @JsonGetter("account_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetAccountType() {
        return this.accountType;
    }

    /**
     * Getter for AccountType.
     * Account Type
     * @return Returns the String
     */
    public String getAccountType() {
        return OptionalNullable.getFrom(accountType);
    }

    /**
     * Setter for AccountType.
     * Account Type
     * @param accountType Value for String
     */
    @JsonSetter("account_type")
    public void setAccountType(String accountType) {
        this.accountType = OptionalNullable.of(accountType);
    }

    /**
     * UnSetter for AccountType.
     * Account Type
     */
    public void unsetAccountType() {
        accountType = null;
    }

    /**
     * Internal Getter for AccountHolderName.
     * Account Holder Name
     * @return Returns the Internal String
     */
    @JsonGetter("account_holder_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetAccountHolderName() {
        return this.accountHolderName;
    }

    /**
     * Getter for AccountHolderName.
     * Account Holder Name
     * @return Returns the String
     */
    public String getAccountHolderName() {
        return OptionalNullable.getFrom(accountHolderName);
    }

    /**
     * Setter for AccountHolderName.
     * Account Holder Name
     * @param accountHolderName Value for String
     */
    @JsonSetter("account_holder_name")
    public void setAccountHolderName(String accountHolderName) {
        this.accountHolderName = OptionalNullable.of(accountHolderName);
    }

    /**
     * UnSetter for AccountHolderName.
     * Account Holder Name
     */
    public void unsetAccountHolderName() {
        accountHolderName = null;
    }

    /**
     * Getter for Id.
     * Location Billing Account Id
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Location Billing Account Id
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for CreatedTs.
     * Created Time Stamp
     * @return Returns the Integer
     */
    @JsonGetter("created_ts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCreatedTs() {
        return createdTs;
    }

    /**
     * Setter for CreatedTs.
     * Created Time Stamp
     * @param createdTs Value for Integer
     */
    @JsonSetter("created_ts")
    public void setCreatedTs(Integer createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * Getter for ModifiedTs.
     * Modified Time Stamp
     * @return Returns the Integer
     */
    @JsonGetter("modified_ts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getModifiedTs() {
        return modifiedTs;
    }

    /**
     * Setter for ModifiedTs.
     * Modified Time Stamp
     * @param modifiedTs Value for Integer
     */
    @JsonSetter("modified_ts")
    public void setModifiedTs(Integer modifiedTs) {
        this.modifiedTs = modifiedTs;
    }

    /**
     * Internal Getter for CreatedUserId.
     * Created User Id
     * @return Returns the Internal String
     */
    @JsonGetter("created_user_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetCreatedUserId() {
        return this.createdUserId;
    }

    /**
     * Getter for CreatedUserId.
     * Created User Id
     * @return Returns the String
     */
    public String getCreatedUserId() {
        return OptionalNullable.getFrom(createdUserId);
    }

    /**
     * Setter for CreatedUserId.
     * Created User Id
     * @param createdUserId Value for String
     */
    @JsonSetter("created_user_id")
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = OptionalNullable.of(createdUserId);
    }

    /**
     * UnSetter for CreatedUserId.
     * Created User Id
     */
    public void unsetCreatedUserId() {
        createdUserId = null;
    }

    /**
     * Internal Getter for ModifiedUserId.
     * Modified User Id
     * @return Returns the Internal String
     */
    @JsonGetter("modified_user_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetModifiedUserId() {
        return this.modifiedUserId;
    }

    /**
     * Getter for ModifiedUserId.
     * Modified User Id
     * @return Returns the String
     */
    public String getModifiedUserId() {
        return OptionalNullable.getFrom(modifiedUserId);
    }

    /**
     * Setter for ModifiedUserId.
     * Modified User Id
     * @param modifiedUserId Value for String
     */
    @JsonSetter("modified_user_id")
    public void setModifiedUserId(String modifiedUserId) {
        this.modifiedUserId = OptionalNullable.of(modifiedUserId);
    }

    /**
     * UnSetter for ModifiedUserId.
     * Modified User Id
     */
    public void unsetModifiedUserId() {
        modifiedUserId = null;
    }

    /**
     * Internal Getter for BillingDescriptor.
     * Billing Descriptor
     * @return Returns the Internal String
     */
    @JsonGetter("billing_descriptor")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetBillingDescriptor() {
        return this.billingDescriptor;
    }

    /**
     * Getter for BillingDescriptor.
     * Billing Descriptor
     * @return Returns the String
     */
    public String getBillingDescriptor() {
        return OptionalNullable.getFrom(billingDescriptor);
    }

    /**
     * Setter for BillingDescriptor.
     * Billing Descriptor
     * @param billingDescriptor Value for String
     */
    @JsonSetter("billing_descriptor")
    public void setBillingDescriptor(String billingDescriptor) {
        this.billingDescriptor = OptionalNullable.of(billingDescriptor);
    }

    /**
     * UnSetter for BillingDescriptor.
     * Billing Descriptor
     */
    public void unsetBillingDescriptor() {
        billingDescriptor = null;
    }

    /**
     * Internal Getter for PaymentMethod.
     * Billing Descriptor
     * @return Returns the Internal String
     */
    @JsonGetter("payment_method")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetPaymentMethod() {
        return this.paymentMethod;
    }

    /**
     * Getter for PaymentMethod.
     * Billing Descriptor
     * @return Returns the String
     */
    public String getPaymentMethod() {
        return OptionalNullable.getFrom(paymentMethod);
    }

    /**
     * Setter for PaymentMethod.
     * Billing Descriptor
     * @param paymentMethod Value for String
     */
    @JsonSetter("payment_method")
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = OptionalNullable.of(paymentMethod);
    }

    /**
     * UnSetter for PaymentMethod.
     * Billing Descriptor
     */
    public void unsetPaymentMethod() {
        paymentMethod = null;
    }

    /**
     * Getter for PortfolioId.
     * Portfolio Id
     * @return Returns the String
     */
    @JsonGetter("portfolio_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPortfolioId() {
        return portfolioId;
    }

    /**
     * Setter for PortfolioId.
     * Portfolio Id
     * @param portfolioId Value for String
     */
    @JsonSetter("portfolio_id")
    public void setPortfolioId(String portfolioId) {
        this.portfolioId = portfolioId;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this LocationBillingAccount into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LocationBillingAccount [" + "title=" + title + ", locationId=" + locationId
                + ", locationApiId=" + locationApiId + ", achSecCode=" + achSecCode
                + ", accountNumber=" + accountNumber + ", routing=" + routing + ", expDate="
                + expDate + ", billingZip=" + billingZip + ", accountType=" + accountType
                + ", accountHolderName=" + accountHolderName + ", id=" + id + ", createdTs="
                + createdTs + ", modifiedTs=" + modifiedTs + ", createdUserId=" + createdUserId
                + ", modifiedUserId=" + modifiedUserId + ", billingDescriptor=" + billingDescriptor
                + ", paymentMethod=" + paymentMethod + ", portfolioId=" + portfolioId
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link LocationBillingAccount.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LocationBillingAccount.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .title(getTitle())
                .id(getId())
                .createdTs(getCreatedTs())
                .modifiedTs(getModifiedTs())
                .portfolioId(getPortfolioId());
        builder.locationId = internalGetLocationId();
        builder.locationApiId = internalGetLocationApiId();
        builder.achSecCode = internalGetAchSecCode();
        builder.accountNumber = internalGetAccountNumber();
        builder.routing = internalGetRouting();
        builder.expDate = internalGetExpDate();
        builder.billingZip = internalGetBillingZip();
        builder.accountType = internalGetAccountType();
        builder.accountHolderName = internalGetAccountHolderName();
        builder.createdUserId = internalGetCreatedUserId();
        builder.modifiedUserId = internalGetModifiedUserId();
        builder.billingDescriptor = internalGetBillingDescriptor();
        builder.paymentMethod = internalGetPaymentMethod();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link LocationBillingAccount}.
     */
    public static class Builder {
        private String title;
        private OptionalNullable<String> locationId;
        private OptionalNullable<String> locationApiId;
        private OptionalNullable<String> achSecCode;
        private OptionalNullable<String> accountNumber;
        private OptionalNullable<String> routing;
        private OptionalNullable<String> expDate;
        private OptionalNullable<String> billingZip;
        private OptionalNullable<String> accountType;
        private OptionalNullable<String> accountHolderName;
        private String id;
        private Integer createdTs;
        private Integer modifiedTs;
        private OptionalNullable<String> createdUserId;
        private OptionalNullable<String> modifiedUserId;
        private OptionalNullable<String> billingDescriptor;
        private OptionalNullable<String> paymentMethod;
        private String portfolioId;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for locationId.
         * @param  locationId  String value for locationId.
         * @return Builder
         */
        public Builder locationId(String locationId) {
            this.locationId = OptionalNullable.of(locationId);
            return this;
        }

        /**
         * UnSetter for locationId.
         * @return Builder
         */
        public Builder unsetLocationId() {
            locationId = null;
            return this;
        }

        /**
         * Setter for locationApiId.
         * @param  locationApiId  String value for locationApiId.
         * @return Builder
         */
        public Builder locationApiId(String locationApiId) {
            this.locationApiId = OptionalNullable.of(locationApiId);
            return this;
        }

        /**
         * UnSetter for locationApiId.
         * @return Builder
         */
        public Builder unsetLocationApiId() {
            locationApiId = null;
            return this;
        }

        /**
         * Setter for achSecCode.
         * @param  achSecCode  String value for achSecCode.
         * @return Builder
         */
        public Builder achSecCode(String achSecCode) {
            this.achSecCode = OptionalNullable.of(achSecCode);
            return this;
        }

        /**
         * UnSetter for achSecCode.
         * @return Builder
         */
        public Builder unsetAchSecCode() {
            achSecCode = null;
            return this;
        }

        /**
         * Setter for accountNumber.
         * @param  accountNumber  String value for accountNumber.
         * @return Builder
         */
        public Builder accountNumber(String accountNumber) {
            this.accountNumber = OptionalNullable.of(accountNumber);
            return this;
        }

        /**
         * UnSetter for accountNumber.
         * @return Builder
         */
        public Builder unsetAccountNumber() {
            accountNumber = null;
            return this;
        }

        /**
         * Setter for routing.
         * @param  routing  String value for routing.
         * @return Builder
         */
        public Builder routing(String routing) {
            this.routing = OptionalNullable.of(routing);
            return this;
        }

        /**
         * UnSetter for routing.
         * @return Builder
         */
        public Builder unsetRouting() {
            routing = null;
            return this;
        }

        /**
         * Setter for expDate.
         * @param  expDate  String value for expDate.
         * @return Builder
         */
        public Builder expDate(String expDate) {
            this.expDate = OptionalNullable.of(expDate);
            return this;
        }

        /**
         * UnSetter for expDate.
         * @return Builder
         */
        public Builder unsetExpDate() {
            expDate = null;
            return this;
        }

        /**
         * Setter for billingZip.
         * @param  billingZip  String value for billingZip.
         * @return Builder
         */
        public Builder billingZip(String billingZip) {
            this.billingZip = OptionalNullable.of(billingZip);
            return this;
        }

        /**
         * UnSetter for billingZip.
         * @return Builder
         */
        public Builder unsetBillingZip() {
            billingZip = null;
            return this;
        }

        /**
         * Setter for accountType.
         * @param  accountType  String value for accountType.
         * @return Builder
         */
        public Builder accountType(String accountType) {
            this.accountType = OptionalNullable.of(accountType);
            return this;
        }

        /**
         * UnSetter for accountType.
         * @return Builder
         */
        public Builder unsetAccountType() {
            accountType = null;
            return this;
        }

        /**
         * Setter for accountHolderName.
         * @param  accountHolderName  String value for accountHolderName.
         * @return Builder
         */
        public Builder accountHolderName(String accountHolderName) {
            this.accountHolderName = OptionalNullable.of(accountHolderName);
            return this;
        }

        /**
         * UnSetter for accountHolderName.
         * @return Builder
         */
        public Builder unsetAccountHolderName() {
            accountHolderName = null;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for createdTs.
         * @param  createdTs  Integer value for createdTs.
         * @return Builder
         */
        public Builder createdTs(Integer createdTs) {
            this.createdTs = createdTs;
            return this;
        }

        /**
         * Setter for modifiedTs.
         * @param  modifiedTs  Integer value for modifiedTs.
         * @return Builder
         */
        public Builder modifiedTs(Integer modifiedTs) {
            this.modifiedTs = modifiedTs;
            return this;
        }

        /**
         * Setter for createdUserId.
         * @param  createdUserId  String value for createdUserId.
         * @return Builder
         */
        public Builder createdUserId(String createdUserId) {
            this.createdUserId = OptionalNullable.of(createdUserId);
            return this;
        }

        /**
         * UnSetter for createdUserId.
         * @return Builder
         */
        public Builder unsetCreatedUserId() {
            createdUserId = null;
            return this;
        }

        /**
         * Setter for modifiedUserId.
         * @param  modifiedUserId  String value for modifiedUserId.
         * @return Builder
         */
        public Builder modifiedUserId(String modifiedUserId) {
            this.modifiedUserId = OptionalNullable.of(modifiedUserId);
            return this;
        }

        /**
         * UnSetter for modifiedUserId.
         * @return Builder
         */
        public Builder unsetModifiedUserId() {
            modifiedUserId = null;
            return this;
        }

        /**
         * Setter for billingDescriptor.
         * @param  billingDescriptor  String value for billingDescriptor.
         * @return Builder
         */
        public Builder billingDescriptor(String billingDescriptor) {
            this.billingDescriptor = OptionalNullable.of(billingDescriptor);
            return this;
        }

        /**
         * UnSetter for billingDescriptor.
         * @return Builder
         */
        public Builder unsetBillingDescriptor() {
            billingDescriptor = null;
            return this;
        }

        /**
         * Setter for paymentMethod.
         * @param  paymentMethod  String value for paymentMethod.
         * @return Builder
         */
        public Builder paymentMethod(String paymentMethod) {
            this.paymentMethod = OptionalNullable.of(paymentMethod);
            return this;
        }

        /**
         * UnSetter for paymentMethod.
         * @return Builder
         */
        public Builder unsetPaymentMethod() {
            paymentMethod = null;
            return this;
        }

        /**
         * Setter for portfolioId.
         * @param  portfolioId  String value for portfolioId.
         * @return Builder
         */
        public Builder portfolioId(String portfolioId) {
            this.portfolioId = portfolioId;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link LocationBillingAccount} object using the set fields.
         * @return {@link LocationBillingAccount}
         */
        public LocationBillingAccount build() {
            LocationBillingAccount model =
                    new LocationBillingAccount(title, locationId, locationApiId, achSecCode,
                            accountNumber, routing, expDate, billingZip, accountType,
                            accountHolderName, id, createdTs, modifiedTs, createdUserId,
                            modifiedUserId, billingDescriptor, paymentMethod, portfolioId);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
