/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.BaseModel;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for PostbackLog type.
 */
public class PostbackLog
        extends BaseModel {
    private OptionalNullable<PostbackStatusIdEnum> postbackStatusId;
    private String id;
    private String postbackConfigId;
    private String changelogId;
    private OptionalNullable<String> httpVerb;
    private OptionalNullable<Integer> nextRunTs;
    private OptionalNullable<Integer> createdTs;
    private OptionalNullable<String> model;
    private OptionalNullable<String> modelId;

    /**
     * Default constructor.
     */
    public PostbackLog() {
    }

    /**
     * Initialization constructor.
     * @param  postbackStatusId  PostbackStatusIdEnum value for postbackStatusId.
     * @param  id  String value for id.
     * @param  postbackConfigId  String value for postbackConfigId.
     * @param  changelogId  String value for changelogId.
     * @param  httpVerb  String value for httpVerb.
     * @param  nextRunTs  Integer value for nextRunTs.
     * @param  createdTs  Integer value for createdTs.
     * @param  model  String value for model.
     * @param  modelId  String value for modelId.
     */
    public PostbackLog(
            PostbackStatusIdEnum postbackStatusId,
            String id,
            String postbackConfigId,
            String changelogId,
            String httpVerb,
            Integer nextRunTs,
            Integer createdTs,
            String model,
            String modelId) {
        this.postbackStatusId = OptionalNullable.of(postbackStatusId);
        this.id = id;
        this.postbackConfigId = postbackConfigId;
        this.changelogId = changelogId;
        this.httpVerb = OptionalNullable.of(httpVerb);
        this.nextRunTs = OptionalNullable.of(nextRunTs);
        this.createdTs = OptionalNullable.of(createdTs);
        this.model = OptionalNullable.of(model);
        this.modelId = OptionalNullable.of(modelId);
    }

    /**
     * Initialization constructor.
     * @param  postbackStatusId  PostbackStatusIdEnum value for postbackStatusId.
     * @param  id  String value for id.
     * @param  postbackConfigId  String value for postbackConfigId.
     * @param  changelogId  String value for changelogId.
     * @param  httpVerb  String value for httpVerb.
     * @param  nextRunTs  Integer value for nextRunTs.
     * @param  createdTs  Integer value for createdTs.
     * @param  model  String value for model.
     * @param  modelId  String value for modelId.
     */

    protected PostbackLog(OptionalNullable<PostbackStatusIdEnum> postbackStatusId, String id,
            String postbackConfigId, String changelogId, OptionalNullable<String> httpVerb,
            OptionalNullable<Integer> nextRunTs, OptionalNullable<Integer> createdTs,
            OptionalNullable<String> model, OptionalNullable<String> modelId) {
        this.postbackStatusId = postbackStatusId;
        this.id = id;
        this.postbackConfigId = postbackConfigId;
        this.changelogId = changelogId;
        this.httpVerb = httpVerb;
        this.nextRunTs = nextRunTs;
        this.createdTs = createdTs;
        this.model = model;
        this.modelId = modelId;
    }

    /**
     * Internal Getter for PostbackStatusId.
     * Postback Status Id
     * @return Returns the Internal PostbackStatusIdEnum
     */
    @JsonGetter("postback_status_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<PostbackStatusIdEnum> internalGetPostbackStatusId() {
        return this.postbackStatusId;
    }

    /**
     * Getter for PostbackStatusId.
     * Postback Status Id
     * @return Returns the PostbackStatusIdEnum
     */
    public PostbackStatusIdEnum getPostbackStatusId() {
        return OptionalNullable.getFrom(postbackStatusId);
    }

    /**
     * Setter for PostbackStatusId.
     * Postback Status Id
     * @param postbackStatusId Value for PostbackStatusIdEnum
     */
    @JsonSetter("postback_status_id")
    public void setPostbackStatusId(PostbackStatusIdEnum postbackStatusId) {
        this.postbackStatusId = OptionalNullable.of(postbackStatusId);
    }

    /**
     * UnSetter for PostbackStatusId.
     * Postback Status Id
     */
    public void unsetPostbackStatusId() {
        postbackStatusId = null;
    }

    /**
     * Getter for Id.
     * Postback Log Id
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Postback Log Id
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for PostbackConfigId.
     * Postback Config Id
     * @return Returns the String
     */
    @JsonGetter("postback_config_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPostbackConfigId() {
        return postbackConfigId;
    }

    /**
     * Setter for PostbackConfigId.
     * Postback Config Id
     * @param postbackConfigId Value for String
     */
    @JsonSetter("postback_config_id")
    public void setPostbackConfigId(String postbackConfigId) {
        this.postbackConfigId = postbackConfigId;
    }

    /**
     * Getter for ChangelogId.
     * Changelog Id
     * @return Returns the String
     */
    @JsonGetter("changelog_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getChangelogId() {
        return changelogId;
    }

    /**
     * Setter for ChangelogId.
     * Changelog Id
     * @param changelogId Value for String
     */
    @JsonSetter("changelog_id")
    public void setChangelogId(String changelogId) {
        this.changelogId = changelogId;
    }

    /**
     * Internal Getter for HttpVerb.
     * Http Verb
     * @return Returns the Internal String
     */
    @JsonGetter("http_verb")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetHttpVerb() {
        return this.httpVerb;
    }

    /**
     * Getter for HttpVerb.
     * Http Verb
     * @return Returns the String
     */
    public String getHttpVerb() {
        return OptionalNullable.getFrom(httpVerb);
    }

    /**
     * Setter for HttpVerb.
     * Http Verb
     * @param httpVerb Value for String
     */
    @JsonSetter("http_verb")
    public void setHttpVerb(String httpVerb) {
        this.httpVerb = OptionalNullable.of(httpVerb);
    }

    /**
     * UnSetter for HttpVerb.
     * Http Verb
     */
    public void unsetHttpVerb() {
        httpVerb = null;
    }

    /**
     * Internal Getter for NextRunTs.
     * Next Run
     * @return Returns the Internal Integer
     */
    @JsonGetter("next_run_ts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetNextRunTs() {
        return this.nextRunTs;
    }

    /**
     * Getter for NextRunTs.
     * Next Run
     * @return Returns the Integer
     */
    public Integer getNextRunTs() {
        return OptionalNullable.getFrom(nextRunTs);
    }

    /**
     * Setter for NextRunTs.
     * Next Run
     * @param nextRunTs Value for Integer
     */
    @JsonSetter("next_run_ts")
    public void setNextRunTs(Integer nextRunTs) {
        this.nextRunTs = OptionalNullable.of(nextRunTs);
    }

    /**
     * UnSetter for NextRunTs.
     * Next Run
     */
    public void unsetNextRunTs() {
        nextRunTs = null;
    }

    /**
     * Internal Getter for CreatedTs.
     * Created Time Stamp
     * @return Returns the Internal Integer
     */
    @JsonGetter("created_ts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetCreatedTs() {
        return this.createdTs;
    }

    /**
     * Getter for CreatedTs.
     * Created Time Stamp
     * @return Returns the Integer
     */
    public Integer getCreatedTs() {
        return OptionalNullable.getFrom(createdTs);
    }

    /**
     * Setter for CreatedTs.
     * Created Time Stamp
     * @param createdTs Value for Integer
     */
    @JsonSetter("created_ts")
    public void setCreatedTs(Integer createdTs) {
        this.createdTs = OptionalNullable.of(createdTs);
    }

    /**
     * UnSetter for CreatedTs.
     * Created Time Stamp
     */
    public void unsetCreatedTs() {
        createdTs = null;
    }

    /**
     * Internal Getter for Model.
     * MOdel
     * @return Returns the Internal String
     */
    @JsonGetter("model")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetModel() {
        return this.model;
    }

    /**
     * Getter for Model.
     * MOdel
     * @return Returns the String
     */
    public String getModel() {
        return OptionalNullable.getFrom(model);
    }

    /**
     * Setter for Model.
     * MOdel
     * @param model Value for String
     */
    @JsonSetter("model")
    public void setModel(String model) {
        this.model = OptionalNullable.of(model);
    }

    /**
     * UnSetter for Model.
     * MOdel
     */
    public void unsetModel() {
        model = null;
    }

    /**
     * Internal Getter for ModelId.
     * Model Id
     * @return Returns the Internal String
     */
    @JsonGetter("model_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetModelId() {
        return this.modelId;
    }

    /**
     * Getter for ModelId.
     * Model Id
     * @return Returns the String
     */
    public String getModelId() {
        return OptionalNullable.getFrom(modelId);
    }

    /**
     * Setter for ModelId.
     * Model Id
     * @param modelId Value for String
     */
    @JsonSetter("model_id")
    public void setModelId(String modelId) {
        this.modelId = OptionalNullable.of(modelId);
    }

    /**
     * UnSetter for ModelId.
     * Model Id
     */
    public void unsetModelId() {
        modelId = null;
    }

    /**
     * Converts this PostbackLog into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PostbackLog [" + "postbackStatusId=" + postbackStatusId + ", id=" + id
                + ", postbackConfigId=" + postbackConfigId + ", changelogId=" + changelogId
                + ", httpVerb=" + httpVerb + ", nextRunTs=" + nextRunTs + ", createdTs=" + createdTs
                + ", model=" + model + ", modelId=" + modelId + ", additionalProperties="
                + getAdditionalProperties() + "]";
    }

    /**
     * Builds a new {@link PostbackLog.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PostbackLog.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .postbackConfigId(getPostbackConfigId())
                .changelogId(getChangelogId());
        builder.postbackStatusId = internalGetPostbackStatusId();
        builder.httpVerb = internalGetHttpVerb();
        builder.nextRunTs = internalGetNextRunTs();
        builder.createdTs = internalGetCreatedTs();
        builder.model = internalGetModel();
        builder.modelId = internalGetModelId();
        return builder;
    }

    /**
     * Class to build instances of {@link PostbackLog}.
     */
    public static class Builder {
        private OptionalNullable<PostbackStatusIdEnum> postbackStatusId;
        private String id;
        private String postbackConfigId;
        private String changelogId;
        private OptionalNullable<String> httpVerb;
        private OptionalNullable<Integer> nextRunTs;
        private OptionalNullable<Integer> createdTs;
        private OptionalNullable<String> model;
        private OptionalNullable<String> modelId;



        /**
         * Setter for postbackStatusId.
         * @param  postbackStatusId  PostbackStatusIdEnum value for postbackStatusId.
         * @return Builder
         */
        public Builder postbackStatusId(PostbackStatusIdEnum postbackStatusId) {
            this.postbackStatusId = OptionalNullable.of(postbackStatusId);
            return this;
        }

        /**
         * UnSetter for postbackStatusId.
         * @return Builder
         */
        public Builder unsetPostbackStatusId() {
            postbackStatusId = null;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for postbackConfigId.
         * @param  postbackConfigId  String value for postbackConfigId.
         * @return Builder
         */
        public Builder postbackConfigId(String postbackConfigId) {
            this.postbackConfigId = postbackConfigId;
            return this;
        }

        /**
         * Setter for changelogId.
         * @param  changelogId  String value for changelogId.
         * @return Builder
         */
        public Builder changelogId(String changelogId) {
            this.changelogId = changelogId;
            return this;
        }

        /**
         * Setter for httpVerb.
         * @param  httpVerb  String value for httpVerb.
         * @return Builder
         */
        public Builder httpVerb(String httpVerb) {
            this.httpVerb = OptionalNullable.of(httpVerb);
            return this;
        }

        /**
         * UnSetter for httpVerb.
         * @return Builder
         */
        public Builder unsetHttpVerb() {
            httpVerb = null;
            return this;
        }

        /**
         * Setter for nextRunTs.
         * @param  nextRunTs  Integer value for nextRunTs.
         * @return Builder
         */
        public Builder nextRunTs(Integer nextRunTs) {
            this.nextRunTs = OptionalNullable.of(nextRunTs);
            return this;
        }

        /**
         * UnSetter for nextRunTs.
         * @return Builder
         */
        public Builder unsetNextRunTs() {
            nextRunTs = null;
            return this;
        }

        /**
         * Setter for createdTs.
         * @param  createdTs  Integer value for createdTs.
         * @return Builder
         */
        public Builder createdTs(Integer createdTs) {
            this.createdTs = OptionalNullable.of(createdTs);
            return this;
        }

        /**
         * UnSetter for createdTs.
         * @return Builder
         */
        public Builder unsetCreatedTs() {
            createdTs = null;
            return this;
        }

        /**
         * Setter for model.
         * @param  model  String value for model.
         * @return Builder
         */
        public Builder model(String model) {
            this.model = OptionalNullable.of(model);
            return this;
        }

        /**
         * UnSetter for model.
         * @return Builder
         */
        public Builder unsetModel() {
            model = null;
            return this;
        }

        /**
         * Setter for modelId.
         * @param  modelId  String value for modelId.
         * @return Builder
         */
        public Builder modelId(String modelId) {
            this.modelId = OptionalNullable.of(modelId);
            return this;
        }

        /**
         * UnSetter for modelId.
         * @return Builder
         */
        public Builder unsetModelId() {
            modelId = null;
            return this;
        }

        /**
         * Builds a new {@link PostbackLog} object using the set fields.
         * @return {@link PostbackLog}
         */
        public PostbackLog build() {
            return new PostbackLog(postbackStatusId, id, postbackConfigId, changelogId, httpVerb,
                    nextRunTs, createdTs, model, modelId);
        }
    }
}
