/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.BaseModel;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for ReceivedEmail type.
 */
public class ReceivedEmail
        extends BaseModel {
    private String subject;
    private String body;
    private String sourceAddress;
    private String returnPath;
    private OptionalNullable<String> providerId;
    private OptionalNullable<String> domainId;
    private OptionalNullable<String> reasonSent;
    private OptionalNullable<ReasonModelEnum> reasonModel;
    private OptionalNullable<String> reasonModelId;
    private OptionalNullable<String> replyTo;
    private String id;
    private Integer createdTs;

    /**
     * Default constructor.
     */
    public ReceivedEmail() {
    }

    /**
     * Initialization constructor.
     * @param  subject  String value for subject.
     * @param  body  String value for body.
     * @param  sourceAddress  String value for sourceAddress.
     * @param  returnPath  String value for returnPath.
     * @param  providerId  String value for providerId.
     * @param  domainId  String value for domainId.
     * @param  reasonSent  String value for reasonSent.
     * @param  reasonModel  ReasonModelEnum value for reasonModel.
     * @param  reasonModelId  String value for reasonModelId.
     * @param  replyTo  String value for replyTo.
     * @param  id  String value for id.
     * @param  createdTs  Integer value for createdTs.
     */
    public ReceivedEmail(
            String subject,
            String body,
            String sourceAddress,
            String returnPath,
            String providerId,
            String domainId,
            String reasonSent,
            ReasonModelEnum reasonModel,
            String reasonModelId,
            String replyTo,
            String id,
            Integer createdTs) {
        this.subject = subject;
        this.body = body;
        this.sourceAddress = sourceAddress;
        this.returnPath = returnPath;
        this.providerId = OptionalNullable.of(providerId);
        this.domainId = OptionalNullable.of(domainId);
        this.reasonSent = OptionalNullable.of(reasonSent);
        this.reasonModel = OptionalNullable.of(reasonModel);
        this.reasonModelId = OptionalNullable.of(reasonModelId);
        this.replyTo = OptionalNullable.of(replyTo);
        this.id = id;
        this.createdTs = createdTs;
    }

    /**
     * Initialization constructor.
     * @param  subject  String value for subject.
     * @param  body  String value for body.
     * @param  sourceAddress  String value for sourceAddress.
     * @param  returnPath  String value for returnPath.
     * @param  providerId  String value for providerId.
     * @param  domainId  String value for domainId.
     * @param  reasonSent  String value for reasonSent.
     * @param  reasonModel  ReasonModelEnum value for reasonModel.
     * @param  reasonModelId  String value for reasonModelId.
     * @param  replyTo  String value for replyTo.
     * @param  id  String value for id.
     * @param  createdTs  Integer value for createdTs.
     */

    protected ReceivedEmail(String subject, String body, String sourceAddress, String returnPath,
            OptionalNullable<String> providerId, OptionalNullable<String> domainId,
            OptionalNullable<String> reasonSent, OptionalNullable<ReasonModelEnum> reasonModel,
            OptionalNullable<String> reasonModelId, OptionalNullable<String> replyTo, String id,
            Integer createdTs) {
        this.subject = subject;
        this.body = body;
        this.sourceAddress = sourceAddress;
        this.returnPath = returnPath;
        this.providerId = providerId;
        this.domainId = domainId;
        this.reasonSent = reasonSent;
        this.reasonModel = reasonModel;
        this.reasonModelId = reasonModelId;
        this.replyTo = replyTo;
        this.id = id;
        this.createdTs = createdTs;
    }

    /**
     * Getter for Subject.
     * Subject
     * @return Returns the String
     */
    @JsonGetter("subject")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSubject() {
        return subject;
    }

    /**
     * Setter for Subject.
     * Subject
     * @param subject Value for String
     */
    @JsonSetter("subject")
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * Getter for Body.
     * Body
     * @return Returns the String
     */
    @JsonGetter("body")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBody() {
        return body;
    }

    /**
     * Setter for Body.
     * Body
     * @param body Value for String
     */
    @JsonSetter("body")
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * Getter for SourceAddress.
     * Source Address
     * @return Returns the String
     */
    @JsonGetter("source_address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSourceAddress() {
        return sourceAddress;
    }

    /**
     * Setter for SourceAddress.
     * Source Address
     * @param sourceAddress Value for String
     */
    @JsonSetter("source_address")
    public void setSourceAddress(String sourceAddress) {
        this.sourceAddress = sourceAddress;
    }

    /**
     * Getter for ReturnPath.
     * Return Path
     * @return Returns the String
     */
    @JsonGetter("return_path")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReturnPath() {
        return returnPath;
    }

    /**
     * Setter for ReturnPath.
     * Return Path
     * @param returnPath Value for String
     */
    @JsonSetter("return_path")
    public void setReturnPath(String returnPath) {
        this.returnPath = returnPath;
    }

    /**
     * Internal Getter for ProviderId.
     * Provider
     * @return Returns the Internal String
     */
    @JsonGetter("provider_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetProviderId() {
        return this.providerId;
    }

    /**
     * Getter for ProviderId.
     * Provider
     * @return Returns the String
     */
    public String getProviderId() {
        return OptionalNullable.getFrom(providerId);
    }

    /**
     * Setter for ProviderId.
     * Provider
     * @param providerId Value for String
     */
    @JsonSetter("provider_id")
    public void setProviderId(String providerId) {
        this.providerId = OptionalNullable.of(providerId);
    }

    /**
     * UnSetter for ProviderId.
     * Provider
     */
    public void unsetProviderId() {
        providerId = null;
    }

    /**
     * Internal Getter for DomainId.
     * Domain
     * @return Returns the Internal String
     */
    @JsonGetter("domain_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDomainId() {
        return this.domainId;
    }

    /**
     * Getter for DomainId.
     * Domain
     * @return Returns the String
     */
    public String getDomainId() {
        return OptionalNullable.getFrom(domainId);
    }

    /**
     * Setter for DomainId.
     * Domain
     * @param domainId Value for String
     */
    @JsonSetter("domain_id")
    public void setDomainId(String domainId) {
        this.domainId = OptionalNullable.of(domainId);
    }

    /**
     * UnSetter for DomainId.
     * Domain
     */
    public void unsetDomainId() {
        domainId = null;
    }

    /**
     * Internal Getter for ReasonSent.
     * Reason Sent
     * @return Returns the Internal String
     */
    @JsonGetter("reason_sent")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetReasonSent() {
        return this.reasonSent;
    }

    /**
     * Getter for ReasonSent.
     * Reason Sent
     * @return Returns the String
     */
    public String getReasonSent() {
        return OptionalNullable.getFrom(reasonSent);
    }

    /**
     * Setter for ReasonSent.
     * Reason Sent
     * @param reasonSent Value for String
     */
    @JsonSetter("reason_sent")
    public void setReasonSent(String reasonSent) {
        this.reasonSent = OptionalNullable.of(reasonSent);
    }

    /**
     * UnSetter for ReasonSent.
     * Reason Sent
     */
    public void unsetReasonSent() {
        reasonSent = null;
    }

    /**
     * Internal Getter for ReasonModel.
     * Reason Model
     * @return Returns the Internal ReasonModelEnum
     */
    @JsonGetter("reason_model")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<ReasonModelEnum> internalGetReasonModel() {
        return this.reasonModel;
    }

    /**
     * Getter for ReasonModel.
     * Reason Model
     * @return Returns the ReasonModelEnum
     */
    public ReasonModelEnum getReasonModel() {
        return OptionalNullable.getFrom(reasonModel);
    }

    /**
     * Setter for ReasonModel.
     * Reason Model
     * @param reasonModel Value for ReasonModelEnum
     */
    @JsonSetter("reason_model")
    public void setReasonModel(ReasonModelEnum reasonModel) {
        this.reasonModel = OptionalNullable.of(reasonModel);
    }

    /**
     * UnSetter for ReasonModel.
     * Reason Model
     */
    public void unsetReasonModel() {
        reasonModel = null;
    }

    /**
     * Internal Getter for ReasonModelId.
     * Reason Model
     * @return Returns the Internal String
     */
    @JsonGetter("reason_model_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetReasonModelId() {
        return this.reasonModelId;
    }

    /**
     * Getter for ReasonModelId.
     * Reason Model
     * @return Returns the String
     */
    public String getReasonModelId() {
        return OptionalNullable.getFrom(reasonModelId);
    }

    /**
     * Setter for ReasonModelId.
     * Reason Model
     * @param reasonModelId Value for String
     */
    @JsonSetter("reason_model_id")
    public void setReasonModelId(String reasonModelId) {
        this.reasonModelId = OptionalNullable.of(reasonModelId);
    }

    /**
     * UnSetter for ReasonModelId.
     * Reason Model
     */
    public void unsetReasonModelId() {
        reasonModelId = null;
    }

    /**
     * Internal Getter for ReplyTo.
     * Reply To
     * @return Returns the Internal String
     */
    @JsonGetter("reply_to")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetReplyTo() {
        return this.replyTo;
    }

    /**
     * Getter for ReplyTo.
     * Reply To
     * @return Returns the String
     */
    public String getReplyTo() {
        return OptionalNullable.getFrom(replyTo);
    }

    /**
     * Setter for ReplyTo.
     * Reply To
     * @param replyTo Value for String
     */
    @JsonSetter("reply_to")
    public void setReplyTo(String replyTo) {
        this.replyTo = OptionalNullable.of(replyTo);
    }

    /**
     * UnSetter for ReplyTo.
     * Reply To
     */
    public void unsetReplyTo() {
        replyTo = null;
    }

    /**
     * Getter for Id.
     * Log Email Id
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Log Email Id
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for CreatedTs.
     * Created Time Stamp
     * @return Returns the Integer
     */
    @JsonGetter("created_ts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCreatedTs() {
        return createdTs;
    }

    /**
     * Setter for CreatedTs.
     * Created Time Stamp
     * @param createdTs Value for Integer
     */
    @JsonSetter("created_ts")
    public void setCreatedTs(Integer createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * Converts this ReceivedEmail into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ReceivedEmail [" + "subject=" + subject + ", body=" + body + ", sourceAddress="
                + sourceAddress + ", returnPath=" + returnPath + ", providerId=" + providerId
                + ", domainId=" + domainId + ", reasonSent=" + reasonSent + ", reasonModel="
                + reasonModel + ", reasonModelId=" + reasonModelId + ", replyTo=" + replyTo
                + ", id=" + id + ", createdTs=" + createdTs + ", additionalProperties="
                + getAdditionalProperties() + "]";
    }

    /**
     * Builds a new {@link ReceivedEmail.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ReceivedEmail.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .subject(getSubject())
                .body(getBody())
                .sourceAddress(getSourceAddress())
                .returnPath(getReturnPath())
                .id(getId())
                .createdTs(getCreatedTs());
        builder.providerId = internalGetProviderId();
        builder.domainId = internalGetDomainId();
        builder.reasonSent = internalGetReasonSent();
        builder.reasonModel = internalGetReasonModel();
        builder.reasonModelId = internalGetReasonModelId();
        builder.replyTo = internalGetReplyTo();
        return builder;
    }

    /**
     * Class to build instances of {@link ReceivedEmail}.
     */
    public static class Builder {
        private String subject;
        private String body;
        private String sourceAddress;
        private String returnPath;
        private OptionalNullable<String> providerId;
        private OptionalNullable<String> domainId;
        private OptionalNullable<String> reasonSent;
        private OptionalNullable<ReasonModelEnum> reasonModel;
        private OptionalNullable<String> reasonModelId;
        private OptionalNullable<String> replyTo;
        private String id;
        private Integer createdTs;



        /**
         * Setter for subject.
         * @param  subject  String value for subject.
         * @return Builder
         */
        public Builder subject(String subject) {
            this.subject = subject;
            return this;
        }

        /**
         * Setter for body.
         * @param  body  String value for body.
         * @return Builder
         */
        public Builder body(String body) {
            this.body = body;
            return this;
        }

        /**
         * Setter for sourceAddress.
         * @param  sourceAddress  String value for sourceAddress.
         * @return Builder
         */
        public Builder sourceAddress(String sourceAddress) {
            this.sourceAddress = sourceAddress;
            return this;
        }

        /**
         * Setter for returnPath.
         * @param  returnPath  String value for returnPath.
         * @return Builder
         */
        public Builder returnPath(String returnPath) {
            this.returnPath = returnPath;
            return this;
        }

        /**
         * Setter for providerId.
         * @param  providerId  String value for providerId.
         * @return Builder
         */
        public Builder providerId(String providerId) {
            this.providerId = OptionalNullable.of(providerId);
            return this;
        }

        /**
         * UnSetter for providerId.
         * @return Builder
         */
        public Builder unsetProviderId() {
            providerId = null;
            return this;
        }

        /**
         * Setter for domainId.
         * @param  domainId  String value for domainId.
         * @return Builder
         */
        public Builder domainId(String domainId) {
            this.domainId = OptionalNullable.of(domainId);
            return this;
        }

        /**
         * UnSetter for domainId.
         * @return Builder
         */
        public Builder unsetDomainId() {
            domainId = null;
            return this;
        }

        /**
         * Setter for reasonSent.
         * @param  reasonSent  String value for reasonSent.
         * @return Builder
         */
        public Builder reasonSent(String reasonSent) {
            this.reasonSent = OptionalNullable.of(reasonSent);
            return this;
        }

        /**
         * UnSetter for reasonSent.
         * @return Builder
         */
        public Builder unsetReasonSent() {
            reasonSent = null;
            return this;
        }

        /**
         * Setter for reasonModel.
         * @param  reasonModel  ReasonModelEnum value for reasonModel.
         * @return Builder
         */
        public Builder reasonModel(ReasonModelEnum reasonModel) {
            this.reasonModel = OptionalNullable.of(reasonModel);
            return this;
        }

        /**
         * UnSetter for reasonModel.
         * @return Builder
         */
        public Builder unsetReasonModel() {
            reasonModel = null;
            return this;
        }

        /**
         * Setter for reasonModelId.
         * @param  reasonModelId  String value for reasonModelId.
         * @return Builder
         */
        public Builder reasonModelId(String reasonModelId) {
            this.reasonModelId = OptionalNullable.of(reasonModelId);
            return this;
        }

        /**
         * UnSetter for reasonModelId.
         * @return Builder
         */
        public Builder unsetReasonModelId() {
            reasonModelId = null;
            return this;
        }

        /**
         * Setter for replyTo.
         * @param  replyTo  String value for replyTo.
         * @return Builder
         */
        public Builder replyTo(String replyTo) {
            this.replyTo = OptionalNullable.of(replyTo);
            return this;
        }

        /**
         * UnSetter for replyTo.
         * @return Builder
         */
        public Builder unsetReplyTo() {
            replyTo = null;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for createdTs.
         * @param  createdTs  Integer value for createdTs.
         * @return Builder
         */
        public Builder createdTs(Integer createdTs) {
            this.createdTs = createdTs;
            return this;
        }

        /**
         * Builds a new {@link ReceivedEmail} object using the set fields.
         * @return {@link ReceivedEmail}
         */
        public ReceivedEmail build() {
            return new ReceivedEmail(subject, body, sourceAddress, returnPath, providerId, domainId,
                    reasonSent, reasonModel, reasonModelId, replyTo, id, createdTs);
        }
    }
}
