/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for ResponseDeclinedRecurringTransactionsCollection type.
 */
public class ResponseDeclinedRecurringTransactionsCollection
        extends BaseModel {
    private Type16Enum type;
    private List<List3> list;
    private Links links;
    private Pagination pagination;
    private Sort sort;

    /**
     * Default constructor.
     */
    public ResponseDeclinedRecurringTransactionsCollection() {
        type = Type16Enum.DECLINEDRECURRINGTRANSACTIONSCOLLECTION;
    }

    /**
     * Initialization constructor.
     * @param  type  Type16Enum value for type.
     * @param  list  List of List3 value for list.
     * @param  links  Links value for links.
     * @param  pagination  Pagination value for pagination.
     * @param  sort  Sort value for sort.
     */
    public ResponseDeclinedRecurringTransactionsCollection(
            Type16Enum type,
            List<List3> list,
            Links links,
            Pagination pagination,
            Sort sort) {
        this.type = type;
        this.list = list;
        this.links = links;
        this.pagination = pagination;
        this.sort = sort;
    }

    /**
     * Getter for Type.
     * Resource Type
     * @return Returns the Type16Enum
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Type16Enum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Resource Type
     * @param type Value for Type16Enum
     */
    @JsonSetter("type")
    public void setType(Type16Enum type) {
        this.type = type;
    }

    /**
     * Getter for List.
     * Resource Members
     * @return Returns the List of List3
     */
    @JsonGetter("list")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<List3> getList() {
        return list;
    }

    /**
     * Setter for List.
     * Resource Members
     * @param list Value for List of List3
     */
    @JsonSetter("list")
    public void setList(List<List3> list) {
        this.list = list;
    }

    /**
     * Getter for Links.
     * Pagination page links
     * @return Returns the Links
     */
    @JsonGetter("links")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Links getLinks() {
        return links;
    }

    /**
     * Setter for Links.
     * Pagination page links
     * @param links Value for Links
     */
    @JsonSetter("links")
    public void setLinks(Links links) {
        this.links = links;
    }

    /**
     * Getter for Pagination.
     * Pagination info
     * @return Returns the Pagination
     */
    @JsonGetter("pagination")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Setter for Pagination.
     * Pagination info
     * @param pagination Value for Pagination
     */
    @JsonSetter("pagination")
    public void setPagination(Pagination pagination) {
        this.pagination = pagination;
    }

    /**
     * Getter for Sort.
     * Sort information used on the results
     * @return Returns the Sort
     */
    @JsonGetter("sort")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Sort getSort() {
        return sort;
    }

    /**
     * Setter for Sort.
     * Sort information used on the results
     * @param sort Value for Sort
     */
    @JsonSetter("sort")
    public void setSort(Sort sort) {
        this.sort = sort;
    }

    /**
     * Converts this ResponseDeclinedRecurringTransactionsCollection into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResponseDeclinedRecurringTransactionsCollection [" + "type=" + type + ", list="
                + list + ", links=" + links + ", pagination=" + pagination + ", sort=" + sort
                + ", additionalProperties=" + getAdditionalProperties() + "]";
    }

    /**
     * Builds a new {@link ResponseDeclinedRecurringTransactionsCollection.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResponseDeclinedRecurringTransactionsCollection.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .type(getType())
                .list(getList())
                .links(getLinks())
                .pagination(getPagination())
                .sort(getSort());
        return builder;
    }

    /**
     * Class to build instances of {@link ResponseDeclinedRecurringTransactionsCollection}.
     */
    public static class Builder {
        private Type16Enum type = Type16Enum.DECLINEDRECURRINGTRANSACTIONSCOLLECTION;
        private List<List3> list;
        private Links links;
        private Pagination pagination;
        private Sort sort;



        /**
         * Setter for type.
         * @param  type  Type16Enum value for type.
         * @return Builder
         */
        public Builder type(Type16Enum type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for list.
         * @param  list  List of List3 value for list.
         * @return Builder
         */
        public Builder list(List<List3> list) {
            this.list = list;
            return this;
        }

        /**
         * Setter for links.
         * @param  links  Links value for links.
         * @return Builder
         */
        public Builder links(Links links) {
            this.links = links;
            return this;
        }

        /**
         * Setter for pagination.
         * @param  pagination  Pagination value for pagination.
         * @return Builder
         */
        public Builder pagination(Pagination pagination) {
            this.pagination = pagination;
            return this;
        }

        /**
         * Setter for sort.
         * @param  sort  Sort value for sort.
         * @return Builder
         */
        public Builder sort(Sort sort) {
            this.sort = sort;
            return this;
        }

        /**
         * Builds a new {@link ResponseDeclinedRecurringTransactionsCollection} object using the set
         * fields.
         * @return {@link ResponseDeclinedRecurringTransactionsCollection}
         */
        public ResponseDeclinedRecurringTransactionsCollection build() {
            return new ResponseDeclinedRecurringTransactionsCollection(type, list, links,
                    pagination, sort);
        }
    }
}
