/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ResponseTicket type.
 */
public class ResponseTicket {
    private Type87 type;
    private Data24 data;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ResponseTicket() {
    }

    /**
     * Initialization constructor.
     * @param  type  Type87 value for type.
     * @param  data  Data24 value for data.
     */
    public ResponseTicket(
            Type87 type,
            Data24 data) {
        this.type = type;
        this.data = data;
    }

    /**
     * Getter for Type.
     * @return Returns the Type87
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Type87 getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for Type87
     */
    @JsonSetter("type")
    public void setType(Type87 type) {
        this.type = type;
    }

    /**
     * Getter for Data.
     * @return Returns the Data24
     */
    @JsonGetter("data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data24 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data24
     */
    @JsonSetter("data")
    public void setData(Data24 data) {
        this.data = data;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ResponseTicket into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResponseTicket [" + "type=" + type + ", data=" + data + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ResponseTicket.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResponseTicket.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .type(getType())
                .data(getData());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ResponseTicket}.
     */
    public static class Builder {
        private Type87 type;
        private Data24 data;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for type.
         * @param  type  Type87 value for type.
         * @return Builder
         */
        public Builder type(Type87 type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  Data24 value for data.
         * @return Builder
         */
        public Builder data(Data24 data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ResponseTicket} object using the set fields.
         * @return {@link ResponseTicket}
         */
        public ResponseTicket build() {
            ResponseTicket model =
                    new ResponseTicket(type, data);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
