/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ResponseSignature type.
 */
public class ResponseSignature {
    private Type72 type;
    private Data21 data;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ResponseSignature() {
    }

    /**
     * Initialization constructor.
     * @param  type  Type72 value for type.
     * @param  data  Data21 value for data.
     */
    public ResponseSignature(
            Type72 type,
            Data21 data) {
        this.type = type;
        this.data = data;
    }

    /**
     * Getter for Type.
     * @return Returns the Type72
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Type72 getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for Type72
     */
    @JsonSetter("type")
    public void setType(Type72 type) {
        this.type = type;
    }

    /**
     * Getter for Data.
     * @return Returns the Data21
     */
    @JsonGetter("data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data21 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data21
     */
    @JsonSetter("data")
    public void setData(Data21 data) {
        this.data = data;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ResponseSignature into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResponseSignature [" + "type=" + type + ", data=" + data + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ResponseSignature.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResponseSignature.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .type(getType())
                .data(getData());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ResponseSignature}.
     */
    public static class Builder {
        private Type72 type;
        private Data21 data;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for type.
         * @param  type  Type72 value for type.
         * @return Builder
         */
        public Builder type(Type72 type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  Data21 value for data.
         * @return Builder
         */
        public Builder data(Data21 data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ResponseSignature} object using the set fields.
         * @return {@link ResponseSignature}
         */
        public ResponseSignature build() {
            ResponseSignature model =
                    new ResponseSignature(type, data);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
