/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for ResponseOnboarding type.
 */
public class ResponseOnboarding
        extends BaseModel {
    private Type52Enum type;
    private Data15 data;

    /**
     * Default constructor.
     */
    public ResponseOnboarding() {
        type = Type52Enum.ONBOARDING;
    }

    /**
     * Initialization constructor.
     * @param  type  Type52Enum value for type.
     * @param  data  Data15 value for data.
     */
    public ResponseOnboarding(
            Type52Enum type,
            Data15 data) {
        this.type = type;
        this.data = data;
    }

    /**
     * Getter for Type.
     * Resource Type
     * @return Returns the Type52Enum
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Type52Enum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Resource Type
     * @param type Value for Type52Enum
     */
    @JsonSetter("type")
    public void setType(Type52Enum type) {
        this.type = type;
    }

    /**
     * Getter for Data.
     * @return Returns the Data15
     */
    @JsonGetter("data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data15 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data15
     */
    @JsonSetter("data")
    public void setData(Data15 data) {
        this.data = data;
    }

    /**
     * Converts this ResponseOnboarding into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResponseOnboarding [" + "type=" + type + ", data=" + data
                + ", additionalProperties=" + getAdditionalProperties() + "]";
    }

    /**
     * Builds a new {@link ResponseOnboarding.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResponseOnboarding.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .type(getType())
                .data(getData());
        return builder;
    }

    /**
     * Class to build instances of {@link ResponseOnboarding}.
     */
    public static class Builder {
        private Type52Enum type = Type52Enum.ONBOARDING;
        private Data15 data;



        /**
         * Setter for type.
         * @param  type  Type52Enum value for type.
         * @return Builder
         */
        public Builder type(Type52Enum type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  Data15 value for data.
         * @return Builder
         */
        public Builder data(Data15 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link ResponseOnboarding} object using the set fields.
         * @return {@link ResponseOnboarding}
         */
        public ResponseOnboarding build() {
            return new ResponseOnboarding(type, data);
        }
    }
}
