/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ResponseError type.
 */
public class ResponseError {
    private String type;
    private String id;
    private Integer statusCode;
    private String title;
    private Detail12 detail;
    private Object meta;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ResponseError() {
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  id  String value for id.
     * @param  statusCode  Integer value for statusCode.
     * @param  title  String value for title.
     * @param  detail  Detail12 value for detail.
     * @param  meta  Object value for meta.
     */
    public ResponseError(
            String type,
            String id,
            Integer statusCode,
            String title,
            Detail12 detail,
            Object meta) {
        this.type = type;
        this.id = id;
        this.statusCode = statusCode;
        this.title = title;
        this.detail = detail;
        this.meta = meta;
    }

    /**
     * Getter for Type.
     * Message type
     * @return Returns the String
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Message type
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Id.
     * Unique identifier for this API call
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique identifier for this API call
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for StatusCode.
     * HTTP status code
     * @return Returns the Integer
     */
    @JsonGetter("statusCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getStatusCode() {
        return statusCode;
    }

    /**
     * Setter for StatusCode.
     * HTTP status code
     * @param statusCode Value for Integer
     */
    @JsonSetter("statusCode")
    public void setStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
    }

    /**
     * Getter for Title.
     * Error title
     * @return Returns the String
     */
    @JsonGetter("title")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * Error title
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for Detail.
     * @return Returns the Detail12
     */
    @JsonGetter("detail")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Detail12 getDetail() {
        return detail;
    }

    /**
     * Setter for Detail.
     * @param detail Value for Detail12
     */
    @JsonSetter("detail")
    public void setDetail(Detail12 detail) {
        this.detail = detail;
    }

    /**
     * Getter for Meta.
     * Object with additional error details
     * @return Returns the Object
     */
    @JsonGetter("meta")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getMeta() {
        return meta;
    }

    /**
     * Setter for Meta.
     * Object with additional error details
     * @param meta Value for Object
     */
    @JsonSetter("meta")
    public void setMeta(Object meta) {
        this.meta = meta;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ResponseError into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResponseError [" + "type=" + type + ", id=" + id + ", statusCode=" + statusCode
                + ", title=" + title + ", detail=" + detail + ", meta=" + meta
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ResponseError.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResponseError.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .type(getType())
                .id(getId())
                .statusCode(getStatusCode())
                .title(getTitle())
                .detail(getDetail())
                .meta(getMeta());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ResponseError}.
     */
    public static class Builder {
        private String type;
        private String id;
        private Integer statusCode;
        private String title;
        private Detail12 detail;
        private Object meta;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for statusCode.
         * @param  statusCode  Integer value for statusCode.
         * @return Builder
         */
        public Builder statusCode(Integer statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for detail.
         * @param  detail  Detail12 value for detail.
         * @return Builder
         */
        public Builder detail(Detail12 detail) {
            this.detail = detail;
            return this;
        }

        /**
         * Setter for meta.
         * @param  meta  Object value for meta.
         * @return Builder
         */
        public Builder meta(Object meta) {
            this.meta = meta;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ResponseError} object using the set fields.
         * @return {@link ResponseError}
         */
        public ResponseError build() {
            ResponseError model =
                    new ResponseError(type, id, statusCode, title, detail, meta);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
