/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ThreeDsRequestor type.
 */
public class ThreeDsRequestor {
    private ThreeDsRequestorAuthenticationInd threeDsRequestorAuthenticationInd;
    private List<ThreeDsRequestorAuthenticationInfo> threeDsRequestorAuthenticationInfo;
    private List<ThreeDsRequestorChallengeInd> threeDsRequestorChallengeInd;
    private List<ThreeDsRequestorPriorAuthenticationInfo> threeDsRequestorPriorAuthenticationInfo;
    private ThreeDsRequestorDecReqInd threeDsRequestorDecReqInd;
    private Integer threeDsRequestorDecMaxTime;
    private ThreeDsRequestorSpcSupport threeDsRequestorSpcSupport;
    private String spcIncompInd;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ThreeDsRequestor() {
    }

    /**
     * Initialization constructor.
     * @param  threeDsRequestorAuthenticationInd  ThreeDsRequestorAuthenticationInd value for
     *         threeDsRequestorAuthenticationInd.
     * @param  threeDsRequestorAuthenticationInfo  List of ThreeDsRequestorAuthenticationInfo value
     *         for threeDsRequestorAuthenticationInfo.
     * @param  threeDsRequestorChallengeInd  List of ThreeDsRequestorChallengeInd value for
     *         threeDsRequestorChallengeInd.
     * @param  threeDsRequestorPriorAuthenticationInfo  List of
     *         ThreeDsRequestorPriorAuthenticationInfo value for
     *         threeDsRequestorPriorAuthenticationInfo.
     * @param  threeDsRequestorDecReqInd  ThreeDsRequestorDecReqInd value for
     *         threeDsRequestorDecReqInd.
     * @param  threeDsRequestorDecMaxTime  Integer value for threeDsRequestorDecMaxTime.
     * @param  threeDsRequestorSpcSupport  ThreeDsRequestorSpcSupport value for
     *         threeDsRequestorSpcSupport.
     * @param  spcIncompInd  String value for spcIncompInd.
     */
    public ThreeDsRequestor(
            ThreeDsRequestorAuthenticationInd threeDsRequestorAuthenticationInd,
            List<ThreeDsRequestorAuthenticationInfo> threeDsRequestorAuthenticationInfo,
            List<ThreeDsRequestorChallengeInd> threeDsRequestorChallengeInd,
            List<ThreeDsRequestorPriorAuthenticationInfo> threeDsRequestorPriorAuthenticationInfo,
            ThreeDsRequestorDecReqInd threeDsRequestorDecReqInd,
            Integer threeDsRequestorDecMaxTime,
            ThreeDsRequestorSpcSupport threeDsRequestorSpcSupport,
            String spcIncompInd) {
        this.threeDsRequestorAuthenticationInd = threeDsRequestorAuthenticationInd;
        this.threeDsRequestorAuthenticationInfo = threeDsRequestorAuthenticationInfo;
        this.threeDsRequestorChallengeInd = threeDsRequestorChallengeInd;
        this.threeDsRequestorPriorAuthenticationInfo = threeDsRequestorPriorAuthenticationInfo;
        this.threeDsRequestorDecReqInd = threeDsRequestorDecReqInd;
        this.threeDsRequestorDecMaxTime = threeDsRequestorDecMaxTime;
        this.threeDsRequestorSpcSupport = threeDsRequestorSpcSupport;
        this.spcIncompInd = spcIncompInd;
    }

    /**
     * Getter for ThreeDsRequestorAuthenticationInd.
     * @return Returns the ThreeDsRequestorAuthenticationInd
     */
    @JsonGetter("three_ds_requestor_authentication_ind")
    public ThreeDsRequestorAuthenticationInd getThreeDsRequestorAuthenticationInd() {
        return threeDsRequestorAuthenticationInd;
    }

    /**
     * Setter for ThreeDsRequestorAuthenticationInd.
     * @param threeDsRequestorAuthenticationInd Value for ThreeDsRequestorAuthenticationInd
     */
    @JsonSetter("three_ds_requestor_authentication_ind")
    public void setThreeDsRequestorAuthenticationInd(ThreeDsRequestorAuthenticationInd threeDsRequestorAuthenticationInd) {
        this.threeDsRequestorAuthenticationInd = threeDsRequestorAuthenticationInd;
    }

    /**
     * Getter for ThreeDsRequestorAuthenticationInfo.
     * Information about how the 3DS Requestor authenticated the cardholder before or during the
     * transaction.
     * @return Returns the List of ThreeDsRequestorAuthenticationInfo
     */
    @JsonGetter("three_ds_requestor_authentication_info")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ThreeDsRequestorAuthenticationInfo> getThreeDsRequestorAuthenticationInfo() {
        return threeDsRequestorAuthenticationInfo;
    }

    /**
     * Setter for ThreeDsRequestorAuthenticationInfo.
     * Information about how the 3DS Requestor authenticated the cardholder before or during the
     * transaction.
     * @param threeDsRequestorAuthenticationInfo Value for List of ThreeDsRequestorAuthenticationInfo
     */
    @JsonSetter("three_ds_requestor_authentication_info")
    public void setThreeDsRequestorAuthenticationInfo(List<ThreeDsRequestorAuthenticationInfo> threeDsRequestorAuthenticationInfo) {
        this.threeDsRequestorAuthenticationInfo = threeDsRequestorAuthenticationInfo;
    }

    /**
     * Getter for ThreeDsRequestorChallengeInd.
     * Indicates whether a challenge is requested for this transaction. For example: For 01-PA, a
     * 3DS Requestor may have concerns about the transaction, and request a challenge. For 02-NPA, a
     * challenge may be necessary when adding a new card to a wallet. Values "05" through "09" are
     * accepted as well if 3DS Server initiates authentication with EMV 3DS 2.2.0 version or greater
     * (required protocol version can be set in the preferred_protocol_version field). If the
     * element is not provided, the expected action is that the ACS would interpret as 01 (No
     * preference). In versions prior to 2.3.1 only a single element is supported. Starting from
     * EMVCo version 2.3.1, this array can now support 1-2 elements. When providing two preferences,
     * you must ensure that they are in preference order and are not conflicting. For example, 02 =
     * No challenge requested and 04 = Challenge requested (Mandate). &gt;01 - No preference &gt; &gt;02 - No
     * challenge requested &gt; &gt;03 - Challenge requested: 3DS Requestor Preference &gt; &gt;04 - Challenge
     * requested: Mandate &gt; &gt;05 - No challenge requested (transactional risk analysis is already
     * performed) (EMV 3DS 2.2.0 version or greater) &gt; &gt;06 - No challenge requested (Data share
     * only) (EMV 3DS 2.2.0 version or greater) &gt; &gt;07 - No challenge requested (strong consumer
     * authentication is already performed) (EMV 3DS 2.2.0 version or greater) &gt; &gt;08 - No challenge
     * requested (utilise whitelist exemption if no challenge required) (EMV 3DS 2.2.0 version or
     * greater) &gt; &gt;09 - Challenge requested (whitelist prompt requested if challenge required) (EMV
     * 3DS 2.2.0 version or greater) &gt; &gt;80 through 99 - can be used for PS-specific values,
     * regardless of protocol version &gt;
     * @return Returns the List of ThreeDsRequestorChallengeInd
     */
    @JsonGetter("three_ds_requestor_challenge_ind")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ThreeDsRequestorChallengeInd> getThreeDsRequestorChallengeInd() {
        return threeDsRequestorChallengeInd;
    }

    /**
     * Setter for ThreeDsRequestorChallengeInd.
     * Indicates whether a challenge is requested for this transaction. For example: For 01-PA, a
     * 3DS Requestor may have concerns about the transaction, and request a challenge. For 02-NPA, a
     * challenge may be necessary when adding a new card to a wallet. Values "05" through "09" are
     * accepted as well if 3DS Server initiates authentication with EMV 3DS 2.2.0 version or greater
     * (required protocol version can be set in the preferred_protocol_version field). If the
     * element is not provided, the expected action is that the ACS would interpret as 01 (No
     * preference). In versions prior to 2.3.1 only a single element is supported. Starting from
     * EMVCo version 2.3.1, this array can now support 1-2 elements. When providing two preferences,
     * you must ensure that they are in preference order and are not conflicting. For example, 02 =
     * No challenge requested and 04 = Challenge requested (Mandate). &gt;01 - No preference &gt; &gt;02 - No
     * challenge requested &gt; &gt;03 - Challenge requested: 3DS Requestor Preference &gt; &gt;04 - Challenge
     * requested: Mandate &gt; &gt;05 - No challenge requested (transactional risk analysis is already
     * performed) (EMV 3DS 2.2.0 version or greater) &gt; &gt;06 - No challenge requested (Data share
     * only) (EMV 3DS 2.2.0 version or greater) &gt; &gt;07 - No challenge requested (strong consumer
     * authentication is already performed) (EMV 3DS 2.2.0 version or greater) &gt; &gt;08 - No challenge
     * requested (utilise whitelist exemption if no challenge required) (EMV 3DS 2.2.0 version or
     * greater) &gt; &gt;09 - Challenge requested (whitelist prompt requested if challenge required) (EMV
     * 3DS 2.2.0 version or greater) &gt; &gt;80 through 99 - can be used for PS-specific values,
     * regardless of protocol version &gt;
     * @param threeDsRequestorChallengeInd Value for List of ThreeDsRequestorChallengeInd
     */
    @JsonSetter("three_ds_requestor_challenge_ind")
    public void setThreeDsRequestorChallengeInd(List<ThreeDsRequestorChallengeInd> threeDsRequestorChallengeInd) {
        this.threeDsRequestorChallengeInd = threeDsRequestorChallengeInd;
    }

    /**
     * Getter for ThreeDsRequestorPriorAuthenticationInfo.
     * This object contains information about how the 3DS Requestor authenticated the cardholder as
     * part of a previous 3DS transaction. In versions prior to 2.3.1, this array is limited to a
     * size of 1. Starting from EMVCo version 2.3.1 this array size may be 1-3. This field is
     * optional, but recommended to include for versions prior to 2.3.1. From 2.3.1, it is required
     * for 3RI in the case of Decoupled Authentication Fallback or for SPC.
     * @return Returns the List of ThreeDsRequestorPriorAuthenticationInfo
     */
    @JsonGetter("three_ds_requestor_prior_authentication_info")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ThreeDsRequestorPriorAuthenticationInfo> getThreeDsRequestorPriorAuthenticationInfo() {
        return threeDsRequestorPriorAuthenticationInfo;
    }

    /**
     * Setter for ThreeDsRequestorPriorAuthenticationInfo.
     * This object contains information about how the 3DS Requestor authenticated the cardholder as
     * part of a previous 3DS transaction. In versions prior to 2.3.1, this array is limited to a
     * size of 1. Starting from EMVCo version 2.3.1 this array size may be 1-3. This field is
     * optional, but recommended to include for versions prior to 2.3.1. From 2.3.1, it is required
     * for 3RI in the case of Decoupled Authentication Fallback or for SPC.
     * @param threeDsRequestorPriorAuthenticationInfo Value for List of ThreeDsRequestorPriorAuthenticationInfo
     */
    @JsonSetter("three_ds_requestor_prior_authentication_info")
    public void setThreeDsRequestorPriorAuthenticationInfo(List<ThreeDsRequestorPriorAuthenticationInfo> threeDsRequestorPriorAuthenticationInfo) {
        this.threeDsRequestorPriorAuthenticationInfo = threeDsRequestorPriorAuthenticationInfo;
    }

    /**
     * Getter for ThreeDsRequestorDecReqInd.
     * @return Returns the ThreeDsRequestorDecReqInd
     */
    @JsonGetter("three_ds_requestor_dec_req_ind")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ThreeDsRequestorDecReqInd getThreeDsRequestorDecReqInd() {
        return threeDsRequestorDecReqInd;
    }

    /**
     * Setter for ThreeDsRequestorDecReqInd.
     * @param threeDsRequestorDecReqInd Value for ThreeDsRequestorDecReqInd
     */
    @JsonSetter("three_ds_requestor_dec_req_ind")
    public void setThreeDsRequestorDecReqInd(ThreeDsRequestorDecReqInd threeDsRequestorDecReqInd) {
        this.threeDsRequestorDecReqInd = threeDsRequestorDecReqInd;
    }

    /**
     * Getter for ThreeDsRequestorDecMaxTime.
     * Indicates the maximum amount of time that the 3DS Requestor will wait for an ACS to provide
     * the results of a Decoupled Authentication transaction (in minutes). Valid values are between
     * 1 and 10080. The field is optional and if value is not present, the expected action is for
     * the ACS to interpret it as 10080 minutes (7 days). Available for supporting EMV 3DS 2.2.0 and
     * later versions. Starting from EMV 3DS 2.3.1: This field is required if
     * three_ds_requestor_dec_req_ind = Y, F or B
     * @return Returns the Integer
     */
    @JsonGetter("three_ds_requestor_dec_max_time")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getThreeDsRequestorDecMaxTime() {
        return threeDsRequestorDecMaxTime;
    }

    /**
     * Setter for ThreeDsRequestorDecMaxTime.
     * Indicates the maximum amount of time that the 3DS Requestor will wait for an ACS to provide
     * the results of a Decoupled Authentication transaction (in minutes). Valid values are between
     * 1 and 10080. The field is optional and if value is not present, the expected action is for
     * the ACS to interpret it as 10080 minutes (7 days). Available for supporting EMV 3DS 2.2.0 and
     * later versions. Starting from EMV 3DS 2.3.1: This field is required if
     * three_ds_requestor_dec_req_ind = Y, F or B
     * @param threeDsRequestorDecMaxTime Value for Integer
     */
    @JsonSetter("three_ds_requestor_dec_max_time")
    public void setThreeDsRequestorDecMaxTime(Integer threeDsRequestorDecMaxTime) {
        this.threeDsRequestorDecMaxTime = threeDsRequestorDecMaxTime;
    }

    /**
     * Getter for ThreeDsRequestorSpcSupport.
     * @return Returns the ThreeDsRequestorSpcSupport
     */
    @JsonGetter("three_ds_requestor_spc_support")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ThreeDsRequestorSpcSupport getThreeDsRequestorSpcSupport() {
        return threeDsRequestorSpcSupport;
    }

    /**
     * Setter for ThreeDsRequestorSpcSupport.
     * @param threeDsRequestorSpcSupport Value for ThreeDsRequestorSpcSupport
     */
    @JsonSetter("three_ds_requestor_spc_support")
    public void setThreeDsRequestorSpcSupport(ThreeDsRequestorSpcSupport threeDsRequestorSpcSupport) {
        this.threeDsRequestorSpcSupport = threeDsRequestorSpcSupport;
    }

    /**
     * Getter for SpcIncompInd.
     * Reason that the SPC authentication was not completed. This field is required if
     * device_channel = 02 (BRW) and the 3DS Requestor attempts to invoke SPC API and there is an
     * error. Available for supporting EMV 3DS 2.3.1 and later versions.
     * @return Returns the String
     */
    @JsonGetter("spc_incomp_ind")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSpcIncompInd() {
        return spcIncompInd;
    }

    /**
     * Setter for SpcIncompInd.
     * Reason that the SPC authentication was not completed. This field is required if
     * device_channel = 02 (BRW) and the 3DS Requestor attempts to invoke SPC API and there is an
     * error. Available for supporting EMV 3DS 2.3.1 and later versions.
     * @param spcIncompInd Value for String
     */
    @JsonSetter("spc_incomp_ind")
    public void setSpcIncompInd(String spcIncompInd) {
        this.spcIncompInd = spcIncompInd;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ThreeDsRequestor into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ThreeDsRequestor [" + "threeDsRequestorAuthenticationInd="
                + threeDsRequestorAuthenticationInd + ", threeDsRequestorAuthenticationInfo="
                + threeDsRequestorAuthenticationInfo + ", threeDsRequestorChallengeInd="
                + threeDsRequestorChallengeInd + ", threeDsRequestorPriorAuthenticationInfo="
                + threeDsRequestorPriorAuthenticationInfo + ", threeDsRequestorDecReqInd="
                + threeDsRequestorDecReqInd + ", threeDsRequestorDecMaxTime="
                + threeDsRequestorDecMaxTime + ", threeDsRequestorSpcSupport="
                + threeDsRequestorSpcSupport + ", spcIncompInd=" + spcIncompInd
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ThreeDsRequestor.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ThreeDsRequestor.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(threeDsRequestorAuthenticationInd)
                .threeDsRequestorAuthenticationInfo(getThreeDsRequestorAuthenticationInfo())
                .threeDsRequestorChallengeInd(getThreeDsRequestorChallengeInd())
                .threeDsRequestorPriorAuthenticationInfo(getThreeDsRequestorPriorAuthenticationInfo())
                .threeDsRequestorDecReqInd(getThreeDsRequestorDecReqInd())
                .threeDsRequestorDecMaxTime(getThreeDsRequestorDecMaxTime())
                .threeDsRequestorSpcSupport(getThreeDsRequestorSpcSupport())
                .spcIncompInd(getSpcIncompInd());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ThreeDsRequestor}.
     */
    public static class Builder {
        private ThreeDsRequestorAuthenticationInd threeDsRequestorAuthenticationInd;
        private List<ThreeDsRequestorAuthenticationInfo> threeDsRequestorAuthenticationInfo;
        private List<ThreeDsRequestorChallengeInd> threeDsRequestorChallengeInd;
        private List<ThreeDsRequestorPriorAuthenticationInfo> threeDsRequestorPriorAuthenticationInfo;
        private ThreeDsRequestorDecReqInd threeDsRequestorDecReqInd;
        private Integer threeDsRequestorDecMaxTime;
        private ThreeDsRequestorSpcSupport threeDsRequestorSpcSupport;
        private String spcIncompInd;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  threeDsRequestorAuthenticationInd  ThreeDsRequestorAuthenticationInd value for
         *         threeDsRequestorAuthenticationInd.
         */
        public Builder(ThreeDsRequestorAuthenticationInd threeDsRequestorAuthenticationInd) {
            this.threeDsRequestorAuthenticationInd = threeDsRequestorAuthenticationInd;
        }

        /**
         * Setter for threeDsRequestorAuthenticationInd.
         * @param  threeDsRequestorAuthenticationInd  ThreeDsRequestorAuthenticationInd value for
         *         threeDsRequestorAuthenticationInd.
         * @return Builder
         */
        public Builder threeDsRequestorAuthenticationInd(
                ThreeDsRequestorAuthenticationInd threeDsRequestorAuthenticationInd) {
            this.threeDsRequestorAuthenticationInd = threeDsRequestorAuthenticationInd;
            return this;
        }

        /**
         * Setter for threeDsRequestorAuthenticationInfo.
         * @param  threeDsRequestorAuthenticationInfo  List of ThreeDsRequestorAuthenticationInfo
         *         value for threeDsRequestorAuthenticationInfo.
         * @return Builder
         */
        public Builder threeDsRequestorAuthenticationInfo(
                List<ThreeDsRequestorAuthenticationInfo> threeDsRequestorAuthenticationInfo) {
            this.threeDsRequestorAuthenticationInfo = threeDsRequestorAuthenticationInfo;
            return this;
        }

        /**
         * Setter for threeDsRequestorChallengeInd.
         * @param  threeDsRequestorChallengeInd  List of ThreeDsRequestorChallengeInd value for
         *         threeDsRequestorChallengeInd.
         * @return Builder
         */
        public Builder threeDsRequestorChallengeInd(
                List<ThreeDsRequestorChallengeInd> threeDsRequestorChallengeInd) {
            this.threeDsRequestorChallengeInd = threeDsRequestorChallengeInd;
            return this;
        }

        /**
         * Setter for threeDsRequestorPriorAuthenticationInfo.
         * @param  threeDsRequestorPriorAuthenticationInfo  List of
         *         ThreeDsRequestorPriorAuthenticationInfo value for
         *         threeDsRequestorPriorAuthenticationInfo.
         * @return Builder
         */
        public Builder threeDsRequestorPriorAuthenticationInfo(
                List<ThreeDsRequestorPriorAuthenticationInfo> threeDsRequestorPriorAuthenticationInfo) {
            this.threeDsRequestorPriorAuthenticationInfo = threeDsRequestorPriorAuthenticationInfo;
            return this;
        }

        /**
         * Setter for threeDsRequestorDecReqInd.
         * @param  threeDsRequestorDecReqInd  ThreeDsRequestorDecReqInd value for
         *         threeDsRequestorDecReqInd.
         * @return Builder
         */
        public Builder threeDsRequestorDecReqInd(
                ThreeDsRequestorDecReqInd threeDsRequestorDecReqInd) {
            this.threeDsRequestorDecReqInd = threeDsRequestorDecReqInd;
            return this;
        }

        /**
         * Setter for threeDsRequestorDecMaxTime.
         * @param  threeDsRequestorDecMaxTime  Integer value for threeDsRequestorDecMaxTime.
         * @return Builder
         */
        public Builder threeDsRequestorDecMaxTime(Integer threeDsRequestorDecMaxTime) {
            this.threeDsRequestorDecMaxTime = threeDsRequestorDecMaxTime;
            return this;
        }

        /**
         * Setter for threeDsRequestorSpcSupport.
         * @param  threeDsRequestorSpcSupport  ThreeDsRequestorSpcSupport value for
         *         threeDsRequestorSpcSupport.
         * @return Builder
         */
        public Builder threeDsRequestorSpcSupport(
                ThreeDsRequestorSpcSupport threeDsRequestorSpcSupport) {
            this.threeDsRequestorSpcSupport = threeDsRequestorSpcSupport;
            return this;
        }

        /**
         * Setter for spcIncompInd.
         * @param  spcIncompInd  String value for spcIncompInd.
         * @return Builder
         */
        public Builder spcIncompInd(String spcIncompInd) {
            this.spcIncompInd = spcIncompInd;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ThreeDsRequestor} object using the set fields.
         * @return {@link ThreeDsRequestor}
         */
        public ThreeDsRequestor build() {
            ThreeDsRequestor model =
                    new ThreeDsRequestor(threeDsRequestorAuthenticationInd,
                            threeDsRequestorAuthenticationInfo, threeDsRequestorChallengeInd,
                            threeDsRequestorPriorAuthenticationInfo, threeDsRequestorDecReqInd,
                            threeDsRequestorDecMaxTime, threeDsRequestorSpcSupport, spcIncompInd);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
