/*
 * FortisApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * TypeId to be used.
 */
public enum TypeId {
    ENUM_20,

    ENUM_21,

    ENUM_22,

    ENUM_30,

    ENUM_40,

    ENUM_50,

    /**
     * Unknown values will be mapped by this enum member
     */
    _UNKNOWN;


    private static TreeMap<Integer, TypeId> valueMap = new TreeMap<>();
    private Integer value;

    static {
        ENUM_20.value = 20;
        ENUM_21.value = 21;
        ENUM_22.value = 22;
        ENUM_30.value = 30;
        ENUM_40.value = 40;
        ENUM_50.value = 50;
        _UNKNOWN.value = null;

        valueMap.put(20, ENUM_20);
        valueMap.put(21, ENUM_21);
        valueMap.put(22, ENUM_22);
        valueMap.put(30, ENUM_30);
        valueMap.put(40, ENUM_40);
        valueMap.put(50, ENUM_50);
    }

    /**
     * Returns the enum member associated with the given integer value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given integer value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static TypeId constructFromInteger(Integer toConvert) throws IOException {
        TypeId enumValue = fromInteger(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given integer value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given integer value.
     */
    public static TypeId fromInteger(Integer toConvert) {
        if (!valueMap.containsKey(toConvert)) {
            return _UNKNOWN;
        }
        return valueMap.get(toConvert);
    }

    /**
     * Returns the integer value associated with the enum member.
     * @return The integer value against enum member.
     */
    @JsonValue
    public Integer value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        if (value == null) {
            return null;
        }
        return value.toString();
    }

    /**
     * Convert list of TypeId values to list of integer values.
     * @param toConvert The list of TypeId values to convert.
     * @return List of representative integer values.
     */
    public static List<Integer> toValue(List<TypeId> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<Integer> convertedValues = new ArrayList<>();
        for (TypeId enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 