/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for V1WalletProviderApplePayValidateMerchantRequest type.
 */
public class V1WalletProviderApplePayValidateMerchantRequest
        extends BaseModel {
    private String url;
    private String merchantId;
    private String domainName;
    private String displayName;

    /**
     * Default constructor.
     */
    public V1WalletProviderApplePayValidateMerchantRequest() {
    }

    /**
     * Initialization constructor.
     * @param  url  String value for url.
     * @param  merchantId  String value for merchantId.
     * @param  domainName  String value for domainName.
     * @param  displayName  String value for displayName.
     */
    public V1WalletProviderApplePayValidateMerchantRequest(
            String url,
            String merchantId,
            String domainName,
            String displayName) {
        this.url = url;
        this.merchantId = merchantId;
        this.domainName = domainName;
        this.displayName = displayName;
    }

    /**
     * Getter for Url.
     * Url obtained in the ApplePay button click event. Apple's URL that needs to be called to
     * validate merchant.
     * @return Returns the String
     */
    @JsonGetter("url")
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * Url obtained in the ApplePay button click event. Apple's URL that needs to be called to
     * validate merchant.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for MerchantId.
     * Merchant ID
     * @return Returns the String
     */
    @JsonGetter("merchantId")
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * Setter for MerchantId.
     * Merchant ID
     * @param merchantId Value for String
     */
    @JsonSetter("merchantId")
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * Getter for DomainName.
     * Domain Name
     * @return Returns the String
     */
    @JsonGetter("domainName")
    public String getDomainName() {
        return domainName;
    }

    /**
     * Setter for DomainName.
     * Domain Name
     * @param domainName Value for String
     */
    @JsonSetter("domainName")
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    /**
     * Getter for DisplayName.
     * Title
     * @return Returns the String
     */
    @JsonGetter("displayName")
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Setter for DisplayName.
     * Title
     * @param displayName Value for String
     */
    @JsonSetter("displayName")
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Converts this V1WalletProviderApplePayValidateMerchantRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "V1WalletProviderApplePayValidateMerchantRequest [" + "url=" + url + ", merchantId="
                + merchantId + ", domainName=" + domainName + ", displayName=" + displayName
                + ", additionalProperties=" + getAdditionalProperties() + "]";
    }

    /**
     * Builds a new {@link V1WalletProviderApplePayValidateMerchantRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link V1WalletProviderApplePayValidateMerchantRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(url, merchantId, domainName, displayName);
        return builder;
    }

    /**
     * Class to build instances of {@link V1WalletProviderApplePayValidateMerchantRequest}.
     */
    public static class Builder {
        private String url;
        private String merchantId;
        private String domainName;
        private String displayName;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  url  String value for url.
         * @param  merchantId  String value for merchantId.
         * @param  domainName  String value for domainName.
         * @param  displayName  String value for displayName.
         */
        public Builder(String url, String merchantId, String domainName, String displayName) {
            this.url = url;
            this.merchantId = merchantId;
            this.domainName = domainName;
            this.displayName = displayName;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for merchantId.
         * @param  merchantId  String value for merchantId.
         * @return Builder
         */
        public Builder merchantId(String merchantId) {
            this.merchantId = merchantId;
            return this;
        }

        /**
         * Setter for domainName.
         * @param  domainName  String value for domainName.
         * @return Builder
         */
        public Builder domainName(String domainName) {
            this.domainName = domainName;
            return this;
        }

        /**
         * Setter for displayName.
         * @param  displayName  String value for displayName.
         * @return Builder
         */
        public Builder displayName(String displayName) {
            this.displayName = displayName;
            return this;
        }

        /**
         * Builds a new {@link V1WalletProviderApplePayValidateMerchantRequest} object using the set
         * fields.
         * @return {@link V1WalletProviderApplePayValidateMerchantRequest}
         */
        public V1WalletProviderApplePayValidateMerchantRequest build() {
            return new V1WalletProviderApplePayValidateMerchantRequest(url, merchantId, domainName,
                    displayName);
        }
    }
}
