/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Values51Enum to be used.
 */
public enum Values51Enum {
    ACCOUNT_NUMBER,

    ACCOUNT_HOLDER_NAME,

    ROUTING_NUMBER;


    private static TreeMap<String, Values51Enum> valueMap = new TreeMap<>();
    private String value;

    static {
        ACCOUNT_NUMBER.value = "account_number";
        ACCOUNT_HOLDER_NAME.value = "account_holder_name";
        ROUTING_NUMBER.value = "routing_number";

        valueMap.put("account_number", ACCOUNT_NUMBER);
        valueMap.put("account_holder_name", ACCOUNT_HOLDER_NAME);
        valueMap.put("routing_number", ROUTING_NUMBER);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Values51Enum constructFromString(String toConvert) throws IOException {
        Values51Enum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Values51Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Values51Enum values to list of string values.
     * @param toConvert The list of Values51Enum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Values51Enum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Values51Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 