/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * WalletTypeEnum to be used.
 */
public enum WalletTypeEnum {
    ENUM_000,

    ENUM_101,

    ENUM_103,

    ENUM_216,

    ENUM_217,

    ENUM_327;


    private static TreeMap<String, WalletTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_000.value = "000";
        ENUM_101.value = "101";
        ENUM_103.value = "103";
        ENUM_216.value = "216";
        ENUM_217.value = "217";
        ENUM_327.value = "327";

        valueMap.put("000", ENUM_000);
        valueMap.put("101", ENUM_101);
        valueMap.put("103", ENUM_103);
        valueMap.put("216", ENUM_216);
        valueMap.put("217", ENUM_217);
        valueMap.put("327", ENUM_327);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static WalletTypeEnum constructFromString(String toConvert) throws IOException {
        WalletTypeEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static WalletTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of WalletTypeEnum values to list of string values.
     * @param toConvert The list of WalletTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<WalletTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (WalletTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 